### ISSUE TITLE
Confusing table for helm chart

### ISSUE THREAD

**Issue by leodotcloud** [rancher/docs#1000]
On this page: 
https://rancher.com/docs/rancher/v2.x/en/catalog/custom/

Looking at this table:
<img width="1043" alt="screen shot 2018-11-20 at 1 41 12 pm" src="https://user-images.githubusercontent.com/19392926/48804736-4c276800-ecca-11e8-9e65-32e31de64a98.png">

I thought I need to place `Chart.yaml`, `questions.yaml` files under `charts/` and `values.yaml` under `templates` directory.

The info in that table needs a different representation to avoid such confusion.

**Comment by deniseschannon** [comment]
Fixed in https://github.com/rancher/docs/pull/1046
