### ISSUE TITLE
MultiCluster App

### ISSUE THREAD

**Issue by deniseschannon** [rancher/docs#1015]

**Comment by MBishop17** [comment]
Talk to @alena1108 for a demo, who is drafting the docs.

**Comment by alena1108** [comment]
RBAC should be covered in a great level of detail.

**Comment by alena1108** [comment]
@mrajashree we already have a pr for a multi cluster app. You might want to work based of it

https://github.com/rancher/docs/pull/1088/files

**Comment by mrajashree** [comment]
@alena1108 oh, thanks! will do
