### ISSUE TITLE
Rancher ARM Support

### ISSUE THREAD

**Issue by deniseschannon** [rancher/docs#1022]

**Comment by MBishop17** [comment]
Need docs from @loganhz or @niusmallnan  for deploying clusters to ARM devices.

**Comment by loganhz** [comment]
Now we are putting the ARM support doc on the top level menu.

Not sure if we should move it into `Installation -> Install on ARM` and `Provisioning Kubernetes Clusters -> Rancher Launched Kubernetes -> Creating a cluster on ARM`

**Comment by loganhz** [comment]
@orangedeng Can you review it, please?
