### ISSUE TITLE
Pluggable Cluster Drivers 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/docs#1024]
Cover where/how to enable other cluster drivers as well as pointing to docs on how someone would develop their own.

**Comment by MBishop17** [comment]
Cluster Driver: think node drivers for kubernetes as a service.

"Node Drivers" is now "Custom Drivers"

Look through doc set for instances of "node drivers". Change to "custom drivers".

Ask @nathan-jenan-rancher for example reference. Find a place in our docs to point toward Nathan's reference.

**Comment by daxmc99** [comment]
See https://github.com/rancher/rancher/issues/12698

**Comment by daxmc99** [comment]
See https://github.com/rancher/docs/pull/1236
