### ISSUE TITLE
Describe use of NetworkManager on EL like systems

### ISSUE THREAD

**Issue by superseb** [rancher/docs#1052]
NetworkManager is known to interfere with network related components on a system, we need to point this out and possibly provide known working configs if NetworkManager is required to be enabled.

**Comment by davidnuzik** [comment]
This is causing issues when attempting to run Rancher on RKE2 clusters (see https://github.com/rancher/rke2/issues/786) We suppport running rancher on RKE2 clusters. We should fix or document this so we indicate what the workaround is.

**Comment by bmdepesa** [comment]
The same problem (https://github.com/rancher/rke2/issues/786) and workaround specified for RKE2 also applies to RKE1. 

Workaround is documented here: https://github.com/rancher/rke2/pull/836

We should add this information to the RKE1 documentation.

**Comment by davidnuzik** [comment]
Cross-linking here for future reference. On the RKE2 side, we just called out the issue in our March patch release notes. We created a docs PR in rke2 project [here](https://github.com/rancher/rke2/pull/836) and this is live and accessible on the rke2 docs site in various places so it's clearly called out to the user.
