### ISSUE TITLE
More detailed Hardware Requirements. 

### ISSUE THREAD

**Issue by wolfoo2931** [rancher/docs#1055]
In the installation instructions it is shown what hardware requirements are needed for a small, medium, large cluster. We would be interested in a more dynamic requirements calculation. It is not clear how the requirements change for other Setups. Like Operating 5 Clusters with 500 nodes or 50 Clusters with 50 Nodes.

**Comment by wolfoo2931** [comment]
Also interesting is whether hardware requirements for the following setups 
- 50 Imported Clusters
- 50 RKE Clusters
- 50 Cloud Hosted Clusters (Hosted by e.g. AWS EKS)

**Comment by btat** [comment]
Closing as duplicate of https://github.com/rancher/rancher-docs/issues/103.
