### ISSUE TITLE
Hyphenation on small screens works improperly. Turn it off

### ISSUE THREAD

**Issue by lukaszswitaj** [rancher/docs#1097]
Hello,

Hyphenation works incorrectly. This is especially troublesome on mobile devices with small screens. It makes reading and understanding the text very difficult.

In my opinion, the side margins on mobile devices are too large, the text should be left-aligned, and the hyphenation completely off.

![obraz](https://user-images.githubusercontent.com/26921579/51325051-66808680-1a6c-11e9-92c6-002932a4ffb2.png)

**Comment by lvuch** [comment]
fixed in this commit to theme https://github.com/rancherlabs/website-theme/commit/9c96d4cdc06b69d49d9c32e0219caf9c1274567c

**Comment by lukaszswitaj** [comment]
Thank you.

Is it released? I can't see any improvement in Firefox for Android (stable). In MIUI Browser it's OK.

And what about too wide margins?

**Comment by lukaszswitaj** [comment]
It's still broken...
