### ISSUE TITLE
RancherOS upgrade notes

### ISSUE THREAD

**Issue by patrick0057** [rancher/docs#1102]
Please add documentation to RancherOS Upgrade instructions for the following scenarios.

1. Upgrading to RancherOS 1.4.0 and greater you must move or copy your files from /var/lib/docker on the host to /var/lib/user-docker otherwise your data will not be available.
 
2. Upgrading to RancherOS 1.3.0 and greater, if you were using docker configuration to configure your bridge you will need to reconfigure your bridge settings with the following commands after the upgrade as the bridge.conf is no longer used.
`ros config set rancher.docker.extra_args ['--bip=10.1.0.1/24','--fixed-cidr=10.1.0.0/24']`

3. If you are upgrading to 1.4.0 and greater and wish to have a bridge IP set for system docker then you will need to add it back as it was removed in 1.3.0 and re-added in 1.4.0 with CNI style networking removed.
`ros config set rancher.system_docker.bip 10.0.0.1/16`

**Comment by niusmallnan** [comment]
@patrick0057 Thanks for your suggestions. I understand the first and third points.
But the second point, the `bridge.conf` only worked on the docker-sys in the earlier version. For the user-docker bridge, I think users should use the `rancher.docker.extra_args`. So I think we don’t have to mention the second point.

**Comment by patrick0057** [comment]
Sounds good, thank you @niusmallnan
