### ISSUE TITLE
Support Cloud-init Configuration for Exoscale Node Template

### ISSUE THREAD

**Issue by srueg** [rancher/docs#1120]
I'd like to be able to specify custom cloud-init for Exoscale node templates. The [Hetzner node driver](https://github.com/mxschmitt/ui-driver-hetzner) for example supports this.
Any chance you can support this?

**Comment by superseb** [comment]
Exoscale was updated in https://github.com/rancher/machine/pull/14 but it seems that the cloudinit/userdata is still referencing a path of the file in Docker Machine. 

As this is the docs repo, can you try the new implementation and else file a feature request in https://github.com/rancher/rancher/issues/new
