### ISSUE TITLE
Add ssh key documentation for EKS

### ISSUE THREAD

**Issue by daxmc99** [rancher/docs#1130]
Add documentation for new ssh ec2 key pair field in EKS. Allows use of key pairs already created in ec2.

https://github.com/rancher/rancher/pull/17868
https://github.com/rancher/rancher/issues/14598
Assign @daxmc99

**Comment by vincent99** [comment]
This is only for EKS, not the EC2 machine driver, right? (Machine already has an option for key, but it then requires provisioning to use that private key and we don't have it)

**Comment by daxmc99** [comment]
Correct, this is only for EKS. Currently, we create a key for each EKS cluster during the bringup but that PR allows a user to specify a key name that already exists in EC2 and use that.

**Comment by deniseschannon** [comment]
This was made available in v2.3 and needs to be added to the docs.

**Comment by catherineluse** [comment]
Closing because it is already documented. https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/#secrets-encryption
