### ISSUE TITLE
RKE restore docs

### ISSUE THREAD

**Issue by patrick0057** [rancher/docs#1150]
There should be a note in the RKE HA restore section(https://rancher.com/docs/rancher/v2.x/en/backups/restorations/ha-restoration/) about removing any old ~/.kube/config and cluster.yml before proceeding with a restore.  Alternatively the customer can run `rke remove` which would remove these files automatically.  If these files exist and a restore is attempted, the restore will fail without a helpful error as to why.

**Comment by alena1108** [comment]
We should make sure to cover:

* the diff between legacy snapshots and 2.2
* the way to convert (not automatic, done when editing cluster in the UI)
