### ISSUE TITLE
Add note when upgrading Rancher 1.6 HA clusters

### ISSUE THREAD

**Issue by mattmattox** [rancher/docs#1158]
Please add the following note to page https://rancher.com/docs/rancher/v1.6/en/upgrading/#multi-nodes

NOTE:
Ensure Rancher server containers, as they are brought up, are allowed sufficient "settling-down" time before starting the next Rancher server container.  A baseline for the database's CPU usage could be used as a gauge to determine how much time is sufficient time. As a new Rancher server comes up, watch spikes in CPU usage to settle down to near-baseline levels before starting the next Rancher server. Additionally, Rancher logs can be monitored to see if a server has had sufficient time to settle down before starting the next one.

**Comment by mattmattox** [comment]
It has been my experience that not giving sufficient time causes DB spikes and can potentially cause the upgrade to be stuck due to a non-responsive db. The workaround being to stop all Rancher server containers and restart the upgrade process with a longer delay.

Also, this mainly impacts larger environments with a large number of clusters, hosts, and workloads.

**Comment by catherineluse** [comment]
Closing this issue because this PR was merged https://github.com/rancher/rancher.github.io/pull/1078
