### ISSUE TITLE
Update docs to provide correct info for ROS OpenStack image

### ISSUE THREAD

**Issue by jambajaar** [rancher/docs#1159]
The docs say that an OpenStack image of ROS is available:
https://rancher.com/docs/os/v1.2/en/running-rancheros/cloud/openstack/

However, there isn't anything that indicates an OpenStack image in the assets list in the Releases page:
https://github.com/rancher/os/releases/tag/v1.5.1 

Turns out the OpenStack image can be downloaded from here:
https://github.com/rancher/os#cloud-links

It is in QCOW3 format that is backward compatible with QCOW2 https://wiki.qemu.org/Features/Qcow3#Fully_QCOW2_backwards-compatible_feature_set

Need to update this Rancher docs page to indicate correct location/format for OpenStack image

**Comment by niusmallnan** [comment]
> The docs say that an OpenStack image of ROS is available:
https://rancher.com/docs/os/v1.2/en/running-rancheros/cloud/openstack/

We should use this link https://rancher.com/docs/os/v1.x/en/running-rancheros/cloud/openstack/

> However, there isn't anything that indicates an OpenStack image in the assets list in the Releases page:
https://github.com/rancher/os/releases/tag/v1.5.1

I have added the artifacts to the release page. 
This link is another option. https://github.com/rancher/os#cloud-links

> It is in QCOW3 format that is backward compatible with QCOW2 https://wiki.qemu.org/Features/Qcow3#Fully_QCOW2_backwards-compatible_feature_set

I will make a PR to fix it.

**Comment by btat** [comment]
Not actionable.
