### ISSUE TITLE
health check path for setting Rancher HA on k3s cluster requires /ping instead of /healthz

### ISSUE THREAD

**Issue by tfiduccia** [rancher/docs#1241]
In the HA documentation.  It says to set the health check path to /healthz.  To setup rancher HA on k3s cluster that will have to be /ping.  Would be nice to have this info added to the documentation.

https://rancher.com/docs/rancher/v2.x/en/installation/ha/create-nodes-lb/nlb/#create-target-groups

**Comment by catherineluse** [comment]
Is this issue up-to-date with the newest K3s version? I searched for a reference to /healthz in the k3s docs and couldn't find it. I couldn't find a reference to /ping either.

**Comment by dkeightley** [comment]
Yes, this should be consistent with all k3s versions as traefik is the default ingress. I've documented some differences below:

**traefik**
By default `/ping` is always matched (regardless of `Host`), and a response [from traefik itself](https://docs.traefik.io/operations/ping/) is always served.

`/healthz` is not handled by default, successful requests require the rancher ingress to be matched.

- `/ping` - yes, traefik will default to responding directly
- `/healthz` - only if using the `Host` header to match the rancher ingress

In the case of ELB health checks the instance IP address is used as the `Host`, and wouldn't match the rancher ingress (`/healthz` will fail ELB health checks with traefik).

**ingress-nginx**
By default `/ping` isn't matched, will rely on a `Host` header matching the rancher ingress to forward to Rancher Pods.

If no matching `Host` header is used, [will forward this](https://kubernetes.github.io/ingress-nginx/user-guide/default-backend/) to the `default-http-backend` Pod. If it matches, requests are forwarded to Rancher Pods.

- `/ping` - only if using the `Host` header to match the rancher ingress
- `/healthz` yes, either `default-http-backend` or Rancher will respond, which one depends on a matching `Host` header. 

It may be good to call out the above for rancher/k3s docs, additionally I could think of some best practices we might consider documenting:
- The `default-http-backend` deployment is a single replica with CPU/memory limits, therefore it is potentially a risky and inaccurate option to rely on for health checks. For eg, if the Pod is down even periodically it could cause all node health checks to fail.
- Use the `Host` header (rancher hostname) combined with `/healthz` (both rke/k3s) wherever possible to simulate an accurate health check (response from Rancher, not the ingress).

**Comment by catherineluse** [comment]
I'm closing this issue because https://github.com/rancher/docs/pull/2548#pullrequestreview-430060252 was merged
