### ISSUE TITLE
Concepts: Cluster - Kubeconfig File

### ISSUE THREAD

**Issue by deniseschannon** [rancher/docs#125]
4.	Clusters
     a.	~What’s a Cluster?~
             ~A short explanation of what clusters are and their role within Kubernetes.~
     b.	~Cluster Creation~
            i.	~Node Components~
                       1.	~Etcd requirements~
                       2.	~Control requirements~
                       3.	~Worker requirements/best practices~
             ii.	~Cluster Providers~
                      1.	~RKE~
                      2.	~Cloud Cluster~
                      3.	~Import~
          **c.	Kubeconfig file**

**Comment by MBishop17** [comment]
Closing since #283 is closed.
