### ISSUE TITLE
Custom CA root certificate page is missing steps for HA install

### ISSUE THREAD

**Issue by janeczku** [rancher/docs#1252]
https://rancher.com/docs/rancher/v2.x/en/admin-settings/custom-ca-root-certificate/

It only shows how to configure CA root certificate in a standalone container. Need to add steps for HA install or  link to the correspondin section: https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/chart-options/#additional-trusted-cas

**Comment by superseb** [comment]
And it needs updating to match the way the Helm chart does it

**Comment by superseb** [comment]
https://rancher.com/docs/rancher/v2.x/en/installation/resources/encryption/custom-ca-root-certificate/ containts two links for Docker and Kubernetes install
