### ISSUE TITLE
Monitoring - metrics vary on different  k8s cluster type/provider

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/docs#1278]
For the cluster level monitoring, the number and types of metrics in the cluster dashboard vary on different k8s cluster type/provider, so we should mention that somewhere in the documentation.

**Comment by loganhz** [comment]
We already have the notes for it via `/tools/monitoring/#kubernetes-components-metrics` and `/rancher/v2.x/en/tools/monitoring/#etcd-metrics`

**Comment by deniseschannon** [comment]
@loganhz i've re-done the monitoring docs, so i think this got lost.

**Comment by deniseschannon** [comment]
these metrics are denoted for RKE clusters only: https://staging.rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/monitoring/cluster-metrics/#etcd-metrics

https://staging.rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/monitoring/cluster-metrics/#kubernetes-components-metrics
