### ISSUE TITLE
Documentation contains many links to old v0.1.x RKE docs

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#1326]
This issue just lists a few areas where I see links to old RKE docs. It should just serve as a general reminder that the docs also need to have these (in ALL areas not just those listed below) updated to newer RKE docs.

I'm not sure if we want to do this right before pushing rancher 2.x docs to prod or right after when RKE v0.2 is up...

Here are some areas I found bad links. Someone can use these as a guide and just do a search in **ALL** docs for links like these:

https://staging.rancher.com/docs/rancher/v2.x/en/installation/ha/#required-tools : "rke" hyperlink links to old v0.1.x

 -> Same as above, "RKE Requirements" hyperlink points to old doc see: https://staging.rancher.com/docs/rancher/v2.x/en/installation/ha/create-nodes-lb/

-> Same as above, "RKE Documentation" hyperlink points to old doc see: https://staging.rancher.com/docs/rancher/v2.x/en/installation/ha/kubernetes-rke/#advanced-configurations

-> Same as above, "RKE Install" hyperlink points to old doc see: https://staging.rancher.com/docs/rancher/v2.x/en/installation/ha/rke-add-on/layer-4-lb/#4-install-rke

-> Same as above, "RKE Documentation: Config Options" hyperlink points to old doc see: https://staging.rancher.com/docs/rancher/v2.x/en/installation/ha/rke-add-on/layer-4-lb/#5-download-rke-config-file-template

**Comment by deniseschannon** [comment]
We've moved to `docs/rke/latest/en` and updated the links in rancher.
