### ISSUE TITLE
Documentation contains some stale screenshots

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#1327]
The documentation contains some stale screenshots. There may be some more areas than those listed below.

https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-single-node/config-rancher-for-private-reg/ : Old screenshot pictured showing old nav bar.

 -> Same thing here: https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-high-availability/config-rancher-for-private-reg/
https://rancher.com/docs/rancher/v2.x/en/installation/options/api-audit-log/#rancher-web-gui : shows old global menu.

**Comment by deniseschannon** [comment]
Yes, the plan is to remove the UI components where possible.

**Comment by catherineluse** [comment]
Closing this issue because the screenshots were removed
