### ISSUE TITLE
RKE docs should highlight the importance of the `<file>.rkestate` and `kube_config_<file>.yml` files

### ISSUE THREAD

**Issue by Oats87** [rancher/docs#1340]
With the release of `rke 0.2.0`, the `<file>.rkestate` and `kube_config_<file>.rkestate` (where `<file>` is the file for the cluster config) are extremely important. We do not do a good job of calling out the fact that these files are important and should be kept around.

**Comment by deniseschannon** [comment]
https://rancher.com/docs/rke/v0.1.x/en/installation/#kubernetes-cluster-state
