### ISSUE TITLE
add faq for how to do advanced customized logging using fluentd

### ISSUE THREAD

**Issue by deniseschannon** [rancher/docs#1348]
customized logging exists now, but you might not notice/realize it, so we should add a faq about it. 

step 4 when enabling logging

https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/logging/
https://rancher.com/docs/rancher/v2.x/en/project-admin/tools/logging/

**Comment by superseb** [comment]
This is now covered on https://rancher.com/docs/rancher/v2.x/en/logging/v2.5/ with examples.
