### ISSUE TITLE
RKE docs for v0.2.x has v0.1.x in URL

### ISSUE THREAD

**Issue by dnoland1** [rancher/docs#1350]
The RKE docs link is `https://rancher.com/docs/rke/v0.1.x/en/`, however we are now on RKE v0.2.1. Maybe URL should change to v0.2.x or v0.x.

**Comment by dnoland1** [comment]
Just noticed there's already a PR for this - https://github.com/rancher/docs/pull/1196

**Comment by deniseschannon** [comment]
It's moving to `docs/rke/latest/en` and is in master.
