### ISSUE TITLE
Document etcd S3 backup using IAM instance profile instead of API keys

### ISSUE THREAD

**Issue by janeczku** [rancher/docs#1395]
Need to document:

1. That `--access-key` and `--secret-key` are not required if the etcd nodes are AWS EC2 instances that have been configured with a suitable IAM instance profile
2. An example IAM role describing the minimal permissions required to store/retrieve backups from S3

https://rancher.com/docs/rke/latest/en/etcd-snapshots/#options-for-rke-etcd-snapshot-save

**Comment by Tediferous** [comment]
👍
