### ISSUE TITLE
ingress-nginx on bare metal does support layer-4 contrary to the docs

### ISSUE THREAD

**Issue by IGWAxel** [rancher/docs#1396]
https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/load-balancers-and-ingress/load-balancers/#support-for-layer-4-load-balancing

Suggests that no layer4 ingress is supportet for example on "RKE on Custom Hosts
(e.g. bare-metal servers)".

However after reading and testing (on my bare-metal rke provisioned node) this suggestion
   https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/ 
I found it works like a charm out-of-the-box to just add appropriate lines to the "tcp-services" config-map through ranchers-UI (no kubectl hacking required!).

I think this option is well worth mentioning in the documentation, especially as the NodePort alternative has a limited port-range

**Comment by vincent99** [comment]
That's not really what is meant there.  Yes there is some capability in nginx-ingress, and it was going to be removed entirely but it appears they've walked that back.

But it does not help with services of type LoadBalancer that you're going to find in helm charts and such, which is what people are generally taking about when they say L4 LB.

(It should probably mention MetalLB though..)

**Comment by IGWAxel** [comment]
Firstly: Thanks a lot for pointing out metalLB to me, that was clearly a piece of the puzzle that was missing to me.

Now to my suggestions about the documentation.
 
There is something missing when the docs don’t give a way into a metal-cluster for anything other than http(s) and the (range-limited) node-ports. I now (thanks to your help!) understand the problem (I think), and I have tried to boil down what I was missing in the docs that caused me (and other too, judging by posts at stackoverflow etc.) to take a painful wrong turn on the first read.

The docs about [#ingress](https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/load-balancers-and-ingress/#ingress) says: 
> “As mentioned in the limitations above, using a load balancer per service can be expensive. You can get around this issue using an ingress.”

That is in my opinion only part of the truth, the addition of the following points would help clarify I think:

- Ingress (better thought of as http-ingress) solves the problem of multiple web-services in the cluster **sharing the same exposed cluster-level nginx** (and related privileged node-ports: 80,443). Ingress does not solve any other form of entry into the cluster, such entry is a job for the LoadBalancer.

- Each kubernetes Ingress resource corresponds conceptually roughly to a file in /etc/nginx/sites-available/ containing a server{} stanza. They play nicely together without having to know about eachother.


The docs about LoadBalancers unfortunately mix and mash the concepts and calls “Nginx ingress controller” a load-balancer even though it has nothing to do with the kuberenetes koncept `serviceType=LoadBalancer`. But the bitter reality of concept-names clashing is what it is. 

Because “Nginx Ingress Controller” is listed as a L7 loadbalancer here: [#support-for-layer-7-load-balancing](https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/load-balancers-and-ingress/load-balancers/#support-for-layer-7-load-balancing)
it would follow the pattern and give very practical help to the reader to also mention the:
- limited L4 support given by the global config-map (even though the drawbacks you mentioned about helm packets etc.)
- third party MetalLB (Thanks alot for pointing that out to me)
In the table here: [#support-for-layer-4-load-balancing](https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/load-balancers-and-ingress/load-balancers/#support-for-layer-4-load-balancing)

I.e: Instead of “Not supported” it the [table entries](https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/load-balancers-and-ingress/load-balancers/#support-for-layer-4-load-balancing) it could say 
 - “Limited nginx ingress* or 3rd party https://metallb.universe.tf/”

And the asteirsk explained below the table as:
> *) Through a single globally managed config-map, see: https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/1964 was merged
