### ISSUE TITLE
recommendations around tuning etcd election and heartbeat settings

### ISSUE THREAD

**Issue by aemneina** [rancher/docs#1400]
I believe heartbeat interval should be set in relation to the maximum amount of time for a packet round trip between etcd nodes, to avoid unnecessary warnings.
      heartbeat-interval: "500"

likewise the election timeout needs to be set factoring the heartbeat interval setting. 10x the heartbeat interval according to the etcd tuning guide. 
election-timeout: "5000"

https://coreos.com/etcd/docs/latest/tuning.html

**Comment by superseb** [comment]
Can you describe what more you would like to see besides the description and the link to more information how to tune it? 

https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/production/#network-latency

**Comment by aemneina** [comment]
I'd like how to calculate heartbeat interval and election timeout on our page, instead of digging through the etcd tuning guide. Not super important just making the information more easily accessible.

**Comment by catherineluse** [comment]
Closing this issue because information about etcd tuning was added to the best practices guide. http://localhost:9001/rancher/v2.x/en/best-practices/v2.5/rancher-server/deployment-types/#make-sure-nodes-are-configured-correctly-for-kubernetes
