### ISSUE TITLE
Docs for feature: Istio - Integrated with Rancher with 2 UI components, routing and monitoring of the traffic

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#1473]

**Comment by deniseschannon** [comment]
https://staging.rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/service-mesh/
https://staging.rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/service-mesh/istio/
https://staging.rancher.com/docs/rancher/v2.x/en/project-admin/service-mesh/
