### ISSUE TITLE
Docs for feature: "System" catalog framework to be able to upgrade system charts

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#1481]
(Support minimum_rancher_version and maximum_rancher_version in catalog)

**Comment by dramich** [comment]
https://github.com/rancher/integration-test-charts/blob/master/charts/chartmuseum/v1.6.0/questions.yml

Charts now support a field called `rancher_min_version` and `rancher_max_version` in the questions.yml file to specify the versions of Rancher that the chart is compatible with. When using the UI only app versions that are valid for the version of rancher running will be shown. API validation is done to ensure apps that don't meet the rancher requirements can not be launched. An app that is already running will not be affected on a rancher upgrade if the newer rancher version does not meet the apps requirements.
