### ISSUE TITLE
Docs for feature: Certify Rancher Server HA on EKS/AKS/GKE

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#1486]

**Comment by catherineluse** [comment]
@SheilaghM 

We already documented that you can install Rancher on EKS, AKS, GKE. We just don't document, step-by-step how to do it.

With that said, it would be nice to document a step-by-step process for deploying Rancher on these three hosted Kubernetes clusters, because it would a) advertise the fact that it is now possible in Rancher v2.5+, and b) reduce friction for those users.

The outstanding questions for documentation purposes is, how do you set up the infrastructure in these environments in a way that fulfills the Requirements for hardware, networking, etc? There are multiple right ways to do it, but the task for engineering is to figure out what these tutorials should look like for users who are possibly new to those cloud environments and don't want to make a lot of decisions.

**Comment by btat** [comment]
The current installation docs for EKS, AKS, GKE cover the step-by-step instructions already. We can open specific tutorial requests on https://github.com/rancher/rancher-docs if needed.
