### ISSUE TITLE
Review docs for Authorized Cluster Endpoint

### ISSUE THREAD

**Issue by daxmc99** [rancher/docs#1488]
Authorized cluster endpoints are a point of confusion (from a user)
```
I see this config section as available when creating a "Custom node" cluster in Rancher. How exactly does this work under-the-hood? I'm interested in configuring a custom node cluster with a load balancer in front of the kube-api server. I'm not sure how Rancher would normally load balance across multiple controlplane nodes. And if I wanted external access to the kube-api server (bypass Rancher proxy), I'd want to hit the load balancer there too. Can you explain what this config section does and if it overlaps what I'm looking to do? Lastly, I notice there is no equivalent config section in the rancher 2 Terraform provider, so it seems....?
``` 
From rancher slack https://rancher-users.slack.com/archives/C3ASABBD1/p1559754937090900

We should ensure our documentation is clear for users here 
https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#authorized-cluster-endpoint
This documentation should be written to reflect how Rancher acts as proxy and why it may be useful to enable cluster endpoint.
We have made UI changes in the past, perhaps further changes are needed? 

https://github.com/rancher/rancher/issues/20009

**Comment by shinebayar-g** [comment]
I'd like to know that, Is it necessary to have Let's Encrypt certificate on Authorized Cluster Endpoint? Can I use default self signed certificate? can it be considered safe?

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/1960
