### ISSUE TITLE
menu: collapsing a section reloads the entire page

### ISSUE THREAD

**Issue by oskapt** [rancher/docs#1500]
- when closing a menu section the entire page refreshes. this is an unnecessary interruption to the experience and forces the user to inspect whether they're still looking at the same information.
- moreover, depending on how fast the page reloads, if the user has begun to do something else like expand another menu, that activity is reset, forcing them to do it again.

**Comment by deniseschannon** [comment]
it looks fixed in the latest design changes @oskapt. if it's not to what you were thinking or seeing before, let me know.
