### ISSUE TITLE
information on custom provisioning appears twice

### ISSUE THREAD

**Issue by oskapt** [rancher/docs#1502]
We speak about custom clusters in two places: 

- under [Creating a Cluster with Custom Nodes](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/custom-nodes/)
- under [Custom Cluster](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/custom-clusters/)

Having information in two places makes it likely that someone searching for information will find only part of what they are looking for. Can these two sections be consolidated?

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/2192
