### ISSUE TITLE
duplicated information about tools

### ISSUE THREAD

**Issue by oskapt** [rancher/docs#1503]
This problem may also exist in other sections.

When clicking the top-level nav for "Configuring Tools" [a page](https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/) opens that contains information about:

- notifiers
- alerts
- logging
- monitoring

Each of these is also listed under its own page beneath that top-level nav header, but _the information in those pages is different_. For example, [this page](https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/notifiers/) covers Notifiers.

Having this information in two places means we have to update it in two places, and it increases the likelihood for confusion when users find one, then the other, or only find partial information. If we want to have a top-level page, it should link to the subpages, not duplicate the information.

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/2154
