### ISSUE TITLE
Headings say "link" instead of showing a chain icon

### ISSUE THREAD

**Issue by oskapt** [rancher/docs#1504]
<img width="760" alt="Screen Shot 2019-06-12 at 10 24 04" src="https://user-images.githubusercontent.com/171292/59359482-6a9f9000-8cfc-11e9-9d58-4c7cbd38aab9.png">

Some padding/margin and a bump in size would also make it more visible.

**Comment by vincent99** [comment]
Baunfire deleted the image font that was used so I just went with text to get the prob back.  These are mostly for us, they are not intended to be particularly visible.

**Comment by catherineluse** [comment]
could use a fontawesome icon instead of an image font

**Comment by btat** [comment]
Resolved with move to new site.
