### ISSUE TITLE
Anchor links do not seem to work in situations where they are in a "tab" within a page

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#1516]
**Summary:**
Anchor links seem to be broken when we are linking to anchors within a non-default "tab" on a page. In some cases anchor links are now missing in newer docs since the upgrade.

**Missing anchors:**
https://rancher.com/docs/rancher/v2.x/en/installation/requirements/#port-requirements
This used to work, now if I look at link for Networking tab the anchor seems to be gone. (look at bottom-left of screenshot below, link is missing anchor, I have moused over the "Networking" tab currently in this image)
![image](https://user-images.githubusercontent.com/45179589/59717491-f4ec6600-91cc-11e9-88a8-238d9176c6f0.png)

**_Result:_** Anchors are missing in situations like this where we had an anchor per tab.

----------

**Anchors not working:**
- Visit https://rancher.com/docs/rancher/v2.x/en/installation/requirements/
- Click on Networking tab
- Mouseover "Node IP Address" and you'll see "link" appear to the right, copy the link.
(Screenshot below shows me hovering over "link" we can see this anchor is there).
![image](https://user-images.githubusercontent.com/45179589/59717551-13eaf800-91cd-11e9-8a7d-eae310669080.png)
- Close the browser window/tab and try to visit the link in a new tab/window.
(Screenshot below shows that the link didn't work. We are on the default page as if no anchor was supplied)
![image](https://user-images.githubusercontent.com/45179589/59717578-2a914f00-91cd-11e9-84c8-af84816e7e22.png)

**_Result:_** Link does not take us to networking tab and scroll to "Node IP Address"

**_Additional Info:_**
Now, if you stay on this page (in your browser), click on the networking tab, and then visit the https://rancher.com/docs/rancher/v2.x/en/installation/requirements/#node-ip-address anchor link, then in this case since we are already on the "Networking" tab in the same window, then and only then the anchor link will work in this situation.

**Comment by catherineluse** [comment]
Closing this issue because the requirements have been reorganized and I believe these links work now.
