### ISSUE TITLE
Docs for how to clean up a Windows node

### ISSUE THREAD

**Issue by dnoland1** [rancher/docs#1526]
Update https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/ to include how to clean up a Windows node. I believe current procedure is to run the follow in PowerShell prompt:
```
pushd c:\etc\rancher
.\cleanup.ps1
popd
```

**Comment by deniseschannon** [comment]
@dnoland1 what is the `cleanup.ps1` script? or where does that exist? 

@loganhz can you have someone in your team submit something?

**Comment by dnoland1** [comment]
@deniseschannon I believe it's a PowerShell script that is supposed to reset an already used node so that it can added to a new Kubernetes cluster. It's located in c:\etc\rancher. See also https://gist.github.com/thxCode/ef3ed73cec5d83fce42aa13eb3bfb97b#34-clean-up

**Comment by deniseschannon** [comment]
@catherineluse can you follow up with @loganhz on what needs to be done?
