### ISSUE TITLE
Install section not showing on https://rancher.com/docs

### ISSUE THREAD

**Issue by jmcgrath207** [rancher/docs#1533]
Install section not showing on https://rancher.com/docs. Everyone other tab/ link seems to work.

Full link:
https://rancher.com/docs/os/v1.x/en/installation/

**Comment by deniseschannon** [comment]
There's actually no content on that page, but we need to re-order the navigation of Rancher OS docs to avoid these kind of pages with no content.

**Comment by catherineluse** [comment]
Closing this issue because the page has content now.
