### ISSUE TITLE
Document release branches of system-charts in Air-Gapped Instructions to "Configure Rancher System Charts"

### ISSUE THREAD

**Issue by axeal** [rancher/docs#1550]
Document the branch of system-charts specific to each minor release at https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-single-node/config-rancher-system-charts/

**Comment by deniseschannon** [comment]
v2.0.0 - v2.2.3 | `master`
v2.2.4+ | `release-v2.2`
v2.3-alpha3 - `v2.3-preview1`
v2.3-alpha5 - `v2.3-preview2`
