### ISSUE TITLE
API docs inconsistent with behavior for Create Project

### ISSUE THREAD

**Issue by jambajaar** [rancher/docs#1563]
*Rancher version:*
v2.2.4

*Description:*
The API docs indicate that for creating a new project, only the clusterId and name fields are required. If you try to POST to that endpoint with only clusterId and name fields set, you get back the following error:

StatusCodeError: 422 - {"baseType":"error","code":"MissingRequired","fieldName":"namespaceDefaultResourceQuota","message":"","status":422,"type":"error"}

**Comment by deniseschannon** [comment]
Closing in favor of https://github.com/rancher/rancher/issues/21471
