### ISSUE TITLE
Describe way to fix certificate state when it is not present

### ISSUE THREAD

**Issue by superseb** [rancher/docs#1575]
This issue https://github.com/rancher/rancher/issues/21056 was fixed by catching the NPE and presenting an error, it needs docs on how to resolve the error situation

**Comment by catherineluse** [comment]
@superseb should I take over this issue?

**Comment by superseb** [comment]
There is workaround in the mentioned issue, and the added error log has never been reported since adding it. As fixing Rancher's internal resources can be a tedious and error-prone process, I suggest to close this and see if it is ever hit again to get more info if the workaround is still valid and if not, if we can auto recover or add a way to do this automatically (for example, using Rancher CLI or some other command)
