### ISSUE TITLE
Create cluster link 404s on pod sec policy

### ISSUE THREAD

**Issue by cloudnautique** [rancher/docs#161]
On page: https://rancher.com/docs/rancher/v2.x/en/tasks/global-configuration/pod-security-policies/

The last link for creating cluster 404s

Going to: https://rancher.com/docs/rancher/v2.x/en/tasks/clusters/creating-a-cluster/_index

**Comment by MBishop17** [comment]
Fixed. 

https://rancher.com/docs/rancher/v2.x/en/tasks/global-configuration/pod-security-policies/
