### ISSUE TITLE
Add key words to air gap pages so people can find it by search without knowing what air gap means

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#1612]
In the user slack, someone asked a question about offline installation of Rancher and someone else referred her to the air gap documents.

I want to mention some key words in the air gap docs so you can find them by search if you don't know what air gap means. Key phrases would include "offline," "behind a proxy server," "behind a firewall."

**Comment by deniseschannon** [comment]
These phrases exist on most of the pages of the revised airgap docs.
