### ISSUE TITLE
Enhance pipeline docs by giving more detail and examples about image building

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#1632]
I noticed a few people on Rancher forums and Slack who were asking questions about how to pass environment variables, secrets, or other build arguments to Docker when they build images as a step of their pipeline. Here's an example:

> https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/pipelines/#build-and-publish-images (no details how to set ENV and ARG in Dockerfiles; setting env vars from UI in advanced options is not possible at all?)

Technically, the YAML tab says that you can pass stuff to Docker using env.PLUGIN_BUILD_ARGS in the YAML, but a lot of people don't get it.

I think the two-tab format in the docs works well when there's very similar information in both tabs, but in this situation, it just hides a lot of features that you can do with YAML but not in the UI. I think that for the sake of visibility, the tabs should go away and everything you can do with the YAML should have its own brief subsection and YAML example.

**Comment by soriyath** [comment]
I do agree. I am having a hard time setting my CI/CD up.
Also having real world examples would help.
Not related to this topic though, I would love to be able to run steps sequentially (it would help me write a more declarative build pipeline).

**Comment by catherineluse** [comment]
Closing because the formatting has been cleaned up, and the content won't change because we now recommend that the pipelines feature should be replaced with Rio.
