### ISSUE TITLE
Rke cluster.yaml examples have a broken link in comments

### ISSUE THREAD

**Issue by kylerome** [rancher/docs#1633]
yaml references at https://rancher.com/docs/rke/latest/en/example-yamls/ include https://github.com/rancher/types/blob/master/apis/management.cattle.io/v3/k8s_defaults.go to lookup valid kubernetes_version and system_version information, but that file appears to be gone.

**Comment by kylerome** [comment]
Realizing that the file probably only exists in the release branches? We may want to clarify that

**Comment by deniseschannon** [comment]
These are the two locations which have the file: 
```
content/rke/latest/en/example-yamls/_index.md
content/rke/latest/en/config-options/system-images/_index.md```

For RKE v0.2.x and below, the files exist at:

https://github.com/rancher/types/blob/release/v2.2/apis/management.cattle.io/v3/k8s_defaults.go

For RKE v0.3.0 and above, the files exist at:

https://github.com/rancher/kontainer-driver-metadata/blob/master/rke/k8s_defaults.go

**Comment by catherineluse** [comment]
Closing this issue because it was addressed by http://github.com/rancher/docs/pull/1739
