### ISSUE TITLE
Document required IAM permissions for EKS

### ISSUE THREAD

**Issue by janeczku** [rancher/docs#1644]
As a user I want to know what IAM permissions are required to Provision EKS clusters with Rancher, so that i can implement security principle of least privilege.

Requirement:
Document an example IAM policy with the minimal required permissions.

**Comment by marclamberti** [comment]
That should be a top priority instead of being moved to the backlog -_-

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/2498
