### ISSUE TITLE
Add Rancher cluster RKE upgrade to Rancher 2.x HA upgrade docs

### ISSUE THREAD

**Issue by axeal** [rancher/docs#1650]
Whilst the Rancher 2.x HA installation instructions include details on installation of the Kubernetes cluster for the Rancher server cluster, via RKE, the upgrade docs do not include upgrading the cluster via RKE. Would be helpful if these included at least a link to the relevant RKE documentation.

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/1851 was merged
