### ISSUE TITLE
Update the etcd restoration process in RKE docs

### ISSUE THREAD

**Issue by galal-hussein** [rancher/docs#1651]
The etcd snapshot restore was optimized in 0.2.x, to get rid off the extra steps for the restoration, the rke restoration currently does the following:
```
1- rke remove to clean old data
2- sync the snapshot (or download from s3)
3- restores the snapshot and starts etcd
4- triggers rke up
```
The docs need to explain the difference in details.

**Comment by catherineluse** [comment]
Hi Galal, I have a couple of questions, just to clarify - 

1. Which steps are no longer necessary? Cleaning the nodes?
2. Which commands are required in 0.2.x?
