### ISSUE TITLE
Update Rancher docs for new Resources menu

### ISSUE THREAD

**Issue by tfiduccia** [rancher/docs#1655]
In : 2.3

The project level main menu has changed in 2.3.  We added Resources menu that contains:
Workloads
HPA
Pipeline
Secrets
Config

![image](https://user-images.githubusercontent.com/11514927/62726220-94f38e00-b9cb-11e9-9782-8bd58fff7bb4.png)

Workloads now only contain: Workloads, Load Balancing, Service Discovery & Volumes
![image](https://user-images.githubusercontent.com/11514927/62726240-a76dc780-b9cb-11e9-9fce-84c1edb2ca4f.png)

Secrets now contain: Secrets, Certificates, Registry Credentials
![image](https://user-images.githubusercontent.com/11514927/62726267-bc4a5b00-b9cb-11e9-91b9-4ba48f31fb53.png)

**Comment by deniseschannon** [comment]
`From the main navigation bar, choose **Resources**. In versions prior to v2.3.0, choose **Workloads** on the main navigation bar.`
