### ISSUE TITLE
[rio] Add Rio docs

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#1657]
Let's start with an initial outline, then need initial tutorial/quick start (A/B scenario, other use cases, etc) then detail concepts, etc.

- [ ] Sheng pull rancher/docs - start outline by creating a new page for Rio or provide an outline in some format for engineer to get started with.
- [ ] Engineer does first pass and enters technical details to cover quick start / getting started, A/B scenario, and any other simple use cases.
- [ ] Tani reviews the first pass the Engineer created
- [ ] Catherine reviews areas as defined in rancher/docs

**Comment by davidnuzik** [comment]
Note: There is some internal discussion of possibly not hosting Rio docs on the rancher.com docs website. It's possible we might look for another solution.

**Comment by davidnuzik** [comment]
Update: There is a possibility we won't have Rio docs at all on the rancher.com website in the near future. The improved README on GitHub may be sufficient for now.

**Comment by btat** [comment]
As per https://github.com/rancher/rio/commit/b4cd8032227905b855ef167e1e008610beece166, the Rio project is on hold. Add docs will not be required.
