### ISSUE TITLE
Statement on testing Rancher on Kubernetes seems inaccurate

### ISSUE THREAD

**Issue by dnoland1** [rancher/docs#1672]
On https://rancher.com/docs/rancher/v2.x/en/cluster-admin/editing-clusters/#upgrading-kubernetes it states: "Before a new version of Rancher is released, it’s tested with the latest versions of Kubernetes to ensure compatibility."

However, Rancher 2.2.6 was released on July 23rd and supported up to Kubernetes 1.15.0. Latest version of Kubernetes at that time was v1.15.1.

Semantically, it's also vague what "latest versions" mean. There's really only one latest version. However, you could claim "latest versions" means the latest version of each 1.x line (example, 1.14.9, 1.15.2)

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/1860 was merged
