### ISSUE TITLE
Site Access Info is missing in Docs

### ISSUE THREAD

**Issue by deniseschannon** [rancher/docs#1683]
After external auth providers are authenticated, they need to specify what site access level they want. It's missing in the auth docs. 

<img width="1258" alt="Screen Shot 2019-08-21 at 9 37 44 AM" src="https://user-images.githubusercontent.com/11410997/63450715-6f1caf00-c3f7-11e9-8167-51b2ca31156a.png">

**Comment by deniseschannon** [comment]
Here is what was documented in 1.x series, but we need to confirm what the levels are for 2.x: 

https://rancher.com/docs/rancher/v1.6/en/configuration/access-control/#site-access

**Comment by catherineluse** [comment]
Closing the issue because it was addressed by https://github.com/rancher/docs/pull/1716
