### ISSUE TITLE
Document the behavior of adding etcd nodes while member of current cluster is unhealthy

### ISSUE THREAD

**Issue by galal-hussein** [rancher/docs#1687]
etcd prevents adding a new etcd members when one or more etcd nodes in the current cluster is unhealthy, this behavior can be overriden by passing  --strict-reconfig-check=false to etcd, but this can cause etcd to enter a quorum loss situation and breaks the cluster, we should document that when one or more etcd is down, user should either fix the broken node or remove it before adding new ones.

related issue: https://github.com/rancher/rancher/issues/20956

**Comment by catherineluse** [comment]
Closing this issue because this PR was merged https://github.com/rancher/docs/pull/1849
