### ISSUE TITLE
Anchor links lead to sections hidden by Rancher banner

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#1689]
I've noticed that if I navigate to an anchor link, when the page loads the Rancher banner hides the beginning of the article I'm loading. 

Running Firefox snap on Xubuntu 18.04

**This link:**
https://rancher.com/docs/rancher/v2.x/en/v1.6-migration/monitor-apps/#rancher-v2-x-health-checks

**Leads to:**
![image](https://user-images.githubusercontent.com/8906089/63594758-3d4e4880-c5af-11e9-8918-7addcffb3ca4.png)

**Expected behavior:** 
![image](https://user-images.githubusercontent.com/8906089/63594884-8a321f00-c5af-11e9-8a8f-ea03987dcca1.png)

**Comment by catherineluse** [comment]
Please raise the issue in the rancherlabs/website repo (that's where the theme is)

**Comment by Tejeev** [comment]
@catherineluse I opened: https://github.com/rancherlabs/website-theme/issues/140
If that's the correct location please close this ticket (thanks! :) )
