### ISSUE TITLE
monitor-apps doc missing diagrams

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#1690]
**Page:** 
https://rancher.com/docs/rancher/v2.x/en/v1.6-migration/monitor-apps/

**Issue:**
There are two times the doc references diagrams that I do not see on the page.
Search "The following diagram displays" on the page.
![image](https://user-images.githubusercontent.com/8906089/63595250-5b687880-c5b0-11e9-92c1-7ffd689acb39.png)

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/1880 was merged
