### ISSUE TITLE
Recommend releases in install docs

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#1697]
It would help to recommend versions for different packages in the install docs.  Maybe we can pull in latest stable release from GH with some sort of actively generated link?

**Comment by catherineluse** [comment]
What do you mean, different packages? We already tell people to use the `stable` server tag to get the latest stable release.

**Comment by Tejeev** [comment]
I think the stuff this pertained to is long gone and going by tag is so much better than what I think was there when I opened the ticket.  Closing.
