### ISSUE TITLE
Focused reader mode or collapsible left menu

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#1698]
A focused reading mode would be nice to have.  Perhaps just the option to collapse the TOC menu on the left hand side?  Preferably be able to switch to the mobile reader view where the text spans the page and the menu at left collapses by choice at any resolution?

Currently I only see text on just less than half of the window and have large amounts of whitespace on either side. If I make the window smaller to accommodate the 'fixed' column width, the column gets thinner to accommodate the menu bar until finally it auto collapses at some point. 

It would be preferable to just have the option to resize at will since monitor resolutions and prefered text sizes vary so greatly.

**Comment by btat** [comment]
May not be applicable now that we've moved to a new site/framework.
