### ISSUE TITLE
Should Prerquisits for upgrade not be steps?

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#1701]
Since these 'prereqs' should be run each time they upgrade, should we not make them just the first steps of the upgrade?  I see this section on most of the upgrade pages.

To clarify for someone and make sure they didn't skip any of the prerequisites since they only seemed to catch the commands that are listed in the article, I rewrote the prerequisites as steps in the upgrade process before sending them the link to the upgrade instructions.

**Comment by deniseschannon** [comment]
Revised upgrade docs have updated this. This will be made available when v2.3 ships.
