### ISSUE TITLE
Changed Select Cluster Type to include "RKE" in verbiage

### ISSUE THREAD

**Issue by tfiduccia** [rancher/docs#1708]
In Add Cluster - Select Cluster Type:
- [ ] Changed text in "From existing nodes (Custom)" to include RKE verbiage
- [ ] Changed text in "infrastructure provider" to include RKE verbiage.

![image](https://user-images.githubusercontent.com/11514927/64194087-202d3b80-ce33-11e9-9666-f1a51473fb5e.png)

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/1734
