### ISSUE TITLE
Enhance Rancher upgrade instructions

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#1710]
Some Rancher users have questions about upgrades, which led to this list of requested enhancements for the Rancher upgrade docs:

- Rancher version compatibility matrix
- List of Rancher versions that should be skipped or [Recommend releases in install docs #1697](https://github.com/rancher/docs/issues/1697).  I believe the later the best option.
- Clearly stated preferred order of operations for a full cloud upgrade addressing the most common deployment architectures. https://github.com/rancher/docs/issues/1650
- Simplified architecture diagrams as an easy way for people to recognize which path matches their deployment rather than asking if they need to upgrade those components.  The Installation Options page might also benefit from these.  This will allow users to easily understand and match their architectures
- Explanation of why the rkestate file is important, depending on your RKE version
- If you don’t have a statefile, explain how to generate a new one from the current state
- Links to installation docs on cluster yamls https://rancher.com/docs/rancher/v2.x/en/installation/ha/kubernetes-rke/ where they are relevant to upgrading Rancher and from the install pages here.  So people know why they are important.  They still aren't saving them despite the note.  Maybe a section on how they can manage their statefiles, yamls, etc with a repo and just push each time they make changes to the cluster and configs?

**Comment by catherineluse** [comment]
Related issue https://github.com/rancher/docs/issues/1915

**Comment by catherineluse** [comment]
About the Rancher version compatibility matrix - Denise said any Rancher 2.x version should be able to upgrade to any newer version.

I think part of the issue is that RKE v0.2.0 changed how clusters are backed up by introducing the `rkestate` file. I think when https://github.com/rancher/docs/issues/1915 is addressed it might clear things up.

**Comment by catherineluse** [comment]
@Tejeev The upgrade docs have been updated since this issue was created. Can you please review it to see how much is still applicable?

**Comment by btat** [comment]
Closing due to no response.
