### ISSUE TITLE
Access to rancher-images.txt is on the About pop-up instead of in Driver page

### ISSUE THREAD

**Issue by tfiduccia** [rancher/docs#1725]
For Airgap installation we are providing a image list for linux and window's based machines.  The access to those files are now in the About popup instead of on the Machine driver page.

So moved this drop-down
![image](https://user-images.githubusercontent.com/11514927/64367692-877ef300-cfcd-11e9-88b7-d441f62d7084.png)

to this:
![image](https://user-images.githubusercontent.com/11514927/64367391-b9438a00-cfcc-11e9-80c1-cd36280a4143.png)

**Comment by deniseschannon** [comment]
We only need to add this information into the k8s metadata sections for airgap users. 

1. This is only needed for air-gap users that are introducing new k8s versions into Rancher.
2. After introducing a new k8s version into Rancher, you'd need use this images list from the about page to populate your private registry. (Refer to air gap docs on how to populate the private registry)
