### ISSUE TITLE
Move Project Alerts to under alerting for projects

### ISSUE THREAD

**Issue by deniseschannon** [rancher/docs#1726]
https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/alerts/default-alerts/

In that page, we have cluster alerts and project alerts, but since this is under the "cluster adminitration", the project alert part is getting lost. 

we should move it to be nested under project administration for alerts:

https://rancher.com/docs/rancher/v2.x/en/project-admin/tools/alerts/

**Comment by catherineluse** [comment]
Closing this issue because this PR was merged https://github.com/rancher/docs/pull/1853
