### ISSUE TITLE
Edit as YAML for cluster creation changed

### ISSUE THREAD

**Issue by deniseschannon** [rancher/docs#1736]
In 2.3, the `edit as yaml` requires the RKE yaml items to be under the `rancher_kubernetes_engine_config:` directive. So previous yamls from other clusters will need to be updated for this format.

**Comment by deniseschannon** [comment]
Needs to be updated specifically here: https://staging.rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#config-file

Also, update the summary of how a config file is used:https://staging.rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/

**Comment by catherineluse** [comment]
Closing this issue because this PR was merged https://github.com/rancher/docs/pull/1829

**Comment by dnoland1** [comment]
This also needs to be fixed in places like here - https://rancher.com/docs/rke/latest/en/config-options/cloud-providers/vsphere/

**Comment by catherineluse** [comment]
I'm reopening this issue so that we can fix other places where people are getting tripped up by the change

**Comment by catherineluse** [comment]
@dnoland1 Vince said documents in the RKE section should not mention Rancher at all. I think that document that you linked might need to be updated to remove the existing reference to Rancher.

**Comment by dnoland1** [comment]
@catherineluse That's fine, but would still need a place to instruct users on how to configure vSphere cloud provider in Rancher.

**Comment by catherineluse** [comment]
@dnoland1 In this other PR https://github.com/rancher/docs/pull/2016 I have reorganized the docs on how to configure vSphere cloud provider in Rancher, partly by moving some Rancher configuration info in the RKE docs back over to the Rancher docs. Hopefully that will make things clearer.

**Comment by dnoland1** [comment]
Thanks @catherineluse. I did a quick pass through on the PR and looks fine.

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by these PRs: https://github.com/rancher/docs/pull/1921 and https://github.com/rancher/docs/pull/2016
