### ISSUE TITLE
Instruction for adding images for both Windows and Linux to the private registry

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/docs#1742]
The current documentation covers only how to prepare the private registry for Linux environment.  https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-single-node/prepare-private-registry/

We need instructions for adding images that would work on both Windows and Linux nodes to the private registry.

**Comment by loganhz** [comment]
# Air Gap Instructions

## Windows Part

### Step 1: Save Images

* Create a Windows 1903 Server which has internet connection and has at least 50 GB
* Download `rancher-windows-images.txt` and `rancher-save-images.ps1` in Rancher release page
* Copy the 2 files to the Windows Server and put them into the same directory.
* Run `powershell` in cmd
* cd to the directory
* Run `.\rancher-save-images.ps1` to pull and save the Windows requried images
* Wait for the previous step finished. It takes time.
* You will see a `rancher-windows-images.tar.gz` in the directory.

### Step 2: Load Images and Push Images to Private Registry

* Go to a Windows 1903 Server which can connect to your private registry.
* Download `rancher-windows-images.txt` and `rancher-load-images.ps1` in Rancher release page.
* Move the `rancher-windows-images.tar.gz` to the server.
* Put `rancher-windows-images.tar.gz`, `rancher-windows-images.txt` and `rancher-load-images.ps1` in the same directory.
* Run `powershell` in cmd
* cd to the directory
* Run `docker login <REGISTRY.YOURDOMAIN.COM:PORT>` to login your private reigstry
* Run `.\rancher-load-images.ps1 --registry <REGISTRY.YOURDOMAIN.COM:PORT>`
* Wait until previous step finished

## Linux Part

### Step 1: Save Images

* You have to finish the Windows Part first if you want to create Windows cluster in your air gap environment.
* Create a Linux host which has internet connection.
* Download `rancher-images.txt` and `rancher-save-images.sh` in Rancher release page
* Copy the 2 files to the linux host and put them into the same directory.
* Run `chmod +x rancher-save-images.sh` to make it executable
* Run `./rancher-save-images.sh` to pull and save the Windows requried images
* Wait for the previous step finished. It takes time.
* You will see a `rancher-images.tar.gz` in the directory.

### Step 2: Load Images and Push Images to Private Registry

* Go to a Linux host which can connect to your private registry.
* Download `rancher-images.txt`, `rancher-windows-images.txt` and `rancher-load-images.sh` in Rancher release page.
* Move the `rancher-images.tar.gz` to the server.
* Put `rancher-images.tar.gz`, `rancher-images.txt`, `rancher-windows-images.txt` and `rancher-images.sh` in the same directory.
* Run `chmod +x rancher-load-images.sh` to make it executable
* Run `docker login <REGISTRY.YOURDOMAIN.COM:PORT>` to login your private reigstry
* Run `./rancher-load-images.sh --windows-image-list ./rancher-windows-images.txt --registry <REGISTRY.YOURDOMAIN.COM:PORT>`
* Wait until previous step finished
* All done

**Comment by jiaqiluo** [comment]
For this command under `Linux Part -> Step 2: Load Images and Push Images to Private Registry`
```
Run ./rancher-load-images.sh --windows-image-list ./rancher-windows-images.txt --registry <REGISTRY.YOURDOMAIN.COM:PORT>
```
it returns errors like this
```
v1.15.3-rancher3-linux-amd64: digest: sha256:53d0fa2aee12457a5db8cc649a9f09ed1dd39c7bb7bf98a5684b7cbc39845272 size: 2211
Preparing manifest ec2-13-56-165-173.us-west-1.compute.amazonaws.com:443/rancher/hyperkube:v1.15.3-rancher3, list[windows-1903 linux-amd64]
open /etc/docker/certs.d/ec2-13-56-165-173.us-west-1.compute.amazonaws.com:443: permission denied
No such manifest: ec2-13-56-165-173.us-west-1.compute.amazonaws.com:443/rancher/hyperkube:v1.15.3-rancher3
```

The workaround is to run the command in `sudo` mode
```
sudo bash ./rancher-load-images.sh --windows-image-list ./rancher-windows-images.txt --registry <REGISTRY.YOURDOMAIN.COM:PORT>
```

cc @loganhz

**Comment by gitlawr** [comment]
Also, add `--image-list ./rancher-images.txt` to the `rancher-load-images.sh` command. It needs both image files when publishing Linux & Windows images. The flag defaults to "rancher-images.txt" but we should expose it in case users put the image files in a different path.

**Comment by gitlawr** [comment]
The manifest subcommand required for mirroring windows images is added in 18.02.0+(https://github.com/docker/cli/pull/138) docker cli. We should mention it as a prerequisite for windows images preparation.

**Comment by jiaqiluo** [comment]
We need to run the `./rancher-load-images.sh` script in `sudo` mode, otherwise it will throw errors like this
```
Preparing manifest ec2-54-215-219-6.us-west-1.compute.amazonaws.com:443/rancher/hyperkube:v1.14.7-rancher1, list[windows-1903 linux-amd64]
open /etc/docker/certs.d/ec2-54-215-219-6.us-west-1.compute.amazonaws.com:443: permission denied
No such manifest: ec2-54-215-219-6.us-west-1.compute.amazonaws.com:443/rancher/hyperkube:v1.14.7-rancher1
The push refers to repository [ec2-54-215-219-6.us-west-1.compute.amazonaws.com:443/rancher/hyperkube]
2ece688092fc: Pushed
193a8e91bc9b: Pushed
39b3ac6d96e9: Layer already exists
7bbae4dddb88: Layer already exists
a00defcfe869: Layer already exists
2ab0ae805c74: Layer already exists
43a8fe7d2382: Layer already exists
3f6a6f542637: Layer already exists
5ba3be777c2d: Layer already exists
```
