### ISSUE TITLE
Fix incorrect description of private registry cluster option

### ISSUE THREAD

**Issue by janeczku** [rancher/docs#1748]
On [this page ](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/#private-registries) private registries cluster option is described as follows:

> If you are using a private registry with authentication for your Docker images, please configure the registry in this section to allow the nodes to pull images from this registry. See Private Registries for more information.

This could be interpreted by users such that the credentials configured here are going to be used when pulling images for user deployed workloads - which is not the case.

The documentation needs to clarify that the registry configuration here is exclusively applied to the pulling of [system](https://rancher.com/docs/rke/latest/en/config-options/system-images/) or [addon](https://rancher.com/docs/rke/latest/en/config-options/add-ons/) images during the provisioning of the cluster.

**Comment by deniseschannon** [comment]
We need to reference that the private registry used during cluster provisioning is *only* used for the components to maintain the Kubernetes cluster.

Users would need to set up their own registry (https://staging.rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/registries/) to be able to pull images from that within their projects to deploy workloads.

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/1843 was merged
