### ISSUE TITLE
Revise the steps to retrieve rancher system images for airgap setups 

### ISSUE THREAD

**Issue by alena1108** [rancher/docs#1758]
@mrajashree we have to revise the steps for Rancher and RKE cli for system images retrieval and publishing them to the private repos in the airgap setups

https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-high-availability/prepare-private-registry/

**Comment by deniseschannon** [comment]
@alena1108 @mrajashree What version did we drop needing this step? We can't just remove it in case older versions need it.
