### ISSUE TITLE
Authorized Cluster Endpoint docs need clarification

### ISSUE THREAD

**Issue by aemneina** [rancher/docs#1764]
Currently our docs say `all Rancher Launched Kubernetes clusters have Authorized Cluster Endpoint`. Whats not clear is if someone launches an EKS cluster from rancher, that's not going to work. This feature only works with rke based clusters. We need better words to express this more clearly.

https://rancher.com/docs/rancher/v2.x/en/cluster-admin/kubeconfig/#accessing-rancher-launched-kubernetes-clusters-without-rancher-server-running

**Comment by superseb** [comment]
The link of Rancher Launched Kubernetes links to https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/ where it is explained what Rancher Launched Kubernetes means. EKS is part of the Hosted Kubernetes Providers which is documented at https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/.

We can add a table where to make clear where ACE can be used if it needs to be more explicitly mentioned.

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/1960
