### ISSUE TITLE
add minimum node requirements for windows

### ISSUE THREAD

**Issue by oskapt** [rancher/docs#1767]
I launched a windows node with the defaults, for testing, and when installing the agent received the following alert:

```
WARN: The DISK resource only satisfy the lowest limit of running Kubernetes components
WARN: Please increase the DISK resource to more than 50 GB if could not schedual Pods in this Node
```

Not sure where this should go in the docs, but I couldn't find anywhere that has it called out right now. Maybe in the windows install walkthrough as a Notice or Warn?

I already fixed the spelling mistakes and issued a PR in the other repo.

**Comment by deniseschannon** [comment]
This is a broader concern that we don't have node/port requirements for user clusters.

**Comment by superseb** [comment]
@catherineluse Can we add the requirement for `Docker Enterprise Edition (EE)` as well please? See https://forums.rancher.com/t/rancher-2-3-0-3-nodes-are-available-3-node-s-had-taints-that-the-pod-didnt-tolerate/15480/2

Checked with Logan and Docker CE was tested and didn't work. Also see https://kubernetes.io/docs/setup/production-environment/windows/intro-windows-in-kubernetes/#container-runtime

**Comment by catherineluse** [comment]
Closing this issue because this PR was merged https://github.com/rancher/docs/pull/1836
