### ISSUE TITLE
[k3s] Docs page to explain what Telemetry is captured and how to opt out

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#1778]
Reference: https://github.com/rancher/k3s/issues/834

We need to clearly state what exactly is being captured, how to opt-out, and explain the anonymity.
We use telemetry for the purposes of improving our projects; we want to be clear in our documentation that you can opt-out and what exactly we capture.

**Comment by catherineluse** [comment]
It sounds like the material on this page could be used as a reference. https://rancher.com/docs/rancher/v2.x/en/faq/telemetry/

**Comment by davidnuzik** [comment]
FYI: For now we are holding off on adding telemetry to k3s.

**Comment by ibuildthecloud** [comment]
Closing as we are not going forward with telemetry 834
