### ISSUE TITLE
Improve Secrets Doc = How to set a Secret for Docker Private Registry in Rancher UI

### ISSUE THREAD

**Issue by ichtestemalwieder** [rancher/docs#1788]
Hello, 

setting Registry Credentials via Secrets is one of the most often used fundamental concepts and requirements by kubernetes. Rancher UI does not adhere to these standard concepts, which makes Rancher more complex to understand.

1.) Suggestion Improving the Doc: 
The Secrets Documentation (https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/secrets/) should point this out in a "Warning Box", that Secrets for Registries are not configurable from this Secret Screen but have their own Concept / UI Screen/Menu Item. 

2.) Suggestion Improving the UI/UX in general 
Slightly redisigning of the "Secrets" screen to make it more consistent with kubernetes itself, by 
a) showing all types of Secrets, as stored in kubernetes. Currently Rancher does filter out Registry Secrets when listing all secrets. 
b) Allowing to also create Registry Secrets from the Secrets screen (by introduction a type fileld that allows to specify that it is of type Registry Secret).

Thanks!

**Comment by vincent99** [comment]
That would be the next section... https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/registries/

**Comment by ichtestemalwieder** [comment]
@vincent99, thanks very much!! just realized this on my own, after 2 hours of searching. But this is completely unintuitive, if not better explained.

**Comment by catherineluse** [comment]
The UI for secrets was improved in Rancher v2.3 in much the same way as described. We now have:

> From the main menu, click Resources > Secrets > Registry Credentials. (For Rancher prior to v2.3, click Resources > Registries.)

**Comment by catherineluse** [comment]
Closing this issue because I have linked to the private registry page from the secret page to make it more discoverable https://github.com/rancher/docs/pull/2151
