### ISSUE TITLE
Rancher single server certificate clarification

### ISSUE THREAD

**Issue by patrick0057** [rancher/docs#1801]
In our docs on https://rancher.com/docs/rancher/v2.x/en/installation/single-node/ under "OPTION C-BRING YOUR OWN CERTIFICATE: SIGNED BY RECOGNIZED CA", I think this section could use a bit of clarification.  

When I see this, I immediately think that we're just using the certificate and the key.  The only part that tells me otherwise is the parameter "FULL CHAIN.pem".  I think it would be helpful to state something in the instructions along the lines of, your tls.crt must contain your full chain which is your certificate, root certificate and and intermediate certificate(s) if you have one.

**Comment by superseb** [comment]
Root certificate should never be in the chain, that should be on the other end. And in case of Recognized CA, the root should already be known. I added the same line for self signed regarding intermediates on the recognized CA section.
