### ISSUE TITLE
Unable to see underscores in one-line monotype

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#1816]
I can barely tell there are underscores in one-line monotype on the docs site. We should fix the docs page styling.

Example:
https://rancher.com/docs/rancher/v2.x/en/installation/single-node/
![image](https://user-images.githubusercontent.com/45179589/66333491-f3fe5200-e8eb-11e9-8485-247793c6f74e.png)
![image](https://user-images.githubusercontent.com/45179589/66333505-fa8cc980-e8eb-11e9-88ec-67a510d832a7.png)

It's as if I only see 1/2 a px or to be more specific like 1 px with 50% opacity for the underscore. Total height of the background for single-line monotype probably needs to be increased slightly.

Other examples:
https://rancher.com/docs/k3s/latest/en/installation/ (this one has lots of use of underscores and is pretty bad)
https://rancher.com/docs/k3s/latest/en/running/

Reproduced issue on:
Linux - Chromium and Firefox
Windows 10 - Chrome and Firefox (It's a little easier to see on Firefox on Windows but not perfect)

**Comment by lvuch** [comment]
resolved here https://github.com/rancherlabs/website-theme/pull/114/

**Comment by davidnuzik** [comment]
@davidnuzik reminder to self to test this tomorrow

**Comment by davidnuzik** [comment]
This is confirmed resolved on the live docs site:
![image](https://user-images.githubusercontent.com/45179589/66500825-11135c00-ea77-11e9-8996-4ad9ccc30e75.png)
Notice it's much easier to see the underscores now.
