### ISSUE TITLE
[Rancher FAQ] Poor formatting and may need updates

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#1818]
The Rancher FAQ parent page https://rancher.com/docs/rancher/v2.x/en/faq/ uses headings to separate out sections i.e. Cattle, Environments & Clusters, etc.

The problem is they are the same size headings and so it's hard to read. The questions should not be using such large headings (should be smaller or just bold text or something).

Additionally, is someone combing through FAQ's each release? We should review and see if this page needs any updates.

**Comment by davidnuzik** [comment]
It looks like you can boldify headings i.e.:
```
# **Example bold heading**
```

So, perhaps that can be done to separate out the questions. This avoids having to reformat child pages as well that utilize the heading to ask questions.

**Comment by davidnuzik** [comment]
The problem seems to be that there doesn't seem to be a diff between level 3 heading and level 4 heading. Might also be solved by just making sections larger heading like just one # for example instead of three.

**Comment by deniseschannon** [comment]
@davidnuzik there are plans to do a design discussion of the docs site in general and i believe things like the fact that H3 and H4 are the same will be added as well.

**Comment by catherineluse** [comment]
In this PR https://github.com/rancher/docs/pull/1901 the formatting was addressed. 

Some items were updated in that PR but I made another issue specifically for reviewing the all of the items: https://github.com/rancher/docs/issues/1913
