### ISSUE TITLE
Feature flag/experimental features configuration can be described more clear

### ISSUE THREAD

**Issue by superseb** [rancher/docs#1826]
On https://rancher.com/docs/rancher/v2.x/en/admin-settings/feature-flags/ we describe the features and the parameter to enable it in the column `ENVIRONMENT VARIABLE KEY`. While in the actual example command, it is referenced as `'extraEnv[0].value=<FEATURE-NAME1>=true`.

Environment variable key can also be interpreted as the actual environment variable, while the actual key is `CATTLE_FEATURES` with its value having `key=value` pairs.

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/1859 was merged
