### ISSUE TITLE
Airgap system charts link

### ISSUE THREAD

**Issue by patrick0057** [rancher/docs#1831]
It would be useful to have a link in the airgapped docs (https://rancher.com/docs/rancher/v2.x/en/installation/air-gap/) to this page about system charts in an airgapped installation.
https://rancher.com/docs/rancher/v2.x/en/installation/options/local-system-charts/

**Comment by deniseschannon** [comment]
@patrick0057 As of v2.3.0, you don't need to mirror the system charts as you can package it in. In the detailed docs of when to install rancher, it talks about this new option and if you were doing another version, it directs you to those instructions: 

https://rancher.com/docs/rancher/v2.x/en/installation/air-gap/install-rancher/
Step E.
