### ISSUE TITLE
"Glossary" of settings, environment variables, rancher startup arguments, and feature flags

### ISSUE THREAD

**Issue by cjellick** [rancher/docs#1834]
We have a lot of undocumented knobs you can tweak for rancher. Many of these are basically one-offs to address some specific problem that a user hit.
 Generally, I don't want these to be in the "main" installation documentation because they would just clutter and confuse a normal user, but I'd like to have some place where we could just quickly and easily enumerate overall of these and briefly explain them. This would empower users to solve some of their own problems.

**Comment by catherineluse** [comment]
Are you thinking of something like the 'chart options' page, but also applicable to single node installs? https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/chart-options/

**Comment by catherineluse** [comment]
Closing this issue because it seems to be covered by chart options. https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/chart-options/ We can reopen if there is something specific that needs to be added to that page, or to the page about enabling experimental features.
