### ISSUE TITLE
Document enabling forward host headers for NGINX 0.25.0 in Rancher Launched Kubernetes clusters in v2.3.0 and higher

### ISSUE THREAD

**Issue by superseb** [rancher/docs#1835]
See https://github.com/rancher/rancher/issues/23341#issuecomment-540601760

Document the required change in https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/chart-options/#external-tls-termination

**Comment by alena1108** [comment]
@sangeethah can someone from qa validate and confirm the workaround steps? So we can follow up documenting them.

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/1939 was merged
