### ISSUE TITLE
Terraform examples to show people how to set up "best practices" infrastructure, how to use Rancher Terraform provider

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#1838]
I think we should include Terraform files that would basically show examples of how you could set up infrastructure that matches what is recommended in the best practices guide.

We could put this in the best practices guide and show different examples for different major cloud providers.

This could help people troubleshoot problems, especially if they use Terraform, because then they could figure out what might be wrong by comparing their Terraform vs. Rancher's examples.

It would be good to also include illustrative examples of how to use the Rancher Terraform provider.

**Comment by dnoland1** [comment]
Might be able to leverage some of the Terraform developed for quickstart - https://github.com/rancher/quickstart

**Comment by catherineluse** [comment]
relevant links:
https://github.com/rancher/onboarding-content/tree/master/phase_I/automate_ha_deployment
https://github.com/rancher/quickstart/pull/54
