### ISSUE TITLE
Rancher Architecture doesn't mention cattle-node-agent, cattle-cluster-agent, and kube-api-auth

### ISSUE THREAD

**Issue by dnoland1** [rancher/docs#1850]
On the Rancher architecture page, at https://rancher.com/docs/rancher/v2.x/en/overview/architecture/ cattle-node-agent, cattle-cluster-agent, and kube-api-auth are not mentioned. These workloads are deployed in the RKE created downstream clusters. They should be shown in the architecture diagram and should be explained as to what they do.

**Comment by superseb** [comment]
For the agents, it is explained on https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rancher-agents/. kube-api-auth is under https://rancher.com/docs/rancher/v2.x/en/cluster-admin/kubeconfig/#kube-api-auth

**Comment by dnoland1** [comment]
Thanks @superseb. I'm still thinking it might be nice to show those components on the architecture diagram, maybe with links going to the URLs mentioned above.

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/1960
