### ISSUE TITLE
CSS Super Fun Happy Time

### ISSUE THREAD

**Issue by MBishop17** [rancher/docs#190]
Lauren, can you please tweak a few things that bug my inner pedant?

1. `<pre>` blocks inside of list items have larger font than stand-alone `<pre>` blocks. Can we use the smaller font for both?

- li (bigger)
      
    ![image](https://user-images.githubusercontent.com/37810556/40756287-7e6576f2-6437-11e8-938f-3bafe2d4a5bf.png)

- stand-alone (smaller)

    ![image](https://user-images.githubusercontent.com/37810556/40756299-92b4fde4-6437-11e8-8f85-f98a27a69a0c.png)

2. For `<ul>` list items, can we change the list style to `list-style-position: outside;`? Text under the bullet looks weird.

![image](https://user-images.githubusercontent.com/37810556/40756314-ab089c34-6437-11e8-8869-e7d7f0bb97d3.png)

3. Also, can we change the first-tier `<ul>` list item indentation to match  `<ol>`'s? Again, looks kinda weird, especially when next to numbered lists.

![image](https://user-images.githubusercontent.com/37810556/40756332-d602b7bc-6437-11e8-9963-be399c3ea675.png)

**Comment by lvuch** [comment]
fixed and pushed to theme
