### ISSUE TITLE
OKTA SAML poorly implemented

### ISSUE THREAD

**Issue by mcmiv413** [rancher/docs#1907]
https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/okta/

"When adding groups, you must select the group from the drop-down that is next to the text box. Rancher assumes that any input from the text box is a user.

The group drop-down shows only the groups that you are a member of. You will not be able to add groups that you are not a member of."

This is very poorly designed, other apps that integrate with okta do not have this behavior and if the group is selected incorrectly there is nothing that indicates it was added "wrong" or that it won't work. How is this documented as a feature instead of being properly treated as a bug in the design?

**Comment by catherineluse** [comment]
That note in a section called "SAML Provider Caveats." To me, "caveats" already indicates a limitation of some kind. Maybe you could raise an issue on rancher/rancher?
