### ISSUE TITLE
Certificate rotation will not restart ETCD container

### ISSUE THREAD

**Issue by nickngch** [rancher/docs#1908]
https://rancher.com/docs/rancher/v2.x/en/cluster-admin/certificate-rotation/
The document indicated that the Kubernetes components are automatically restarted after the certificates are rotated.

Tried certificate rotation from UI on Rancher v2.1.13 and v2.3.1, the etcd container will not restart after certificate rotation.

**Comment by btat** [comment]
Docs version no longer maintained.
