### ISSUE TITLE
Node Requirements needs updating for 2.3

### ISSUE THREAD

**Issue by superseb** [rancher/docs#1912]
https://rancher.com/docs/rancher/v2.x/en/installation/requirements/

* OS and Docker versions need to be updated (RHEL 7.6 -> RHEL 7.7 and add Docker 19.03.x where Docker 18.09.x)
* List consists of OS and Docker on the same indentation, this needs to be combined on a single line or second line indented, or a table, something that coupes OS and Docker version(s)
* RancherOS -> v1.5.4, section for switching Docker version can be removed as the default is supported.

**Comment by superseb** [comment]
This was not completely addressed by the PR, RHEL 7.7 is not listed and Docker 19.03 was not added to the supported OS's.

**Comment by catherineluse** [comment]
@superseb Does the table about operating system requirements need any more changes for 2.3? https://rancher.com/docs/rancher/v2.x/en/installation/requirements/#operating-systems-and-docker-requirements

**Comment by catherineluse** [comment]
Closing this issue because we're actually removing the specific OS versions and Docker versions from the installation docs.
