### ISSUE TITLE
Review restore/backup information on Rancher docs to sync with RKE docs

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#1915]
These pages should be in sync with each other:

- https://rancher.com/docs/rancher/v2.x/en/backups/restorations/ha-restoration/
- https://rancher.com/docs/rke/latest/en/etcd-snapshots/restoring-from-backup/

**Comment by btat** [comment]
No longer applicable. Cannot find current page that corresponds to first link that is referenced.
