### ISSUE TITLE
Broken link to helm documentation

### ISSUE THREAD

**Issue by patrick0057** [rancher/docs#1955]
At the following URL:
https://rancher.com/docs/rancher/v2.x/en/catalog/#launching-catalog-applications

"Using Helm: The format and limitations of –set" points to a broken link: https://github.com/helm/helm/blob/master/docs/using_helm.md#the-format-and-limitations-of---set

Working link: https://helm.sh/docs/using_helm/#the-format-and-limitations-of-set

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/1960
