### ISSUE TITLE
RKE Config File Reference

### ISSUE THREAD

**Issue by MBishop17** [rancher/docs#196]
As a user, I'd like a reference table that documents the purpose of each option in the RKE config file so that I can customize an imported RKE config.

**Comment by deniseschannon** [comment]
This has been added. it's not in Table format, but it lists all the options.

https://rancher.com/docs/rke/v0.1.x/en/config-options/

There is also the example yaml:

https://rancher.com/docs/rke/v0.1.x/en/example-yamls/
