### ISSUE TITLE
command to show available Kubernetes versions

### ISSUE THREAD

**Issue by nickngch** [rancher/docs#1968]
https://rancher.com/docs/rke/latest/en/upgrades/

provide the command to list out the available Kubernetes versions

`rke config -l -a`

Useful when the user wants to specify the Kubernetes version in cluster.yaml file

**Comment by superseb** [comment]
This should be in after the requested changes has been added in https://github.com/rancher/docs/pull/1911

**Comment by catherineluse** [comment]
Closing this issue because the command was moved to the upgrades page in this PR https://github.com/rancher/docs/pull/2143
