### ISSUE TITLE
Rancher 2.x HA image has duplicate text above and below

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#1971]
Notice, on https://rancher.com/docs/rancher/v2.x/en/installation/ha/#recommended-architecture

The image has the same text below and under the image. We should pick one -- what is the standard procedure to put text under? We should do whatever the standard is.

![image](https://user-images.githubusercontent.com/45179589/68412387-5c3d8f00-0149-11ea-8951-aa2a5d8e1105.png)

```
<figcaption>HA Rancher install with layer 4 load balancer, depicting SSL termination at ingress controllers</figcaption>
![Rancher HA]({{< baseurl >}}/img/rancher/ha/rancher2ha.svg)
<sup>HA Rancher install with Layer 4 load balancer (TCP), depicting SSL termination at ingress controllers</sup>
```

I personally prefer the `<figcaption>` under the image and remove the `<sup>` as the caption is easier to read with the current page styling we are utilizing.

**Comment by catherineluse** [comment]
I'll address this as part of this huge PR https://github.com/rancher/docs/pull/1960

**Comment by catherineluse** [comment]
I prefer the <figcaption> as well

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/1960
