### ISSUE TITLE
"Upgrading Kubernetes" should be more promenant

### ISSUE THREAD

**Issue by stefanlasiewski** [rancher/docs#1975]
Upgrading Kubernetes in a Rancher Launched Kubernetes cluster is a very important task which most Rancher users will do 3-4 times per year. Currently, the instructions to upgrade Kubernetes are kept under _[Cluster Administration > Editing Clusters > Cluster Options > Upgrading Kubernetes](https://rancher.com/docs/rancher/v2.x/en/cluster-admin/editing-clusters/#upgrading-kubernetes)_, which is fairly deep within the hierarchy and rather hidden. I've been reading these docs for 8+ months and didn't know about that section until today.

Would it be possible to move the Upgrading instructions to a more prominent location, such as a new section titled _Cluster Administration  > Upgrading Clusters_?

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/2146
