### ISSUE TITLE
Review and edit k3s documentation

### ISSUE THREAD

**Issue by cjellick** [rancher/docs#1979]
Content of k3s documentation will be updated by next monday, but it could use a review and edit for grammar, wording, formatting, etc.

You won't have to produce new content, just need the existing content cleaned up.

Note: we are still updating existing content, so don't start on this until next week.

This will need done next week so that its done in time for kubecon, but I'm just looking for best effort you can get done in that timeframe.

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/2159
