### ISSUE TITLE
Update Istio docs to include no sidecar annotation

### ISSUE THREAD

**Issue by cloudnautique** [rancher/docs#1993]
On the enable istio sidecar injection in a namespace page: https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/istio/setup/enable-istio-in-namespace/

We should include that if you need to exclude a workload from getting the sidecar injected the user can use the following annotation:
`sidecar.istio.io/inject: “false”`

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/2024
