### ISSUE TITLE
Investigate Hugo app failures (drone failures)

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#1994]
We should spend some time to investigate why hugo crashes / times out in drone-pr some of the time. It's the same generic message each time. The workaround is to restart (sometimes more than once) which slows down work.

Drone should not be at fault. The issue seems to be coming from hugo.

**Comment by davidnuzik** [comment]
This seems to be failing more frequently and is slowing down my effort to get k3s docs in.

**Comment by catherineluse** [comment]
I think we can close this issue because to my knowledge, we have not had a drone failure in some time. Please let me know if it happens again.
