### ISSUE TITLE
Reorganize and clean up config options in RKE docs

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#2001]
This section https://rancher.com/docs/rke/latest/en/config-options/ contains a lot of information, so much that parts of it could be moved out of config options and into their own sections. Cloud providers, for example, could be its own top-level section. This reorganization should make it easier to find how-to guides in the RKE docs.

**Comment by btat** [comment]
Closing as the page has undergone some reorganization already. E.g. cloud provider has its own section in the navigation menu.
