### ISSUE TITLE
RKE Templates clarification for enable monitoring/alerting. 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/docs#2010]
We will document that enabling monitoring/alerting in the RKE template will give you the ability to turn on monitoring/alerting as part of the RKE template but does not enforce whether or not monitoring can be turned on/off in the cluster by the RKE template.

https://github.com/rancher/rancher/issues/23795

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/2017 was merged
