### ISSUE TITLE
Formatting issue on Windows page in "Important" box.

### ISSUE THREAD

**Issue by dnoland1** [rancher/docs#2014]
On https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/

Formatting needs to be fixed:
<img width="910" alt="image" src="https://user-images.githubusercontent.com/468462/69027116-93e6db00-0982-11ea-921e-e7b7624cbbe1.png">

Should be:
```
For Host Gateway (L2bridge) networking, ...
```
Not:
```
For
Host Gateway (L2bridge)
networking, ...
```

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/2020 was merged
