### ISSUE TITLE
Deploying rancher on a cluster using documented rke yaml fails

### ISSUE THREAD

**Issue by aemneina** [rancher/docs#2022]
The rke cluster yaml we provide in our docs [here](https://rancher.com/docs/rancher/v2.x/en/installation/ha/kubernetes-rke/#create-the-rancher-cluster-yml-file) will result in a failing deployment of rancher. This should be amended to include nginx headers required as that cluster definition will deploy ingress nginx by default. 

See here for details on the issue: 
https://github.com/rancher/rancher/issues/23341#issuecomment-540601760

The current location for documenting extra headers is buried here:
https://rancher.com/docs/rancher/v2.x/en/installation/ha/helm-rancher/chart-options/#configuring-ingress-for-external-tls-when-using-nginx-v0-25

**Comment by aemneina** [comment]
I'd imagine our upgrade documentation might need this called out as users upgrading their underlying k8s clusters will hit this.

**Comment by SheilaghM** [comment]
This is about updating the example yaml. We don't have to explain, just update the example.

**Comment by aemneina** [comment]
@SheilaghM I believe that's not the case. There was a fundamental change in Nginx that you won't get a working deployment with the example we provide.

**Comment by SheilaghM** [comment]
@aemneina - yes, and providing a corrected example should resolve this issue.

**Comment by btat** [comment]
The exact page mentioned in the original comment has moved/no longer exists. This [page](https://github.com/rancher/docs/blame/master/content/rancher/v2.5/en/installation/resources/k8s-tutorials/ha-RKE/_index.md#L64-L69) on HA RKE already has the required nginx header block
