### ISSUE TITLE
Document how to remove a cluster from Rancher while still being able to use the cluster

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#2040]
This is in reference to this Slack comment: https://rancher.slack.com/archives/C4G650MQF/p1575307716246100?thread_ts=1575299908.235800&cid=C4G650MQF

**Comment by oskapt** [comment]
Bill, Tom, and I discussed this at length and decided on two things:

1. If you imported the cluster into Rancher, you should be able to detach it and continue using it.
2. If you deployed a hosted provider cluster (EKS, et al), you should be able to detach it and continue using it.
3. If you deployed an RKE cluster from within Rancher, you will not be able to detach it if you stop using Rancher.

To this end, we need some changes to the documentation:

1. If #1 is possible, document how. If not, advise Bill, and he'll pursue a change to the product to make it so.
2. #2 is not possible now, so Bill will take that as a product update.
3. Document that this is not possible.

I will open two other issues for the related docs changes.

**Comment by catherineluse** [comment]
@oskapt I'm not clear about the message we want to tell people about the clusters that can't easily be detached from Rancher at the moment - in other words, every cluster that isn't an imported cluster.

Should we basically just warn people that it will be difficult to detach from Rancher? In this comment https://github.com/rancher/docs/issues/2121#issue-541793092 you had raised the possibility of suggesting third-party backup options, but since that option would mean downtime for the cluster, it sounds like maybe that's not what we're recommending after all, because most people would want to remake a backup of the cluster somewhere else and transition services to get zero downtime.

Any ideas on where to get more clarity  on this?

**Comment by oskapt** [comment]
Please grab me and Bill at the event next week to discuss further.

**Comment by catherineluse** [comment]
I asked Bill about the message that we tell people who want to detach a cluster from Rancher - should we say it is impossible, or possible but unsupported? He said the docs should say it is impossible.

I also asked if we should say in the docs that the feature to detach hosted Kubernetes clusters is in the pipeline. He said we shouldn't mention it yet.

**Comment by catherineluse** [comment]
@oskapt 

I created an RKE cluster on a single node, imported it into Rancher, and deleted it from Rancher. I took note of the number of containers running on the node before it was imported, after it was imported, and after it was deleted.

I found that seven containers were added to the cluster node when it was imported into Rancher, and only four containers were deleted after the cluster was removed from Rancher.

That leaves the following three containers, so I'm thinking that maybe they should also have been automatically removed from the cluster when it was deleted in the Rancher UI:

```

CONTAINER ID        IMAGE                                             COMMAND                  CREATED             STATUS              PORTS               NAMES
--
7ffd341b65bb        rancher/k8s-dns-sidecar                           "/sidecar --v=2 --lo…"   16 minutes ago      Up 16 minutes                           k8s_sidecar_kube-dns-58bd5b8dd7-m6kxn_kube-system_5e220e53-37f8-11ea-a416-063f62d01cfc_0
c02b4ea5d636        rancher/k8s-dns-dnsmasq-nanny                     "/dnsmasq-nanny -v=2…"   16 minutes ago      Up 16 minutes                           k8s_dnsmasq_kube-dns-58bd5b8dd7-m6kxn_kube-system_5e220e53-37f8-11ea-a416-063f62d01cfc_0
0cadfd56a318        rancher/nginx-ingress-controller-defaultbackend   "/server"                17 minutes ago      Up 16 minutes                           k8s_default-http-backend_default-http-backend-78fccfc5d9-2tdvd_ingress-nginx_653182ee-37f8-11ea-a416-063f62d01cfc_0


```

@cjellick Is it expected behavior for these three containers to remain in an imported cluster after the cluster is removed from Rancher?

**Comment by oskapt** [comment]
We should remove all CRDs, the rancher-system namespace, and anything else that we install.

.a

**Comment by catherineluse** [comment]
Will said that a rancher/rancher issue should be used to track the capability to remove hosted Kubernetes clusters and RKE clusters from Rancher, remove Rancher components, and retain full control over the cluster. Denise confirmed an issue for this doesn't exist yet, so I created one here. https://github.com/rancher/rancher/issues/25234

**Comment by catherineluse** [comment]
In this PR I worked with Will to document the official responses we want to give to people with questions about what happens if they no longer need Rancher. The doc is no longer under the title "Removing Rancher Server," it is now in the FAQ and is called "Rancher is no Longer Needed." https://rancher.com/docs/rancher/v2.x/en/faq/removing-rancher/

I think this issue can probably be closed and the discussion of the work that needs to be done on Rancher itself can be on the `rancher/rancher` issue https://github.com/rancher/rancher/issues/25234

**Comment by catherineluse** [comment]
@oskapt 
I asked Dan if it is expected behavior for the three containers to remain on the imported cluster after it's removed from Rancher. He said:
> Yes, if you use rancher to deploy things and then we delete an ingress controller bad things will happen. We purposely don't remove things so your cluster is still fine after rancher is gone. The goal is to remove enough that rancher isn't there but could be reimported again, not to scorch the earth with anything we put in the cluster.

**Comment by oskapt** [comment]
that's fair - we don't want to break things on our way out the door.
