### ISSUE TITLE
Update catalog docs of missing variable types and broken link

### ISSUE THREAD

**Issue by guangbochen** [rancher/docs#2045]
https://github.com/rancher/charts/pull/343
https://github.com/rancher/charts/issues/334

1. Add the missing variable types of `questions.yml`
2. fix broken helm developer guide link

**Comment by guangbochen** [comment]
link PR to https://github.com/rancher/docs/pull/2046

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/2046 was merged
