### ISSUE TITLE
Create Custom Global Role and associate a group to a global role

### ISSUE THREAD

**Issue by deniseschannon** [rancher/docs#2047]
1. Create a custom global role
 - When deleting a custom global role, all global role bindings with this custom role are deleted.
 -  If this was the only global role associated with a user and it's deleted, they will lose access to Rancher. An admin would need to edit the user and apply new global permissions. 
2. Assign Global Role (under Groups) 
   - Only works with authentication that has groups (not local auth)
  - Use case: There is an existing group in your external auth provider that will be all admins. You can easily add the group and associate `admin` to the group so when a user logs in they would get admin access. 
   - When the user logs in, they will end up getting the individual user global role (based on the default global roles that are set). If they are in any groups, they will also get the permissions from the groups. 
   - If someone is removed from the external auth provider group, they lose their permissions from the group global role binding, but they would continue to have their individual user global roles.

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/2100 was merged
