### ISSUE TITLE
Rancher Installation requirements

### ISSUE THREAD

**Issue by ibrokethecloud** [rancher/docs#2050]
The Rancher Installation requirements available at:

[https://rancher.com/docs/rancher/v2.x/en/installation/requirements/](https://rancher.com/docs/rancher/v2.x/en/installation/requirements/)

mention support for RHEL/CentOS and Docker v1.13

Our [TOS](https://rancher.com/support-maintenance-terms/#2.3.x) already support RHEL and Docker CE.

An update is needed to the installation docs to update the support matrix.

**Comment by catherineluse** [comment]
Closing this issue because the specific versions of OS and Docker are being removed from the installation docs. We are just saying that Rancher should work on any modern Linux and Docker version and people can refer to the terms of service for specific versions
