### ISSUE TITLE
Docs references wrong UI location for adding SSL certs

### ISSUE THREAD

**Issue by Robbie-Cook** [rancher/docs#2066]
In [the docs for adding a cert to a to a project/cluster](https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/certificates/), it states to add a new certificate, you should go to Resources -> Certificates. However, the menu seems to now located under Resources -> Secrets -> Certificates as of `rancher/rancher:latest`

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/2122
