### ISSUE TITLE
RKE Retention description for etcd snapshots - Retention supercedes retention

### ISSUE THREAD

**Issue by dnoland1** [rancher/docs#2070]
At https://rancher.com/docs/rke/latest/en/etcd-snapshots/recurring-snapshots/#options-for-the-etcd-snapshot-service this doesn't make sense:

Option | Description
-----|-----
retention | The number of snapshots to retain before rotation. This supercedes the `retention` option and will override it if both are specified.

How does the retention option supercede the retention option?

**Comment by catherineluse** [comment]
Catherine to ask Seb

**Comment by Rancheroo** [comment]
I was trying to make a pull request to the docs
https://github.com/rancher/docs/pull/2446

My understanding was that in RKE 0.2+ the retention field used the number or snapshots (as stated above) not the time period. However now i'm not sure, does it use both? What is the best practice for providing this retention value 24h or 24?
Do we need to specify RKE version in the example?

**Comment by superseb** [comment]
This was probably from the time it was still on one page, but nevertheless its confusing. It refers to the configuration parameters from pre v0.2, and the option description says it will override if both are specified. The description of both fields in both versions is also accurate as far as I can see.

**Comment by catherineluse** [comment]
https://github.com/rancher/docs/issues/2070

**Comment by catherineluse** [comment]
Closing this issue because it is clarified in this commit https://github.com/rancher/docs/commit/f6bfbd6c625c23ecf655af90d59c2d2cbf230df9
