### ISSUE TITLE
Update docs to include bare minimum on disk capacity

### ISSUE THREAD

**Issue by panoslith** [rancher/docs#2071]
Its common for users to ask how much storage is required for rancher installation. 

While this varies per use case and scale, we can at least offer a bare minimum(e.g 50GB) of disk capacity for the installation. 

Specify under this
https://rancher.com/docs/rancher/v2.x/en/installation/requirements/#disks

**Comment by catherineluse** [comment]
After a discussion with Craig, Denise, and Dan, we decided we're not going to update it at this time, for these reasons:

1. It varies per use case and scale, as you mentioned
2. The default disk size that comes with the required CPU and memory would be sufficient in most cases
3. It isn't difficult to add more disk capacity to the cluster if necessary
