### ISSUE TITLE
Update docs supported web browsers

### ISSUE THREAD

**Issue by curx** [rancher/docs#2077]
The docs and changlog should  have a information what kind of webbrowser are currently supported.
Since Rancher v2.3.3 the Microsoft Edge (not the chrome engine) is not more supported.

It's more a broken change for companies that use this browser widely!

Thanks and regards,
Thorsten

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/2180
