### ISSUE TITLE
Need to update docs for adding registry

### ISSUE THREAD

**Issue by dnoland1** [rancher/docs#2081]
Regarding - https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/registries/

Believe in v2.3, this changed:
_2. From the main menu, select Resources > Registries. Click Add Registry._

Navigation is now:
Resources -> Secrets -> Registry Credentials

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/2113
