### ISSUE TITLE
document requirements for monitoring per project

### ISSUE THREAD

**Issue by loganhz** [rancher/docs#2106]
moved from https://github.com/rancher/rancher/issues/20583

**What kind of request is this (question/bug/enhancement/feature request):**
doc bug/rfe

**Other details that may be helpful:**
Today we have generic doc's for enabling cluster level monitoring. Just a placeholder doc bug to extend that to resource requirements when monitoring at the project level.

**Comment by catherineluse** [comment]
Closing this issue because the project monitoring resource requirements are documented here https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.0.x-v2.4.x/cluster-monitoring/project-monitoring/#project-level-monitoring-resource-requirements
