### ISSUE TITLE
add an upgrade path for upgrading Rancher and cert-manger v0.12

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/docs#2117]
Because of the API change in cert-manager since v0.11 
https://cert-manager.io/docs/installation/upgrading/upgrading-0.10-0.11/
and how helm handles upgrading apps(helm compares the running app with the original template used to install it), we have to upgrade Rancher with the following steps if we want to run Rancher with cert-manager 0.12:

Step1: make a one-time snapshot of Rancher data
```
rke etcd snapshot-save --name rancher-2-3-3-backup.db --config rancher-cluster.yml
```
Result: RKE takes a snapshot of etcd running on each etcd node. The file is saved to /opt/rke/etcd-snapshots.

Step2: uninstall Rancher
```
helm delete rancher -n cattle-system
```

Step3: uninstall cert-mananger
```
helm delete cert-manager -n cert-manager
```

Step4: Delete the CustomResourceDefinition using the link to the version v0.9.1 you installed
```
kubectl delete -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.9/deploy/manifests/00-crds.yaml
```

Step5: Install the new CustomResourceDefinition resources
```
kubectl apply -f https://raw.githubusercontent.com/jetstack/cert-manager/release-0.12/deploy/manifests/00-crds.yaml
```

Step6: Re-install cert-manager
```
helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v0.12.0 
```

Step7; Re-install Rancher
```
helm install rancher rancher-latest/rancher --version 2.3.4-rc4 --namespace cattle-system --set hostname=jiaqi-ha.qa.rancher.space  
```

**Comment by catherineluse** [comment]
@jiaqiluo Is this issue addressed by this PR? https://github.com/rancher/docs/pull/2168

**Comment by jiaqiluo** [comment]
@catherineluse We still need some changes and I put a PR for it. Also, I need to get the confirmation from @rawmind0 for the new changes.

**Comment by jiaqiluo** [comment]
Verified that the information and steps for handling the upgrade of cert-manager older than 0.11 were added to the staging documentation. 

This issue can be closed.
