### ISSUE TITLE
On the architecture page the link to choosing an installation method is broke

### ISSUE THREAD

**Issue by pvandervelde** [rancher/docs#2118]
On this page: https://rancher.com/docs/rancher/v2.x/en/overview/architecture/ the link to `choosing an installation method` points to: https://rancher.com/docs/rancher/v2.x/en/installation/choosing-installation

However that link returns a 404. I'd happily put in a PR but I'm not sure where it's supposed to be pointing.

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/2123
