### ISSUE TITLE
Change title for "Cleaning Up Clusters" section

### ISSUE THREAD

**Issue by oskapt** [rancher/docs#2120]
The section on [Cleaning Up Clusters](https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/) can use a different title. It's not about cleaning a cluster - it's about disconnecting a node from a Rancher-launched cluster and deleting all of the Kubernetes bits from it, returning it to a (mostly) clean node that can be used for something else. 

It also needs a prominent warning at the top that this is about deleting Kubernetes from a node.

(See rancher/docs#2040 for overall context)

**Comment by catherineluse** [comment]
This issue is addressed by https://github.com/rancher/docs/pull/2133

The title of the section is now "Removing Kubernetes Components from Nodes."

The top of the section now says:

> This section describes how to disconnect a node from a Rancher-launched Kubernetes cluster and remove all of the Kubernetes components from the node. This process allows you to use the node for other purposes.

I didn't make it a warning because the message now aligns with the title.
