### ISSUE TITLE
Create new docs page about Removing rancher components and remove redirect

### ISSUE THREAD

**Issue by oskapt** [rancher/docs#2121]
In the second item on [this page](https://rancher.com/docs/rancher/v2.x/en/removing-rancher/) we say

> In this context, you are removing Rancher components from Kubernetes clusters that you launched using Rancher.

This sounds like it's going to remove Rancher from a running cluster and leave the cluster intact. In actuality it redirects to a page about how to nuke all of the Kubernetes bits and delete everything from the node. That redirect is not obvious (see #2120), and someone might accidentally delete their running cluster. 

I'd like to see this renamed and go to its own page that discusses the available options for removing Rancher components (see #2040), what is and isn't possible, and what alternatives (if any) exist (links to Velero/Restic, Stashed). 

The goal is that when users come looking for information on how to disconnect a cluster from Rancher and still keep it running, they can quickly and clearly understand their options and be taken to guides that walk them through each step. If it's not possible (Rancher-launched RKE), then we give them links to third-party solutions that might be able to assist them.

**Comment by catherineluse** [comment]
Is it true to say this:

> If you need to detach non-imported clusters from Rancher while still being able to use the cluster, we recommend backing up the cluster, deleting it in Rancher, then restoring it from backup.

**Comment by oskapt** [comment]
No, that's not a solution that supports the idea of, "if you brought it, you can take it with you." 

It introduces downtime for all workloads running on that cluster, and any restore from backup, no matter how reliable, is a risk. 

Faced with that choice, a user would choose instead to build a new cluster, migrate the data, cut over to it, and then delete the original cluster, none of which fits into the idea that you can "uninstall" Rancher cleanly from your existing clusters. 

Importing a cluster installs components that bridge between the Kubernetes API and the Rancher server. Rancher becomes another management piece, and it is reasonable to expect that we can reverse that process cleanly with no downtime and no impact to running workloads.

If we cannot currently do this, then we need to say so in the docs and add a feature request to get it into the product.

**Comment by catherineluse** [comment]
Craig said that for imported clusters, you would just delete it from Rancher, and you would still be able to use the cluster. And if it doesn't work like that, it's a bug

**Comment by catherineluse** [comment]
Closing this issue because when we updated this page https://rancher.com/docs/rancher/v2.x/en/faq/removing-rancher/, it sounded like that all that needs to be documented for now.
