### ISSUE TITLE
Markup issues on "Collect and Publish Images to your Private Registry" page

### ISSUE THREAD

**Issue by superseb** [rancher/docs#2127]
https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/air-gap/populate-private-registry/

Table under `A. Find the required assets for your Rancher version` is broken.

Step 3 of `D. Populate the private registry` shows ```plain in code block

Directly under there is `<div class="tab-pane" title="Linux and Windows Clusters">` shown in a code block.

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/2131 and https://github.com/rancher/docs/pull/2132
