### ISSUE TITLE
What does it mean to disable the default k3s network policy?

### ISSUE THREAD

**Issue by mak3r** [rancher/docs#2178]
What exactly does disable network policy do? From a user standpoint, I don’t see any docs on what the network policy is to begin with (google “k3s network policy” or search the docs page). So, I'm not not sure what is being disabled when I use the `--disable-network-policy` flag or how it correlates to other flags such as the group for networking:
```
--cluster-cidr value                       (networking) Network CIDR to use for pod IPs (default: "10.42.0.0/16")
--service-cidr value                       (networking) Network CIDR to use for services IPs (default: "10.43.0.0/16")
--cluster-dns value                        (networking) Cluster IP for coredns service. Should be in your service-cidr range (default: 10.43.0.10)
--cluster-domain value                     (networking) Cluster Domain (default: "cluster.local")
--flannel-backend value                    (networking) One of 'none', 'vxlan', 'ipsec', or 'flannel' (default: "vxlan")
 ```

**Comment by davidnuzik** [comment]
Close in favor of rancher/k3s issue https://github.com/rancher/k3s/issues/1308
We are using rancher/k3s for tracking k3s docs presently as it makes it easier to manage on our boards. We may move to rancher/docs for issue tracking in the future (requires setting up a separate board).
