### ISSUE TITLE
Explain how to override cluster capabilities

### ISSUE THREAD

**Issue by rmweir** [rancher/docs#2182]
When a user imports a cluster, we are ignorant to how that cluster is provisioned. This makes it so we don't know if a user provisioned the cluster with an option like PSPs being enabled. Capability override annotations give us this ability: https://github.com/rancher/rancher/issues/21039

It needs to be clear that this does NOT grant these abilities. It is simply a means of informing rancher that the cluster was given these abilities outside of rancher. For example: If the cluster was not provisioned with PSPs, then setting the override annotation will not make then enable PSPs.

the way it works is by adding an annotation to the cluster with the format `capabilities/<capability>: <value>` where <capability> is replaced with the capability that is to be overridden. <value> can be replaced by a primitive, or a json encoded object.

Examples:

pspEnabled -
"capabilities.cattle.io/pspEnabled": "true"

Ingress capabilities -
"capabilities.cattle.io/ingressCapabilities": "[{\"customDefaultBackend\":true,\"ingressProvider\":\"asdf\"}]"

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/2427
