### ISSUE TITLE
Broken link to external documentation

### ISSUE THREAD

**Issue by rosskirkpat** [rancher/docs#2188]
On our docs page [for creating custom catalog charts](https://rancher.com/docs/rancher/v2.x/en/catalog/custom/creating/#example-custom-chart-creation)

We have a note box under the section:

`NOTE:
For a complete walkthrough of developing charts, see the upstream Helm chart developer reference.`

`developer reference` link points to [external helm documentation page that no longer exists](https://helm.sh/docs/topics/chart_template_guide/)

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by this PR https://github.com/rancher/docs/pull/2190
