### ISSUE TITLE
How to use custom metrics HPA

### ISSUE THREAD

**Issue by mak3r** [rancher/docs#2205]
https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/horitzontal-pod-autoscaler/manage-hpa-with-kubectl/#configuring-hpa-to-scale-using-custom-metrics-with-prometheus
1. refers the user to banzai-charts/prometheus adapter which no longer exists (404)
1. (nice to have) actually showing how to use a custom metrics HPA once the setup is properly configured.

**Comment by catherineluse** [comment]
I think someone fixed the link already - I went to the page and didn't see any 404s/

**Comment by btat** [comment]
Resolved as per https://github.com/rancher/docs/issues/2205#issuecomment-607680675.
