### ISSUE TITLE
projects page has confusing text about namespaces and projects

### ISSUE THREAD

**Issue by oskapt** [rancher/docs#2215]
From [this page](https://rancher.com/docs/rancher/v2.x/en/cluster-admin/projects-and-namespaces/)

> Within Rancher, you can further divide projects into different namespaces, which are virtual clusters within a project backed by a physical cluster. Should you require another level of organization beyond projects and the default namespace, you can use multiple namespaces to isolate applications and resources.

This is confusing, because a Project is a group of Namespaces.  If you don't have a need for more than the default namespace, you also do not need more than the Default Project. The first part of the sentence makes it sound like Namespaces are a feature of Rancher, when they're a feature of Kubernetes and should be called out first.

Proposed fix:

> Namespaces offer a way to create virtual clusters, backed by a physical cluster. A Project can contain multiple Namespaces, making it possible to organize and isolate resources within the Project. 

I feel like that might not give enough information, but because the whole page prioritizes Projects over Namespaces, any additional information I want to add is already included higher up in the page. It might make sense to reorganize it, introducing Namespaces and then Projects.

Projects are also due for an overhaul, so if that's coming soon, we might just wait and tackle this whole page when those changes hit.

**Comment by catherineluse** [comment]
Closing this issue because it is addressed by https://github.com/rancher/docs/pull/2219
