### ISSUE TITLE
Document an example of adding options for enabling Thanos

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#2229]
https://github.com/rancher/rancher/issues/24793

**Comment by deniseschannon** [comment]
Steps to reproduce (least amount of steps as possible):
We need to update the Cluster Monitoring Configuration and Project Monitoring Configuration pages to make it easy to enable Thanos. Currently, we need to pass all options in the answers section.

prometheus.thanos.enabled=true
prometheus.thanos.objectConfig.type=S3
prometheus.thanos.objectConfig.config.bucket=jiaqi-thanos
prometheus.thanos.objectConfig.config.region=us-west-1
prometheus.thanos.objectConfig.config.endpoint=s3.amazonaws.com
prometheus.thanos.objectConfig.config.signature_version2=false
prometheus.thanos.objectConfig.config.insecure=true
prometheus.thanos.objectConfig.config.access_key=*****
prometheus.thanos.objectConfig.config.secret_key=*****
See this issue for more info: #24214

**Comment by SheilaghM** [comment]
This is for the 2.4 docs only.

**Comment by btat** [comment]
Docs version no longer maintained.
