### ISSUE TITLE
Known Upgrade Issues needs clarification

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#2243]
Re: https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/#known-upgrade-issues
The section notes: `Any user provisioned cluster will be automatically updated upon any edit as tolerations were added to the images used for Kubernetes provisioning.` but this is unclear.

Is it referring to this known issue from release notes?

> If you have Rancher cluster with OpenStack cloud provider having  LoadBalancer set, and the cluster was provisioned on version 2.2.3 or  less, the upgrade to the Rancher version v2.2.4 and up will fail. Steps  to mitigate can be found in the comment to [20699]

I don't understand this section since it doesn't actually note all the known issues, but seems to just pick 4.  Are they the most noteworthy?  Could do with some explanation and maybe a reference to the release notes or actual bugs for more technical information.

**Comment by catherineluse** [comment]
I believe the issue about tolerations originates from Rancher v2.3.0. In the [release notes,](https://forums.rancher.com/t/rancher-release-v2-3-0/15476) it's listed as important:

> Please be aware that upon an upgrade to v2.3.0, any edits to a Rancher launched Kubernetes cluster will cause all system components to restart due to added tolerations to Kubernetes system components. Plan accordingly.

It looks like maybe more information from the release notes needs to be included in the upgrade docs.
