### ISSUE TITLE
Reword cluster cleaning docs

### ISSUE THREAD

**Issue by rmweir** [rancher/docs#2252]
Reword cluster cleaning docs (https://rancher.com/docs/rancher/v2.x/en/cluster-admin/cleaning-cluster-nodes/#imported-cluster-nodes) to not refer to nodes, and possibly move section to a different page such as https://rancher.com/docs/rancher/v2.x/en/faq/removing-rancher/

**Comment by catherineluse** [comment]
Closing because the section was clarified here https://github.com/rancher/docs/pull/2253
