### ISSUE TITLE
RKE Template creation warning

### ISSUE THREAD

**Issue by chrisreed87** [rancher/docs#2256]
Under the documentation for creating RKE templates:
https://rancher.com/docs/rancher/v2.x/en/admin-settings/rke-templates/creating-and-revising/#creating-a-template

Might be helpful to provide a warning/information blurb that once a cluster is "managed" by an RKE template, it cannot be disconnected and the option to uncheck "Use an existing RKE Template and revision" is greyed out and unavailable

**Comment by catherineluse** [comment]
Closing this issue because it is addressed in this commit https://github.com/rancher/docs/commit/164d548380f5a6c5a26d3fe4f1800607a6983113
