### ISSUE TITLE
Single node upgrade section should be clearer on the instruction

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#2262]
**Link:** https://github.com/rancher/docs/edit/master/content/rancher/v2.x/en/upgrades/upgrades/single-node/_index.md

**Issue:** 
The white box ends before the tabs for the final command that should be run.  I think it would help if the text was clearer/more concise and if the command tabs were in the same white box and indented to be clearly part of the numbered list.

**Current:** 
![image](https://user-images.githubusercontent.com/8906089/74175112-10f5b980-4c2d-11ea-937e-368340ff7672.png)

**Comment by catherineluse** [comment]
Closing this issue because I've broken step "C: Upgrade Rancher" into two steps: one to pull the new Docker image and one to start the container.

I couldn't put the tabs in the white box because the white box is just what the theme adds to numbered steps.
