### ISSUE TITLE
[2.4] Add docs for monitoring changes

### ISSUE THREAD

**Issue by loganhz** [rancher/docs#2276]
Monitoring changes in PR https://github.com/rancher/system-charts/pull/138
Related issues: https://github.com/rancher/rancher/issues/20624 and https://github.com/rancher/rancher/issues/23874

In monitoring version **0.0.8** （which is available in Rancher 2.4.0 ）we will support the following stuff in **cluster** monitoring and **project** monitoring.

Note:

There is no UI for these new configurations. Users need to config them in custom answers.

Changes:

1. Support Prometheus RemoteWrite and RemoteWrite. More docs via https://prometheus.io/docs/operating/integrations/#remote-endpoints-and-storage. The spec for RemoteWrite and RemoteRead can be found via https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#remotewritespec and https://github.com/coreos/prometheus-operator/blob/master/Documentation/api.md#remotereadspec

![image](https://user-images.githubusercontent.com/21168270/74292075-04c74480-4d72-11ea-9875-0adf70dbc80a.png)

2. Support to config LivenessProbe and  ReadinessProbe. The spec is https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#probe-v1-core 

![image](https://user-images.githubusercontent.com/21168270/74292708-aac77e80-4d73-11ea-9905-4f9e294aaff6.png)

**Comment by catherineluse** [comment]
This applies to monitoring v0.1.0

**Comment by kamushadenes** [comment]
Despite https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#basicauth, I can't get basic auth working. 
It either doesn't do anything when I save, or simply doesn't deploy prometheus-cluster-monitoring if I insert the data before enabling monitoring.

prometheus.remoteWrite[0].basicAuth.password: SOME_BASE64=
prometheus.remoteWrite[0].basicAuth.username: 13117
prometheus.remoteWrite[0].name: production
prometheus.remoteWrite[0].url: https://url

If I just use the URL, it works, but obviously fails to authenticate.


Is this a known issue?
