### ISSUE TITLE
clarify alert grouping options

### ISSUE THREAD

**Issue by oskapt** [rancher/docs#2278]
In multiple places on [this page](https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/alerts/) we provide an explanation for Group Wait Time, Group Interval Time, and Repeat Wait Time.

Both of the last two provide the same explanation (other than the default time):

> Group Interval Time: How long to wait before sending an alert that has been added to a group which contains already fired alerts, default to 30 seconds.
>
> Repeat Wait Time: How long to wait before sending an alert that has been added to a group which contains already fired alerts, default to 1 hour.

I suspect that the latter is how long to wait before sending _another_ alert, but I'm not sure. Whatever it is, it will help if we clarify it in all locations.

**Comment by oskapt** [comment]
The change would also apply to the [project alerts page](https://rancher.com/docs/rancher/v2.x/en/project-admin/tools/alerts/).

**Comment by oskapt** [comment]
The inline help for alerts states that the Repeat Wait Time is:

> How long to wait before re-sending a given alert that has already been sent.

**Comment by catherineluse** [comment]
Closing this issue because the repeat wait time has been updated:

> Repeat Wait Time: How long to wait before re-sending a given alert that has already been sent, default to 1 hour.
