### ISSUE TITLE
Update proxy documentation

### ISSUE THREAD

**Issue by bmdepesa** [rancher/docs#2283]
When Rancher is behind a proxy, and the user is importing an existing cluster, `10.43.0.1/16` must be added to `NO_PROXY` for the cluster to register successfully.

This is not required for nodedriver/custom clusters. 

Edit: Our HA docs have `10.0.0.0/8` specified as a default in `NO_PROXY`. We should be consistent between the two. This has been tested and confirmed to be working. 

See: https://github.com/rancher/rancher/issues/25372

**Comment by davidnuzik** [comment]
https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/proxy/#docker-installation

Is this the only place?

In any case, basically on this page we just need to ad that IP/CIDR to the bulleted list and to the commandline example below in the #docker-installation section.

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/2284 was merged
