### ISSUE TITLE
Hardening guide recommendation 1.1.2 is missing from v2.3.3 guide

### ISSUE THREAD

**Issue by mak3r** [rancher/docs#2287]
The hardening guide item recommended in v2.3 https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3/#1-1-2-install-the-encryption-provider-configuration-on-all-control-plane-nodes
is absent from the v2.3.3 hardening guide.
https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.3/ 

I believe it is still a valid level 1 profile item that should be included in v2.3.3?

**Comment by btat** [comment]
Docs version no longer maintained.
