### ISSUE TITLE
secret and configmap names don't have to be unique in the set of all members

### ISSUE THREAD

**Issue by oskapt** [rancher/docs#2292]
[This page](https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/registries/) and others dealing with secrets, certificates, and configmaps, all say:

> Note:
> Kubernetes classifies secrets, certificates, ConfigMaps, and registries all as secrets, and no two secrets in a project or namespace can have duplicate names. Therefore, to prevent conflicts, your registry must have a unique name among all secrets within your workspace.

This does not appear to be accurate. I can create a ConfigMap called `test` and a secret called `test` both in the `default` namespace.  I am unable to create a registry credential for `test`, and I didn't test with a certificate. It might only be that ConfigMaps are not considered Secrets.

```yaml
apiVersion: v1
data:
  thing: b3RoZXI=
kind: Secret
metadata:
  annotations:
    field.cattle.io/creatorId: user-l5dmw
  creationTimestamp: "2020-02-18T17:19:41Z"
  labels:
    cattle.io/creator: norman
  name: test
  namespace: default
  resourceVersion: "173105"
  selfLink: /api/v1/namespaces/default/secrets/test
  uid: c11332f5-f604-4fdf-82ed-c905ee5a3457
type: Opaque
---
apiVersion: v1
data:
  thing: other thing
kind: ConfigMap
metadata:
  annotations:
    field.cattle.io/creatorId: user-l5dmw
  creationTimestamp: "2020-02-18T15:43:05Z"
  labels:
    cattle.io/creator: norman
  name: test
  namespace: default
  resourceVersion: "159566"
  selfLink: /api/v1/namespaces/default/configmaps/test
  uid: 8fef09d5-8ff6-4b03-bdea-583ddef94039
```

**Comment by catherineluse** [comment]
The Google Cloud docs say this:

> Secrets are secure objects which store sensitive data, such as passwords, OAuth tokens, and SSH keys, in your clusters. Storing sensitive data in Secrets is more secure than plaintext ConfigMaps or in Pod specifications.

So I removed ConfigMaps from the list of secrets. https://github.com/rancher/docs/commit/b67e0050508b3022700155bbdecdb616945869b4

@oskapt can this issue be closed?

**Comment by oskapt** [comment]
sorry for the late reply - my inbox got out of hand for a few months.

yes, lgtm. thank you.
