### ISSUE TITLE
Edit this page with arrow button - symbolism mismatch

### ISSUE THREAD

**Issue by cyberjaguar** [rancher/docs#2305]
On each page of the documentation there is a button on the bottom with an `arrow right` and the text `EDIT THIS PAGE` - I found the arrow to be misplaced here as it is interpreted as "next page" - this is what we have been trained on bazillions of internet sites since many years - arrows are for navigation.

**Comment by Bilal-io** [comment]
I totally agree with you and this is the reason I am here. I came across this ticket because I searched for "EDIT THIS PAGE".

This should be updated for better UX. If any designer can come up with a better button design, I'd be happy to create a PR to fix it.
