### ISSUE TITLE
no navigation at all

### ISSUE THREAD

**Issue by cyberjaguar** [rancher/docs#2306]
There is no navigation in the docs - you forgot that? 

You have a content list on the left side, but there is no navigation at all, at least I can not see one. Also there does not seem to be any kind of keyboard navigation. Why not?

**Comment by catherineluse** [comment]
The left navigation bar isn't just a content list, it has sections that expand and collapse, and the sections contain more pages.

Can you please provide examples of what you have in mind?

**Comment by catherineluse** [comment]
I'm going to raise a GitHub issue about adding keyboard navigation to the docs. (it will be in a different repository)

**Comment by btat** [comment]
Not applicable.
