### ISSUE TITLE
bad readability because of low contrast and thin font

### ISSUE THREAD

**Issue by cyberjaguar** [rancher/docs#2307]
The docs have very bad readability, because you make it harder to read with a grey background and an extra thin font - why are you doing that? Please make readability of documentation the top priority for design decisions, you can still add a lot of CI via icons / images / general layout but do not let designers touch things that make it harder for your users to **read things**. 
This makes me very huuuuungry! Jezuz.....

**Comment by btat** [comment]
Addressed with the move to our new site.
