### ISSUE TITLE
Broken Link on Persistent Storage Docs

### ISSUE THREAD

**Issue by leflambeur** [rancher/docs#2324]
https://rancher.com/docs/rancher/v2.x/en/cluster-admin/volumes-and-storage/examples/ebs/

Has a link to setting up the concept in rancher but that link points to

https://rancher.com/docs/rancher/v2.x/en/cluster-admin/volumes-and-storage/examples/attaching-existing-storage

Which 404's

I believe it should point to here:

https://rancher.com/docs/rancher/v2.x/en/cluster-admin/volumes-and-storage/attaching-existing-storage/

**Comment by catherineluse** [comment]
closing this issue because it is fixed in this commit https://github.com/rancher/docs/commit/a723b9bc997c4d0c1720f32364726011b70f8648
