### ISSUE TITLE
suggestion v2.3.5 hardening guide and possibly all future hardening guides

### ISSUE THREAD

**Issue by patrick0057** [rancher/docs#2332]
To ease the process of following the instructions of the hardening guide, it would be nice to be able to just copy and paste new file creations like the following (referencing from ( https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/#configure-kernel-runtime-parameters )

```
cat << EOF > /etc/sysctl.d/90-kubelet.conf
vm.overcommit_memory=1
vm.panic_on_oom=0
kernel.panic=10
kernel.panic_on_oops=1
kernel.keys.root_maxbytes=25000000
EOF
```

**Comment by Pitson3** [comment]
Thank you @patrick0057, your answer simplified my goal.
