### ISSUE TITLE
Additional information in Rancher v2.3.5 hardening guide

### ISSUE THREAD

**Issue by patrick0057** [rancher/docs#2335]
It would be useful for the end user to understand what all they are changing from the default config and why in the following sections of the hardening guide.  The v2.3.3 hardening guide had much more detail, so if explanation was left out as it assumed the user went through the previous guide, there should be instructions pointing back to that guide for explanations.
https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/#reference-hardened-rke-cluster-yml-configuration
https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/#reference-hardened-rke-template-configuration
https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/#hardened-reference-ubuntu-18-04-lts-cloud-config

**Comment by btat** [comment]
These doc versions are no longer maintained.
