### ISSUE TITLE
Rancher v2.3.3 hardening guide missing components from v2.3

### ISSUE THREAD

**Issue by patrick0057** [rancher/docs#2338]
The Rancher v2.3.3 hardening guide does not indicate how to create the admission.yaml, audit.yaml, encryption.yaml and event.yaml like in the v2.3 guide.  The guide should include how to create these files or reference the original guide for instructions.
https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.3/

**Comment by btat** [comment]
These doc versions are no longer maintained.
