### ISSUE TITLE
Rancher v2.3.3 hardening guide addons not included in full examples

### ISSUE THREAD

**Issue by patrick0057** [rancher/docs#2339]
In the Rancher v2.3.3 hardening guide, the addons section is not included inline with the complete cluster.yml section or the complete rke template section.
https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.3/#appendix-b-complete-rke-cluster-yml-example
https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.3/#appendix-c-complete-rke-template-example

**Comment by btat** [comment]
These doc versions are no longer maintained.
