### ISSUE TITLE
Rancher hardening guide v2.3.5 full example discrepancy

### ISSUE THREAD

**Issue by patrick0057** [rancher/docs#2340]
The Rancher hardening guide for v2.3.5 ( https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/ ) has a discrepancy in the addons section with the PodSecurityPolicy apiVersion.  In the full example for cluster.yml the PodSecurityPolicy section's first three lines:
```
  ---
  apiVersion: policy/v1beta1
  kind: PodSecurityPolicy
```

In the full example for the RKE Template the PodSecurityPolicty section's first three lines:
```
    ---
    apiVersion: extensions/v1beta1
    kind: PodSecurityPolicy
```

**Comment by paraglade** [comment]
resolved here: https://github.com/rancher/docs/pull/2374
