### ISSUE TITLE
Rancher v2.3.5 hardening guide needs to be validated for Kubernetes v1.16

### ISSUE THREAD

**Issue by patrick0057** [rancher/docs#2341]
Rancher v2.3.5 hardening guide needs to be validated for Kubernetes v1.16.
https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/

**Comment by paraglade** [comment]
With v2.3.5 of the Rancher hardening guide the goal is to align the guide with the version of Kubernetes covered in CIS Kubernetes Benchmark v1.5.0. With that goal a hardening guide for Kubernetes v1.16 might be covered in future revisions of the CIS Kubernetes Benchmark.
