### ISSUE TITLE
Need to update the 2.3.3 Hardening Guide to Align the Test Numbers

### ISSUE THREAD

**Issue by maggieliu** [rancher/docs#2344]
There are some mismatch tests with the test numbers in the 2.3.3: https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.3/

<img width="996" alt="Screen Shot 2020-03-12 at 4 11 28 PM" src="https://user-images.githubusercontent.com/2137556/76575387-2e13e700-647c-11ea-9a60-be9f5d9ff9cb.png">

**Comment by btat** [comment]
These doc versions are no longer maintained.
