### ISSUE TITLE
Issues in CIS 1.5 Self Assessment Guide

### ISSUE THREAD

**Issue by sowmyav27** [rancher/docs#2347]
In this section - https://rancher.com/docs/rancher/v2.x/en/security/benchmark-2.3.5/#4-1-3-ensure-that-the-proxy-kubeconfig-file-permissions-are-set-to-644-or-more-restrictive-scored

- Tests 4.1.3, 4.1.4, 4.1.5 and 4.1.6 - The Result and the Remediation are incorrect

**Comment by paraglade** [comment]
@sowmyav27 Could you provide some details why the result and remediation are incorrect for these tests?

**Comment by sowmyav27** [comment]
@paraglade The test 4.1.3 - 4.1.6 - are for kubeconfig files and not for configuration files . As per the CIS benchmark 1.5 document:
```
4.1.3 - Description: If kube-proxy is running, and if it is using a file-based kubeconfig file, ensure that the proxy kubeconfig file has permissions of 644 or more restrictive.
```

**Comment by paraglade** [comment]
@maggieliu @sowmyav27 
For those tests the result and remediation are as follows:

**Result**: Not Applicable

**Remediation**: RKE doesn’t require or maintain a configuration file for the * service. All configuration is passed in as arguments at container run time.

Since RKE does not use a config files is this not an acceptable reason for skipping these tests?

**Comment by sowmyav27** [comment]
@paraglade As per @leodotcloud 's comments on this
```
root@localhost:~# ls -ltr /etc/kubernetes/ssl/ | grep kubecfg
-rw------- 1 root root  517 Mar 16 09:19 kubecfg-kube-apiserver-proxy-client.yaml
-rw------- 1 root root  465 Mar 16 09:19 kubecfg-kube-scheduler.yaml
-rw------- 1 root root  445 Mar 16 09:19 kubecfg-kube-node.yaml
-rw------- 1 root root  533 Mar 16 09:19 kubecfg-kube-apiserver-requestheader-ca.yaml
-rw------- 1 root root  449 Mar 16 09:19 kubecfg-kube-proxy.yaml
-rw------- 1 root root  501 Mar 16 09:19 kubecfg-kube-controller-manager.yaml
root@localhost:~#
These are the kubecfg files used by various components. Few of the tests have been marked incorrectly thinking they are related to config files.
```
