### ISSUE TITLE
Issues in CIS 1.4 Self Assessment Guide

### ISSUE THREAD

**Issue by sowmyav27** [rancher/docs#2348]
In section: https://rancher.com/docs/rancher/v2.x/en/security/benchmark-2.3/#known-scored-control-failures

- The failed tests have to be updated
- They will differ based on the profile selected now.

The following test have to be marked Not Applicable as per the changes in the KDM
- 1.1.9  - https://rancher.com/docs/rancher/v2.x/en/security/benchmark-2.3/#1-1-9-ensure-that-the-repair-malformed-updates-argument-is-set-to-false-scored
- 1.3.6 - https://rancher.com/docs/rancher/v2.x/en/security/benchmark-2.3/#1-3-6-ensure-that-the-rotatekubeletservercertificate-argument-is-set-to-true-scored
- 2.1.13 - https://rancher.com/docs/rancher/v2.x/en/security/benchmark-2.3/#2-1-13-ensure-that-the-rotatekubeletservercertificate-argument-is-set-to-true-scored
- 2.1.8 - https://rancher.com/docs/rancher/v2.x/en/security/benchmark-2.3/#2-1-8-ensure-that-the-hostname-override-argument-is-not-set-scored

**KDM:** https://releases.rancher.com/kontainer-driver-metadata/dev-v2.4/data.json

**Comment by paraglade** [comment]
PR for documentation updates: https://github.com/rancher/docs/pull/2350

**Comment by catherineluse** [comment]
Closing because https://github.com/rancher/docs/pull/2350 was merged
