### ISSUE TITLE
k3s - update on the air-gap installation instruction 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/docs#2351]
During the validation for this issue: https://github.com/rancher/rancher/issues/25495#issuecomment-598915440

I found there are some improvements we can do for the documentation for k3s air-gap installation: https://rancher.com/docs/k3s/latest/en/installation/airgap/

- [ ] for the section `Prepare Images Directory`, add some explanation for why we still need this when we have a private registry
- [ ] for the section `Create Registry YAML`, add some explanation for when and how the private registry will be used by k3s, why the private registry is not used for k3s' own images
- [ ] for the section `Install K3s`, add a sample command when installing k3s with an external database 
- [ ] the corresponding section in Rancher's documentation under `Installing Rancher in an Air Gapped Environment` also needs to be updated.

**Comment by catherineluse** [comment]
@jiaqiluo The K3s air gap docs were recently updated. https://github.com/rancher/docs/pull/2381 Are there still more improvements that need to be made?

**Comment by btat** [comment]
K3s docs are on a different org/repo now. Created https://github.com/k3s-io/docs/issues/123 there.
