### ISSUE TITLE
Need to update the second diagram in 'How Resource Quotas Work in Rancher Projects'

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#2382]
- url: https://rancher.com/docs/rancher/v2.x/en/project-admin/resource-quotas/quotas-for-projects/

- issue: the second diagram in this page has a minor problem that needs to be fixed. 

- description: in the second diagram, the 'Namespace Default Limit' is 1024 MiB each . There are 4 namespaces in the diagram, which add up to the sum of 4096 MiB as the actual 'Project Default Limit'.  But the diagram shows the 'Project Default Limit' is 2048 MiB instead of 4096 MiB. This might be a bit confusing, to my understanding , the sum of  'Namespace Default Limit' should be equal to or less than 'Project Default Limit'. Otherwise, two or three namespaces could use up all the resources, leaving the other one or two namespaces with no resource to use .
![image](https://user-images.githubusercontent.com/36651058/77494927-1d9f3b80-6e82-11ea-9b09-5bb715dc9d01.png)

**Comment by yzeng25** [comment]
hello @SheilaghM  , are we gonna fix it or not?

**Comment by SheilaghM** [comment]
Yes, we will fix this. Milestone is TBD.

**Comment by lvuch** [comment]
wip how is this looking?
![image](https://user-images.githubusercontent.com/3013118/121435495-d93b7680-c933-11eb-91e4-171dad400f03.png)

**Comment by yzeng25** [comment]
Looks good to me @lvuch

**Comment by lvuch** [comment]
Sent to @SheilaghM via slack

**Comment by SheilaghM** [comment]
LGTM. 
@catherineluse - can you please make sure this gets inserted in the correct space in the documentation?
