### ISSUE TITLE
Secrets are updated automatically

### ISSUE THREAD

**Issue by loganhz** [rancher/docs#2392]
It says Any update to an active secrets won't automatically update the pods that are using it. Restart those pods to have them use the new secret. in our docs https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/secrets/

But it kubernetes docs it says mounted secrets are updated automatically unless you are using it as subpath volume. 

https://kubernetes.io/docs/concepts/configuration/secret/#mounted-secrets-are-updated-automatically

**Comment by catherineluse** [comment]
Closing this issue because it is addressed in this commit https://github.com/rancher/docs/commit/17c2203b9d67217ee4585ca1fde445dbb2ecfefd
