### ISSUE TITLE
rancher-pipeline.yml reference

### ISSUE THREAD

**Issue by dscham** [rancher/docs#2404]
There is no reference for the rancher-pipeline.yml to be found. Yet the docs under https://github.com/rancher/docs/blob/master/content/rancher/v2.x/en/k8s-in-rancher/pipelines/example/_index.md explain there should be one.

There are 2 issues with this.

Generally,
It's probably bad practice to suggest the existence of docs that do not exist. And getting into pipelines is harder for me as a developer looking for config files he can push, rather than a click through tutorial.

For my case,
I can't find a way to schedule a pipeline. So I can only trigger it via commit, or manually. Making nightly builds impossible. Or only doable via some unreliable hack like committing with a script or do an API call every evening.

To solve this I would, update the docs so it doesn't create false hope for something that doesn't exist. (Which cost me a lot of time). And, if there is an option for it, document how to schedule a pipeline via the rancher-pipeline.yml.

**Comment by catherineluse** [comment]
Closing this issue because it addressed by this PR https://github.com/rancher/docs/pull/2419
