### ISSUE TITLE
Clean up ingress page

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#2438]
The instructions on this page left someone unable to reach an endpoint via ingress https://rancher-users.slack.com/archives/C3ASABBD1/p1586446738475800?thread_ts=1586445412.467800&cid=C3ASABBD1

There is configuration reference information mixed in with the instructions, so it's unclear what's optional and what's required or default. Any time it says "if you choose this option," I think that can be separated out into a configuration reference.

https://rancher.com/docs/rancher/v2.x/en/k8s-in-rancher/load-balancers-and-ingress/ingress/

**Comment by btat** [comment]
Resolved as the page has gone through multiple updates since this issue was raised.
