### ISSUE TITLE
Document Prometheus Remote read/write configs

### ISSUE THREAD

**Issue by cloudnautique** [rancher/docs#2439]
We should include these options: https://github.com/rancher/rancher/issues/20624#issuecomment-587981860

In our documentation for Prometheus configuration.

**Comment by ibrokethecloud** [comment]
Related PR: https://github.com/rancher/docs/pull/2531

**Comment by catherineluse** [comment]
Closing this issue because the PR was merged https://github.com/rancher/docs/pull/2531
