### ISSUE TITLE
Need better documentation for importing EKS clusters

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#2441]
When trying to build and import EKS clusters we found the documentation sparse regarding the IAM policies required.  A step by step manual would really be handy here.

**Comment by catherineluse** [comment]
Are these permissions too excessive? https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/#appendix-minimum-eks-permissions

**Comment by catherineluse** [comment]
Closing this issue because the EKS permissions were added to the docs since this issue was opened. The EKS docs were updated for Rancher v2.5. If the step by step manual is still needed, please open a separate issue.
