### ISSUE TITLE
Single node upgrade command is incorrect

### ISSUE THREAD

**Issue by loganhz** [rancher/docs#2443]
https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/single-node/

Some param is missing. like `-p` and `-v` 

![image](https://user-images.githubusercontent.com/21168270/79035512-f2db1400-7bf1-11ea-9e80-cf364ff82f80.png)

**Comment by catherineluse** [comment]
Closing this issue because it has been fixed.
