### ISSUE TITLE
Example expressions are outdated based on Kubernetes version

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#2453]
Someone on Rancher users slack said this section outdated. https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/monitoring/expression/#kubernetes-components-metrics

> `apiserver_request_latencies_sum` doesnt appear available on my 1.17.4 RKE cluster

> `apiserver_request_duration_seconds_bucket|count|sum` are

**Comment by btat** [comment]
First value mentioned is still in the current docs and second can't be found, Closing as versions mentioned are outdated now and original issue description needs more context.
