### ISSUE TITLE
Missing local_cluster_auth_endpoint in Reference Hardened RKE cluster.yml configuration

### ISSUE THREAD

**Issue by nickngch** [rancher/docs#2458]
Missing `local_cluster_auth_endpoint` configuration in the Reference Hardened RKE cluster.yml configuration(https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.3.5/#reference-hardened-rke-cluster-yml-configuration)

The RKE template couldn't load properly on Rancher UI if the `local_cluster_auth_endpoint` is missing.

**Comment by btat** [comment]
No longer maintaining these doc versions.
