### ISSUE TITLE
port requirements page changes

### ISSUE THREAD

**Issue by leodotcloud** [rancher/docs#2472]
1) Information regarding git server

```
git.rancher.io (2):
35.160.43.145:32
35.167.242.46:32
52.33.59.17:32
```

`:32` should be listed as `/32`.

2) Information regarding whitelisting Docker Hub registry access needs to be added.

3) Workload clients -> Workload Clients(Example: Laptops, VPN IP range, etc)

**Comment by catherineluse** [comment]
I checked #1 and it looks like it's already fixed.

Can you please clarify where the change needs to be made for #3?

**Comment by leodotcloud** [comment]
I guess I meant:
Workload Clients(Example: Laptops, VPN IP range, etc) -> port 80, 443 and nodeport range

**Comment by maggieliu** [comment]
@catherineluse To review if these changes are done already or not.
