### ISSUE TITLE
add sample helm command for installing Rancher with self-singed certs from private CA

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/docs#2477]
If we are using a Private CA signed certificate, we need to add `--set privateCA=true` to the helm command. This is mentioned in the documentation, but it is not conspicuous, and it is easy to be missed when users come to the page to copy & paste the sample command. 

<img width="910" alt="Screen Shot 2020-04-29 at 2 49 32 PM" src="https://user-images.githubusercontent.com/6218999/80650547-0cb98b00-8a29-11ea-8416-21e6ff0d0f18.png">

It is better to have one more helm command sample in this section for using private CA. 
```
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=rancher.my.org \
  --set ingress.tls.source=secret \
  --set privateCA=true
```

**Comment by catherineluse** [comment]
Closing this issue because it is addressed in this PR https://github.com/rancher/docs/pull/2485
