### ISSUE TITLE
Monitoring Release Notes 

### ISSUE THREAD

**Issue by leflambeur** [rancher/docs#2480]
As we provide an inbuilt monitoring solution with its own versions some customers have requested formal release notes - often a requirement of internal process mgmt

Let me know if this is the right place for this

**Comment by catherineluse** [comment]
@deniseschannon what do you think of this?

**Comment by leflambeur** [comment]
I know this came up again recently internally with @dnoland1

**Comment by deniseschannon** [comment]
@leflambeur I'm assuming you are talking about monitoring v1?
