### ISSUE TITLE
In the Rancher server docs, the page for custom-clusters is not reachable

### ISSUE THREAD

**Issue by belgaied2** [rancher/docs#2481]
[This page](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/custom-clusters/) shows Error 403.
![image](https://user-images.githubusercontent.com/60746935/80707053-9fb9fa00-8ae9-11ea-8c84-40209fa9c1e2.png)

**Comment by catherineluse** [comment]
Closing this issue because the link redirects to the page now.
