### ISSUE TITLE
Add ingress class option docs to the helm chart

### ISSUE THREAD

**Issue by galal-hussein** [rancher/docs#2483]
A new helm chart option was introduced to specify the class of the ingress https://github.com/rancher/rancher/pull/26870

this should be documented for the user to be able to use different ingresses

**Comment by catherineluse** [comment]
related issue #2976

**Comment by catherineluse** [comment]
Closing because the ingress class option is now documented in the Helm chart options page

> | `letsEncrypt.ingress.class`    | ""                                                    | `string` - optional ingress class for the cert-manager acmesolver ingress that responds to the Let's Encrypt ACME challenges. Options: traefik, nginx.                      |
