### ISSUE TITLE
expandable sections wont expand in Networking Requirements

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#2492]
https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/node-requirements/#networking-requirements/
Accordion sections are not working for me on the following browsers with noscript turned off
Firefox 75.0 (64-bit) apt package
Firefox 75.0 (64-bit) snap
Chromium Version 81.0.4044.129 (Official Build) snap (64-bit)

**Comment by catherineluse** [comment]
fixed https://github.com/rancher/docs/commit/fedbf354f3a1e13a098e9789d7b260afac39ed87
