### ISSUE TITLE
rancherOS in the docs - comment on EOL coming soon

### ISSUE THREAD

**Issue by vrms** [rancher/docs#2508]
I learned in a rancher online event that rancherOS is about to reach it's EOL.
I suggest to add a prominent comment about this to:

1. the [documentation](https://github.com/rancher/docs/blob/master/content/os/v1.x/en/_index.md
) and 
2. [the README of rancherOS](https://github.com/rancher/os/blob/master/README.md) 

I would provide a PR, but am not aware of the detailed schedule for this.

**Comment by SimonHeimberg** [comment]
Maybe do not list RancherOS in
 * rancher/v2.x/en/installation/requirements/_index.md (https://rancher.com/docs/rancher/v2.x/en/installation/requirements/)
 * rancher/v2.x/en/cluster-provisioning/node-requirements/_index.md (https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/node-requirements/)

related https://github.com/rancher/os/issues/3000

**Comment by bd8392** [comment]
Will there be rancher-os 3?

**Comment by vrms** [comment]
> Will there be rancher-os 3? Because it's the best operating system I've ever head!

as far as I understand the matter, no (that's why I have opened this issue)

**Comment by elsbrock** [comment]
Too bad I only found out now. I agree this should be made more transparent.

**Comment by bd8392** [comment]
Yes...is there any similar system I can upgrade to? Because I just started to use it on all my servers...

**Comment by olljanat** [comment]
FYI. We have now BurmillaOS release candidate which is compatible with RancherOS and to where users can directly upgrade. Anyone who is interested please checkout release notes, test your configuration and report bugs if found any so we can fix those to release version: https://github.com/burmilla/os/releases/tag/v1.9.0-rc1

**Comment by SimonHeimberg** [comment]
There is one link remaining which does not mention EOL:
>     2. [the README of rancherOS](https://github.com/rancher/os/blob/master/README.md)

The other 3 links (listed in the summary or the 1st comment) are updated :+1:
