### ISSUE TITLE
[RKE] minimum CPU/Memory requirements

### ISSUE THREAD

**Issue by dkeightley** [rancher/docs#2529]
For Rancher and k3s we document the minimum resource requirements, currently RKE doesn't state a minimum.

It's difficult to cater for all environments, however having a minimum of CPU/mem that is at least required to run a minimal cluster with docker, k8s components, and addons that are deployed with RKE.

**Comment by raelix** [comment]
Hello everyone, i just found this open issue, I’m trying to find the min. requirements for RKE but without success. Is there an update for this? Any useful suggestions?

Thanks in advance.

**Comment by superseb** [comment]
The requirements in the Rancher docs here https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/node-requirements/ describe how to size your nodes for Kubernetes.

**Comment by raelix** [comment]
Thanks a lot @superseb i saw them but unfortunately those are related to RKE nodes including Rancher not to an RKE downstream cluster. Do you know if this information is available somewhere?

Thanks a lot in advance

**Comment by raelix** [comment]
Thanks a lot @superseb i saw it. Thank you very much

**Comment by raelix** [comment]
Just last question, the doc talks about worker role, are there any other information regards the etcd and control-plane node?

Thank you

**Comment by superseb** [comment]
etcd is linked in the docs: https://etcd.io/docs/v3.4.0/op-guide/hardware/

The `building large clusters` used to have indications for resource requirements as far as I know but it's not there anymore, we should probably change the link or describe it ourselves. For now I would just follow RKE install requirements from here https://rancher.com/docs/rancher/v2.x/en/installation/requirements/ and monitor resource usage.
