### ISSUE TITLE
Rancher Catalog IP no more accurate

### ISSUE THREAD

**Issue by rtau** [rancher/docs#2540]
In https://rancher.com/docs/rancher/v2.x/en/installation/requirements/ports/#rancher-nodes, which asked us to whitelist several IP address for accessing "Rancher catalog (git.rancher.io)", the list of IP addresses, "35.160.43.145,35.167.242.46,52.33.59.17", does not match that resolved at the moment, which is:
git.rancher.io.		279	IN	CNAME	ext-services-lb-2a685576fdf664e2.elb.us-west-2.amazonaws.com.
ext-services-lb-2a685576fdf664e2.elb.us-west-2.amazonaws.com. 39 IN A 34.208.213.149
ext-services-lb-2a685576fdf664e2.elb.us-west-2.amazonaws.com. 39 IN A 52.36.54.134

In general, I am wondering if such IP address whitelist is possible with AWS ELB.

**Comment by catherineluse** [comment]
After discussion with David Noland, it sounds like we'll make these changes:

Everywhere that it says

```
 git.rancher.io (2):
35.160.43.145:32
35.167.242.46:32
52.33.59.17:32
```

needs to be simply
```
 git.rancher.io
```

We'll say “Rancher catalog” and drop the git.rancher.io so it doesn’t look redundant.
