### ISSUE TITLE
Missing Supported cloud providers

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#2543]
**Steps to reproduce (least amount of steps as possible):**

1. visit https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/cloud-providers/
2. look at the sentence under the first paragraph:"Supported cloud providers are:"
3. compare the cloud provider listed on this page and those listed in the catalog, you can see that "Amazon" and "Azure" are listed on the catalog and in the page. But Google Compute Engine is missing on the page.

**Result:**
Google Compute Engine is missing on the page.

**Other details that may be helpful:**
url: https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/cloud-providers/
fix recommendation: add a bullet point under "Amazon" and "Azure" would fix it.

**Comment by catherineluse** [comment]
Closing this issue because it is addressed in this commit https://github.com/rancher/docs/commit/978e1ed3143672c0bf79b936598735ad53033416
