### ISSUE TITLE
Would be good to have a copy button for the resources on the Istio Add Deployments page

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#2544]
https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/istio/setup/deploy-workloads/#resource-yaml

This page features a large text block with many YAML manifests the user must copy and paste into their cluster.  It would benefit usability to have a "Copy to Clipboard" button at the top and bottom of this manifest (it's long...)

**Comment by Tejeev** [comment]
https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/istio/setup/gateway/
This one too

**Comment by catherineluse** [comment]
this is the same as https://github.com/rancher/docs/issues/488

@StrongMonkey Are you still working on this?

**Comment by StrongMonkey** [comment]
I would like to. Can find a time to contribute :)

**Comment by catherineluse** [comment]
Ok. If you could work on it, I would appreciate it. That would be really awesome. But if you don't have time, no worries.

**Comment by btat** [comment]
Closing a duplicate of https://github.com/rancher/docs/issues/488
