### ISSUE TITLE
Invalid link on RKE "How Upgrades Work" page

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#2573]
URL: https://rancher.com/docs/rke/latest/en/upgrades/how-upgrades-work

Issue: The link in the last section/paragraph of RKE v1.1.0+ "or more information on configuring the number of replicas for each addon, refer to  **this section**" does not lead to a useful place.

Expect result: This link should jump to somewhere that has specific instructions/examples of configuring RKE Add-ons.

Actual result: This link jumps to the exact same page.

Suggestion: My guess is that specific instructions/examples used to be on this page, but later moved to https://rancher.com/docs/rke/latest/en/config-options/add-ons/. It would be more helpful if this link were changed to redirect users to visit this page.

**Comment by catherineluse** [comment]
I had intended the link to go here https://rancher.com/docs/rke/latest/en/upgrades/configuring-strategy/#replicas-for-ingress-and-networking-addons

I have fixed it in this commit https://github.com/rancher/docs/commit/cbfa213502a7ba558aed4f474264ba02c16aab80
