### ISSUE TITLE
Controversial description on RKE "How Upgrades Work" page

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#2574]
URL: https://rancher.com/docs/rke/latest/en/upgrades/how-upgrades-work/

Issue: In "RKE prior to v1.1.0" tab, there is a bullet point says "Controlplane nodes get updated second, one at a time.", yet the paragraph says "Controlplane and etcd nodes would be upgraded in batches of 50 nodes or the total number of controlplane nodes, whichever is lower."

Question: which description is correct?

**Comment by catherineluse** [comment]
The sentence "Controlplane and etcd nodes would be upgraded in batches of 50 nodes or the total number of controlplane nodes, whichever is lower." applies to RKE prior to v1.1.0.

I have made the correction in this commit https://github.com/rancher/docs/commit/2112fa0eea0b6ef16a958c55b0a7135d4a949970
