### ISSUE TITLE
Cluster Administration Table links to 404 pages and duplications of the same contents in the bottom section of this page.

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#2577]
URL: https://rancher.com/docs/rancher/v2.x/en/cluster-admin/

Issue 1: Cluster Administration Table links to 404 pages. The first column of the table on this page are links, but all of them fail to link to valid pages.

Issue 2: Duplications of the same contents in the bottom section of this page. The same contents of table appear in the bottom section of this page without correct formatting.

**Comment by superseb** [comment]
I guess this is related to https://github.com/rancher/docs/pull/2571, @bashofmann can you check?

**Comment by bashofmann** [comment]
Will look at it asap

**Comment by bashofmann** [comment]
@superseb https://github.com/rancher/docs/pull/2585 fixes both issues for me. Learnt a bit about how hugo page bundles work.
