### ISSUE TITLE
Incorrect version of RKE on One-time Snapshots page

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#2589]
- URL: https://rancher.com/docs/rke/latest/en/etcd-snapshots/one-time-snapshots/

- Steps to reproduce: 
1. visit the url listed above
2. select the "RKE 0.2.0+" tab
3. scroll down to the "Using a custom CA certificate for S3" topic, where it says "Available as of v2.2.5"

- Expected Result: list the version number of RKE.

- Actual Result: the version number now listed on the page is clearly not a valid RKE version, since the latest RKE version is 1.1.x.

- Suggestion: I checked RKE release notes, **the correct version should be 0.2.0**.  If you would like to double check, the link is here: https://github.com/rancher/rke/releases/tag/v0.2.0

**Comment by yzeng25** [comment]
Another typo:

"If the S3 backend uses a self-signed or custom certificate, provide a custom certificate using the --s3-endpoint-ca to connect to the S3 **back end**"

”back end“ --> "backend"

**Comment by catherineluse** [comment]
Closing this issue because it is addressed in this commit https://github.com/rancher/docs/commit/f626c4e389ce86e7e1419f2d6e6cca130456e405

Also fixed the typo.
