### ISSUE TITLE
Fix Rancher HA disaster recovery documentation

### ISSUE THREAD

**Issue by janeczku** [rancher/docs#2590]
**Problem**

By following the [HA restore documentation](https://rancher.com/docs/rancher/v2.x/en/backups/restorations/ha-restoration/) a user will not be able to successfully restore an RKE-based Rancher HA cluster.

The following error will occur while running the restore command:

```
FATA[0012] failed to start backup server on all etcd nodes: [Failed to run backup server container, container logs: time="2020-07-07T15:09:46Z" level=fatal msg="open /etc/kubernetes/ssl/kube-ca.pem: no such file or directory"
```

**Solution**

Overhaul the complete documentation  for the disaster recovery procedure and fix incorrect and redundant instructions, including:

> Modify the copy and make the following changes.
> Use RKE with the new rancher-cluster-restore.yml configuration and restore the database to the single “target node”.

This results in the restore to fail, because rke will create an empty rkestate file and will lack the certificate of the existing cluster. Instead the user should be instructed to backup  `rancher-cluster.yml` and ` rancher-cluster.rkestate` but then modify and work with the **original** files.

> Comment out the nodes that are not your “target node”. We want the cluster to only start on that one node.

This is not necessary anymore (per @bashofmann). The snapshot restore can be done using a config that includes all cluster nodes. See also RKE documentation. 

> RKE will create an etcd container with the restored database on the target node. This container will not complete the etcd initialization and stay in a running state until the cluster brought up in the next step.

This is incorrect. Running the `rke etcd snapshot-restore` command will yield a fully functional cluster.

> Use RKE and bring up the cluster on the single “target node.”

This is not necessary. Running `rke etcd snapshot-restore` command will **implicitly** bring up the cluster and restart all system pods. See RKE documentation (`The following actions will be performed when you run the command`): https://rancher.com/docs/rke/latest/en/etcd-snapshots/restoring-from-backup/
```

**Comment by catherineluse** [comment]
Closing this issue because it is addressed in this PR https://github.com/rancher/docs/pull/2594
