### ISSUE TITLE
RKE Backups and Disaster Recovery Example Scenarios missing a figure

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#2596]
URL: https://rancher.com/docs/rke/latest/en/etcd-snapshots/example-scenarios/#1-back-up-the-cluster

Issue:  Under "1. Back Up the Cluster", the figure is not showing up as expected.

Expected Result: the expected figure should be this one: **/img/rke/rke-etcd-backup.png**, but it seems like the way of referencing to this path is not recognizable by hugo.

**Comment by yzeng25** [comment]
Both of ”RKE V0.2.0+“ tab and “RKE PRIOR TO V0.2.0” tab have the same problem.

**Comment by catherineluse** [comment]
I don't see the reference to the file, or the file itself anymore. But I think that's okay because I believe the section already looks fine without the image. Denise also said we are moving away from screenshots because they are hard to maintain, so I think that it's fine as-is.
