### ISSUE TITLE
Add steps to update SSL certs for Rancher HA install

### ISSUE THREAD

**Issue by leodotcloud** [rancher/docs#260]

**Comment by catherineluse** [comment]
@leodotcloud is this about certificate rotation? if so, should we close the issue because it's already documented? https://rancher.com/docs/rancher/v2.x/en/cluster-admin/certificate-rotation/

**Comment by divya-mohan0209** [comment]
@SheilaghM : Just following up on this, do we need this to be open or has this been documented?

**Comment by catherineluse** [comment]
I think this has already been documented here: https://rancher.com/docs/rancher/v2.5/en/installation/resources/update-ca-cert/

**Comment by divya-mohan0209** [comment]
@catherineluse - good to close this then? Or would you be aware if I need to reach out to anyone for confirmation on this?

**Comment by catherineluse** [comment]
I would say it is OK to close.

**Comment by divya-mohan0209** [comment]
Closing this off per comment above.
