### ISSUE TITLE
Enable/use logging

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#2608]
The new logging docs are a work in progress at this page:
https://staging.rancher.com/docs/rancher/v2.x/en/logging/ (updated link on August 28)

For logging we still need details of: 

1. How to configure the logging output when you install Rancher as a helm chart
2. How to configure the logging output when you install Rancher using the Rancher CLI
3. How to enable logging for Rancher managed clusters
4. How to configure the logging application (not step by step, this would be essentially a reference for the custom resource options)

Edit: We should add that we don't support syslog.

**Comment by paynejacob** [comment]
There is a typo in "Changes in Rancher v2.5"  "Rancher’s logging feature is now powered the Banzai Cloud Logging operator instead..." -> "Rancher’s logging feature is now powered by the Banzai Cloud Logging operator instead..."

**Comment by paynejacob** [comment]
for the "Configuring the Logging Output for the Rancher Kubernetes Cluster" section, we have changed how the logging ui will work.  Users won't configure outputs from the chart install, they will be able to select additional logs to collect and any outputs and flows will be configured through separate crd pages.

**Comment by paynejacob** [comment]
We should include an example for forwarding to another fluentd.  This is useful when users want a feature we don't currently support.

**Comment by cbron** [comment]
Need to doc that windows support isn't in yet
