### ISSUE TITLE
Update HA Install page with following requests

### ISSUE THREAD

**Issue by leodotcloud** [rancher/docs#261]
Link: https://rancher.com/docs/rancher/v2.x/en/installation/ha-server-install

When setting up HA, there can be multiple options for loadbalancer.
Currently we have steps for Nginx.
- Need to add steps for Amazon NLB (Network Load Balancer)
    - NLB with private option doesn't work outside of VPC (Add this as caveat)
    - NLB requires two availability zones. (Need to update HA install docs to specify how to spread the rancher rke mgmt nodes across multiple AZs)

What considerations need to be taken when deploying HA?
RKE provides functionality to do etcd snapshots ... do we need to add EBS volumes to the RKE nodes?

**Comment by deniseschannon** [comment]
Available: https://rancher.com/docs/rancher/v2.x/en/installation/ha/create-nodes-lb/nlb/
