### ISSUE TITLE
Custom Cluster docs are missing the requirements regarding node roles

### ISSUE THREAD

**Issue by janeczku** [rancher/docs#2611]
With regards to configuring node roles the documentation merely states:
> From Node Role, choose the roles that you want filled by a cluster node.
https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/custom-nodes/

There should be an explanation of the roles (possibly via a link) and it should be called out that at least one node must be configured for etcd and control plane (since the GUI default to generating a worker node command).

> You must provision at least one node with the `etcd` and `control plane` roles.

**Comment by dramich** [comment]
The docs should clarify that all three roles are required for a custom cluster to finish provisioning. If a worker node is not added the cluster will never finish.
