### ISSUE TITLE
404 link on "Prometheus Custom Metrics Adapter" page

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#2626]
URL: https://rancher.com/docs/rancher/v2.x/en/cluster-admin/tools/monitoring/custom-metrics/

Broken Link: "A more comprehensive configuration file can be found in **sample-config.yaml**, but a basic config with one rule might look like..."

**Comment by catherineluse** [comment]
Closing this issue because I added a redirect for that URL and I don't think the broken link text is in the docs anymore.
