### ISSUE TITLE
Update docs for Rancher 2.5 installation

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#2640]
- Talk about installing the Rancher binary and using the Rancher CLI to set up the Rancher server Kubernetes cluster
- Reorganize installation docs - Regardless of the installation option you have to pick the Rancher version and Helm chart options
- Add new installation pages for installing Rancher on EKS, AKS, GKE and any other kubernetes cluster)

**Comment by maggieliu** [comment]
Closing this in favor of https://github.com/rancher/docs/issues/2677
