### ISSUE TITLE
Updating navigation for tools

### ISSUE THREAD

**Issue by deniseschannon** [rancher/docs#2649]
- [x] Backup and Restore needs to move to the new helm chart method. Move old docs for backups and disaster recovery under "Legacy

- [x] Move v2 tool to a top level nav link
- [x] Under "Legacy" move all cluster level and project level links

For these tools:
New Tool - Monitoring/Alerting
Old Tool - 
  - [x] Monitoring (Cluster, Project)
  - [x] Alerts (Cluster, Project)
  - [x] Notifiers (Cluster)

Example Nav:
```
Monitoring/Alerting
  - Legacy 
      - Monitoring
         - Cluster Level
         - Project Level
      - Alerts
         - Cluster Level
         - Project Level
      - Notifiers
```

New Tool - Istio
Old Tool 
   - [x] Istio (Cluster)

New Tool - Logging
Old Tool 
  - [x] Logging (Cluster, Project)

New Tool - CIS Scans
Old Tool 
  - [x] CIS Scans (Cluster)

New Heading - Applications across Clusters
Old Tool
 -  [x] Multi-Cluster App (Global)

New Heading - Helm Charts in Rancher
Legacy
  - [x] Catalogs (Global, Cluster, Project)

**Comment by catherineluse** [comment]
Closing this issue because I finished organizing the staging branch
