### ISSUE TITLE
Update structure for old Hardening Guide

### ISSUE THREAD

**Issue by deniseschannon** [rancher/docs#2651]
With 2.5, we are increasing the guide from providing guidance on a RKE1 cluster to all Rancher k8s distros.
Currently, we have a link for each Hardening Guide and each Self Assessment Guide. 
<img width="235" alt="Screen Shot 2020-08-24 at 10 35 08 PM" src="https://user-images.githubusercontent.com/11410997/91126993-22972f80-e65a-11ea-998e-48d562713ed8.png">

To prep for it, let's first clean up the old hardening guide to this format:
```
- Rancher v2.4 - new page that should summarize the versions used and then links to the individual guides explaining the hardening guide will explain how to harden your Rancher v2.4 clusters and the self assessment guide will give you the report for how we score on every bench mark. 
  - Hardening Guide
  - Self Assessment Guide
- Rancher v2.3
   - Rancher v2.3.5
       - Hardening Guide
       - Self Assessment Guide
   - Rancher v2.3.3
       - Hardening Guide
       - Self Assessment Guide
   - Rancher v2.3.0
       - Hardening Guide
       - Self Assessment Guide
- Rancher v2.2
  - Hardening Guide
  - Self Assessment Guide
- Rancher v2.1
  - Hardening Guide
  - Self Assessment Guide
```

**Comment by catherineluse** [comment]
closing this issue because https://github.com/rancher/docs/pull/2713 is merged
