### ISSUE TITLE
Contents are displayed improperly in "Creating an Azure Cluster" page

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#2656]
URL: https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/node-pools/azure/
Issue: after the most recent commit (https://github.com/rancher/docs/commit/64b01f69448f2658411ebad668d371c94f7c201e), page content are displayed improperly.
![image](https://user-images.githubusercontent.com/36651058/91710387-bf0b8580-ebb6-11ea-9974-93ea48bd73ba.png)

@catherineluse

**Comment by catherineluse** [comment]
this issue is addressed by this commit https://github.com/rancher/docs/commit/10a345c1f528c6ee268ce0a79a765eac71f9e123
