### ISSUE TITLE
[CIS v2] Documentation for cis-operator

### ISSUE THREAD

**Issue by prachidamle** [rancher/docs#2658]
We need to document the upcoming CIS v2 changes. 

The feature overview., CRD  and user flow explanation is available here:
https://rancher.atlassian.net/wiki/spaces/EN/pages/687210583/CIS+v2+Overview+CRD+Design+and+UserFlow

The structure will be similar to what's in the above linked document:

- Overview
- CRD explanations
  - ClusterScanBenchmark
  - ClusterScanProfile
  - ClusterScan
  - ClusterScanReport
- How to install the Helm chart
- How to run a scan
- How to view a scan report
- How to see all scans
- How to skip tests

We also need to include details from this issue https://github.com/rancher/dashboard/issues/1072

**Comment by prachidamle** [comment]
@catherineluse here is some more info helpful to document: https://github.com/rancher/dashboard/issues/1072

Especially the CRD relational model, Overview description etc.

**Comment by catherineluse** [comment]
Closing this issue because docs are in staging https://github.com/rancher/docs/pull/2728
