### ISSUE TITLE
Document Windows Prefix RKE Cluster YAML Additions

### ISSUE THREAD

**Issue by luthermonson** [rancher/docs#2659]
Based on this issue https://github.com/rancher/rancher/issues/28507 which links to 3 issues coalesced into one concept of new `win_` prefixed params in RKE cluster yaml. There are 4 total, 3 service level binds for env/args/binds and 1 cluster level for prefix path.

**Comment by btat** [comment]
Closing as per https://github.com/rancher/docs/pull/3059#issuecomment-1176515770.
