### ISSUE TITLE
Update air gap installation docs for Rancher 2.5 installs with rancherd

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#2672]
Catherine to follow up with @davidnuzik to find out how Rancherd can be installed in an air gap environment

Denise also said we should include this change:

> As part of air gap docs, we also need a note that specifies if you are connecting to an external service through alertmanager or logging, the external service needs to be reachable from the cluster running the tool

**Comment by davidnuzik** [comment]
Note, tracking for rancherd implementation is here: https://github.com/rancher/rancher/issues/28131 presently there is no rancherd binary/release to work with. Presently standing by for rancherd to be completed.

**Comment by catherineluse** [comment]
Removing the staging label because rancherd is not being documented for Rancher v2.5

**Comment by catherineluse** [comment]
Closing in favor of #2826
