### ISSUE TITLE
Rancherd installation, uninstallation, upgrade and configuration

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#2677]
Rancherd is being tracked here https://github.com/rancher/rancher/issues/28131
and the air gap install docs are being tracked here https://github.com/rancher/docs/issues/2672

Catherine to ask Craig for help when it is ready to be documented

**Comment by catherineluse** [comment]
Removing the staging label because rancherd is not being documented in Rancher v2.5.0

**Comment by maggieliu** [comment]
Installation, uninstallation, upgrade and configuration reference.

**Comment by catherineluse** [comment]
Closing because https://github.com/rancher/docs/pull/2947 was merged
