### ISSUE TITLE
Improve vsphere doc page

### ISSUE THREAD

**Issue by leodotcloud** [rancher/docs#268]
We need to expand more on this page: `https://rancher.com/docs/rancher/v2.x/en/tasks/clusters/creating-a-cluster/create-cluster-vsphere/`

Something like: `https://blogs.vmware.com/cloudnative/2016/02/17/how-to-use-docker-machine-in-conjunction-with-vsphere-driver`

**Comment by aemneina** [comment]
https://www.koding.com/docs/terraform/providers/vsphere/index.html/ this too!

**Comment by olljanat** [comment]
FYI. There is now **#vsphere** channel on [Rancher Users](https://slack.rancher.io/) slack where we are discussing about this topic and target is share working configs on here.

**Comment by deniseschannon** [comment]
Expanded the docs and already live: https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/node-pools/vsphere/
