### ISSUE TITLE
Document permissions/requirements for creating EKS clusters in Rancher 2.5

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#2688]
These questions come from Bill's feedback on this PR about the new EKS provisioning docs https://github.com/rancher/docs/pull/2674 and this issue about documenting the EKS changes. https://github.com/rancher/docs/issues/2639

- What network requirements are needed for Rancher to access the EKS cluster with private access?
- How do you use eksctl to add the Rancher cloud credential to the aws-auth configmap as a cluster admin, and how do you bind the user to `system:masters` group?
- What's the kubectl command to launch the Rancher agent on an EKS cluster? (we've only previously documented the Docker command)
- What is the minimum IAM permissions policy for the Rancher service role?
- Does the IAM policy need permission to see the KMS key if you want to encrypt secrets?
- Does the IAM policy need permission to send logs to Amazon CloudWatch? or is that included in the Rancher default policy?

**Comment by cloudnautique** [comment]
Opened up an issue for this: rancherlabs/eio#265

**Comment by Sheldonwl** [comment]
@cloudnautique I also had a ticket open for those permissions: https://github.com/rancherlabs/eio/issues/257
Ended up using the minimum requirements listed in our docs (https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/eks/), but had to add a couple more; ec2:ModifySubnetAttribute and kms:ListKeys.  
  
This is the full list I have now: 

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "EC2Permisssions",
            "Effect": "Allow",
            "Action": [
                "ec2:AuthorizeSecurityGroupIngress",
                "ec2:DeleteSubnet",
                "ec2:CreateKeyPair",
                "ec2:AttachInternetGateway",
                "ec2:ReplaceRoute",
                "ec2:DeleteRouteTable",
                "ec2:AssociateRouteTable",
                "ec2:DescribeInternetGateways",
                "ec2:CreateRoute",
                "ec2:CreateInternetGateway",
                "ec2:RevokeSecurityGroupEgress",
                "ec2:DescribeAccountAttributes",
                "ec2:DeleteInternetGateway",
                "ec2:DescribeKeyPairs",
                "ec2:CreateTags",
                "ec2:CreateRouteTable",
                "ec2:DescribeRouteTables",
                "ec2:DetachInternetGateway",
                "ec2:DisassociateRouteTable",
                "ec2:RevokeSecurityGroupIngress",
                "ec2:DeleteVpc",
                "ec2:CreateSubnet",
                "ec2:DescribeSubnets",
                "ec2:DeleteKeyPair",
                "ec2:DeleteTags",
                "ec2:CreateVpc",
                "ec2:DescribeAvailabilityZones",
                "ec2:CreateSecurityGroup",
                "ec2:ModifyVpcAttribute",
                "ec2:AuthorizeSecurityGroupEgress",
                "ec2:DescribeTags",
                "ec2:DeleteRoute",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeImages",
                "ec2:DescribeVpcs",
                "ec2:DeleteSecurityGroup",
                "ec2:ModifySubnetAttribute"
            ],
            "Resource": "*"
        },
        {
            "Sid": "EKSPermissions",
            "Effect": "Allow",
            "Action": [
                "eks:DeleteFargateProfile",
                "eks:DescribeFargateProfile",
                "eks:ListTagsForResource",
                "eks:UpdateClusterConfig",
                "eks:DescribeNodegroup",
                "eks:ListNodegroups",
                "eks:DeleteCluster",
                "eks:CreateFargateProfile",
                "eks:DeleteNodegroup",
                "eks:UpdateNodegroupConfig",
                "eks:DescribeCluster",
                "eks:ListClusters",
                "eks:UpdateClusterVersion",
                "eks:UpdateNodegroupVersion",
                "eks:ListUpdates",
                "eks:CreateCluster",
                "eks:UntagResource",
                "eks:CreateNodegroup",
                "eks:ListFargateProfiles",
                "eks:DescribeUpdate",
                "eks:TagResource"
            ],
            "Resource": "*"
        },
        {
            "Sid": "IAMPermissions",
            "Effect": "Allow",
            "Action": [
                "iam:ListRoleTags",
                "iam:RemoveRoleFromInstanceProfile",
                "iam:CreateRole",
                "iam:AttachRolePolicy",
                "iam:AddRoleToInstanceProfile",
                "iam:DetachRolePolicy",
                "iam:GetRole",
                "iam:DeleteRole",
                "iam:CreateInstanceProfile",
                "iam:ListInstanceProfilesForRole",
                "iam:PassRole",
                "iam:GetInstanceProfile",
                "iam:ListRoles",
                "iam:ListInstanceProfiles",
                "iam:DeleteInstanceProfile"
            ],
            "Resource": "*"
        },
        {
            "Sid": "CloudFormationPermisssions",
            "Effect": "Allow",
            "Action": [
                "cloudformation:DescribeStackResource",
                "cloudformation:ListStackResources",
                "cloudformation:DescribeStackResources",
                "cloudformation:DescribeStacks",
                "cloudformation:ListStacks",
                "cloudformation:CreateStack",
                "cloudformation:DeleteStack"
            ],
            "Resource": "*"
        },
        {
            "Sid": "AutoScalingPermissions",
            "Effect": "Allow",
            "Action": [
                "autoscaling:DescribeAutoScalingGroups",
                "autoscaling:UpdateAutoScalingGroup",
                "autoscaling:TerminateInstanceInAutoScalingGroup",
                "autoscaling:CreateOrUpdateTags",
                "autoscaling:DeleteAutoScalingGroup",
                "autoscaling:CreateAutoScalingGroup",
                "autoscaling:DescribeAutoScalingInstances",
                "autoscaling:DescribeLaunchConfigurations",
                "autoscaling:DescribeScalingActivities",
                "autoscaling:CreateLaunchConfiguration",
                "autoscaling:DeleteLaunchConfiguration"
            ],
            "Resource": "*"
        },
        {
            "Sid": "KMSPermissions",
            "Effect": "Allow",
            "Action": "kms:ListKeys",
            "Resource": "*"
        }
    ]
}
```
I believe these are necessary for Rancher to be able to create EKS clusters in 2.5.x. I have not removed anything from the existing minimum permissions list from the docs. Do I need to try to trim that down as well, for ABSA? It's a very trial and error based process, so if anyone has any tips on how to test this in an easier way, please let me know.

**Comment by Sheldonwl** [comment]
What network requirements are needed for Rancher to access the EKS cluster with private access?
https://docs.aws.amazon.com/eks/latest/userguide/cluster-endpoint.html#private-access  
- Connected network: https://docs.aws.amazon.com/whitepapers/latest/aws-vpc-connectivity-options/introduction.html
- Amazon EC2 bastion host  
- AWS Cloud9 IDE

**Comment by Sheldonwl** [comment]
**Does the IAM policy need permission to see the KMS key if you want to encrypt secrets?**  

Yes, the "kms:ListKeys" policy needs to be added, or else you will get an error while filling in the template whilst creating the cluster. At the option "Secrets Encryption", there is no issue as long as "None" is selected, but when choosing "KMS Key: Select or Enter KMS Key that will be used to encrypt secrets", you will see the following warning:   

![image](https://user-images.githubusercontent.com/6817520/94374100-3bd44580-010a-11eb-87e0-fb65c607b91d.png)

**Comment by Sheldonwl** [comment]
**Does the IAM policy need permission to send logs to Amazon CloudWatch? or is that included in the Rancher default policy?**  

No extra permissions needed, this is included in the minimum policies listed above. I was able to enable the options listed below without any issues and validated that the logs were available in Cloudwatch.  

![image](https://user-images.githubusercontent.com/6817520/94374761-b010e800-010e-11eb-8b98-9e409aad58ba.png)

**Comment by cloudnautique** [comment]
We need this broken down a bit more. If the user were to provision the VPC/Subnets and IAM policies ahead of time what would the required permissions be in the EKS policy?

 Ideally, is there a policy where the IAM ACLs are limited to list/attach/detach capabilities, and could that be tied to specific ARNs? Most organizations are not going to want to give create/delete/attach role capabilities.

**Comment by catherineluse** [comment]
@cloudnautique I'm trying to make sense of what still needs to be done to close this issue. Does anything else still need to be documented?

**Comment by SheilaghM** [comment]
Taken care of by eio.
