### ISSUE TITLE
Upgrade scenario when local cluster is disabled

### ISSUE THREAD

**Issue by maggieliu** [rancher/docs#2693]
Need to include upgrade scenario when existing Rancher setup has addLocal=off. This flag will need to be true else there will be a warning. A new [restricted admin role](https://github.com/rancher/rancher/issues/28977) should be used to give to users that need to have access to all downstream clusters instead of the global admin role. 

- Hardening Guide should not recommend the removal of local cluster
- Best Practices should not recommend the removal of local cluster

**Comment by dnoland1** [comment]
Also should remove the option from https://rancher.com/docs/rancher/v2.x/en/installation/options/helm2/helm-rancher/chart-options/#advanced-options or at least mention it has been removed as of v2.5.0

**Comment by cbron** [comment]
@cloudnautique / @dramich on hardening guide, should we instead recommend them to use the restricted admin role ? I'm not sure if that makes sense.

**Comment by dramich** [comment]
If the rancher cluster is already created and we force local any global admin would have full access so they would probably want to switch over to the new restricted-admin. In a fresh install they could set the new flag to force the bootstrapped admin to be restricted-admin, never creating that full global admin.

**Comment by dnoland1** [comment]
What will be the process for moving a 2.4 cluster with local cluster disabled to 2.5 with local cluster enabled and changing admin to a restricted admin?

**Comment by cloudnautique** [comment]
@cbron Yes, I think that makes sense assuming that is our recommended path forward.

**Comment by maggieliu** [comment]
Found this place in the hardening guide that should be updated under "Audit" https://rancher.com/docs/rancher/v2.x/en/security/hardening-2.1/#3-1-rancher-management-control-plane-installation

**Comment by catherineluse** [comment]
Closing this issue because we captured that you should drop the addLocal flag when upgrading to Rancher v2.5 https://github.com/rancher/docs/issues/2693
