### ISSUE TITLE
No Upgrade path from the old experimental OPA to to the new chart

### ISSUE THREAD

**Issue by maggieliu** [rancher/docs#2696]
Need to note that there is no direct upgrade path from the experimental version to the GA. User need to uninstall the old chart and reinstall the new chart.

To uninstall the old chart, user should go into the ember UI, in the System project, under apps. Deleting from 2.5 dashboard will cause a problem: https://github.com/rancher/rancher/issues/29188

**Comment by catherineluse** [comment]
Closing this issue because it is documented on this page https://staging.rancher.com/docs/rancher/v2.x/en/opa-gatekeper/
