### ISSUE TITLE
Need to update docs on Firewalld with Calico

### ISSUE THREAD

**Issue by maggieliu** [rancher/docs#2697]
Firewalld does not work with Calico
Details here: https://github.com/rancher/rancher/issues/28840#issuecomment-693022222

**Comment by catherineluse** [comment]
@maggieliu Chris Kim said we should still add the correct set of rules that are needed to allow firewalld to work in synergy with the network providers that are supported on Kubernetes 1.19, but the changes in this PR https://github.com/rancher/docs/pull/2739 are sufficient for documentation for today.

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/2739 is merged
The follow-up issue is https://github.com/rancher/docs/issues/2740
