### ISSUE TITLE
Need documentation on the Rancher specific “Resources” that are listed in the dropdown when creating Project Roles. 

### ISSUE THREAD

**Issue by ansilh** [rancher/docs#2698]
Need documentation on the Rancher specific “Resources” that are listed in the dropdown when creating Project Roles. 
The native K8s objects like pods, daemonsets, and deployments are self-explanatory, but Rancher specific resources like bindings, opas, pipelines, rbacs are not.  There’s even something called “kuberneteses” (!?). 
Need this info to lock down permissions as much as possible, but has no idea what some of these resources are and the impact of granting or not granting them will be. 

![image](https://user-images.githubusercontent.com/468462/94038062-e2bb8900-fd7a-11ea-805b-7693947921d7.png)

gz#12301
SURE-2434

**Comment by sirredbeard** [comment]
JIRA https://jira.suse.com/browse/SURE-2434?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by jtravee** [comment]
Closing issue and referring to UI. UI should filter out deprecated resources, group related items, and/or provide guidance within the UI for anything ambiguous. See [#4888](https://github.com/rancher/dashboard/issues/4888).
