### ISSUE TITLE
Restricted-admin and flag

### ISSUE THREAD

**Issue by dramich** [rancher/docs#2702]
The restricted-admin DOES have full admin access in all downstream clusters.

The restricted-admin can create other restricted-admins as that would be equal to their level of access.

A new setting was added to Rancher to set the initial bootstrapped admin to be the restricted-admin. This only applies to the first start of rancher when we add this first user. If the flag is set then no 'real' admin would be created and it would be impossible to do so through rancher. An admin user in the cluster itself (not through rancher) would be the only way to do admin level things in the local cluster.

Restricted-admin:
Has full admin access to all downstream/user clusters (not sure what term is normally used in the docs)
Very limited access to the local cluster, ideally they should just ignore it (can access rancher CRDs but has no access to any k8s native types)
Can add other users and assign them to clusters outside of local
Can create other restricted admins
Can not grant any permissions in the local cluster they don't currently have (this is how k8s normally operates)
Upgrade from hidden local cluster:
Drop the flag to hide the local cluster, if not dropped then rancher will not start 
Once signed in a current global admin should change all global admins over to the new restricted admin role.
This can be done through Security>Users and moving any Administrator role over to Restricted Administrator
Signed in user can even change themselves over to the restricted admin if they wish but the should only do that as the last step otherwise they won't have the permissions to do so. 

https://github.com/rancher/rancher/issues/28977

**Comment by catherineluse** [comment]
updated snippet from Dan:

> 
> Restricted-admin:
> Has full admin access to all downstream/user clusters (not sure what term is normally used in the docs)
> Very limited access to the local cluster, ideally they should just ignore it (can access rancher CRDs but has no access to any k8s native types)
> Can add other users and assign them to clusters outside of local
> Can create other restricted admins
> Can not grant any permissions in the local cluster they don't currently have (this is how k8s normally operates)
> Upgrade from hidden local cluster:
> Drop the flag to hide the local cluster, if not dropped then rancher will not start 
> Once signed in a current global admin should change all global admins over to the new restricted admin role.
> This can be done through Security>Users and moving any Administrator role over to Restricted Administrator
> Signed in user can even change themselves over to the restricted admin if they wish but the should only do that as the last step otherwise they won't have the permissions to do so. 
> Collapse

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/issues/2702 was merged
