### ISSUE TITLE
Update taint example for k3s HA master isolation

### ISSUE THREAD

**Issue by mak3r** [rancher/docs#2707]
Currently, the docs on this page https://rancher.com/docs/k3s/latest/en/installation/ha/ gives an example for creating masters that are not also workers by tainting the nodes. The example given `--node-taint k3s-controlplane=true:NoExecute` seems to be viewed as the specific taint needed to achieve separation of masters from workers. I noticed there is a closed issue https://github.com/rancher/k3s/issues/1401 related but I don’t think the merged fix actually solves the issue - being that this taint still does not create independent masters in an HA cluster.

I think we should update the docs to give this example instead `--node-taint CriticalAddonsOnly=true:NoExecute`. Still only an example, but it will automatically work with the existing tolerations on the critical addons. One exception is the traefik installer but once workers are added even svclb would land on the nodes tainted this way (which may or may not be desirable).

**Comment by catherineluse** [comment]
Closing this issue because I have made the change here: https://github.com/rancher/docs/commit/85fd92ee9f8effd158d4f8568eb9f73842b07310
