### ISSUE TITLE
Update docs on snapshot behavior

### ISSUE THREAD

**Issue by maggieliu** [rancher/docs#2726]
The way the snapshotting works is:

- Determine the name for the snapshot (this is auto generated for RKE/Rancher, and overridable for RKE one-time snapshots (--name)), for Rancher it's a naming convention based on the type (manual/recurring) and target (local/s3), examples: c-9dmxz-rl-8b2cx, c-9dmxz-ml-kr56m, c-9dmxz-ms-t6bjb, c-9dmxz-rs-8gxc8 (m/r for manual recurring, l/s for local/s3)
- For each etcd node in the cluster, we check the cluster health, if healthy, create a snapshot, optionally upload it (if s3). If the directory where is written to is a shared mount, it will be overwritten. On S3, the snapshot will always be from the last node that uploads it (as all upload it and the last will survive)

On restore the snapshot is retrieved from s3 (if configured), unzipped (if zipped), one of the etcd nodes in the cluster will serve that snapshot file to the other nodes, the other nodes will download it and validate checksum so they all use the same snapshot for restore, it will be restored and post restore actions will be done in the cluster.

This process ensures that it will always result in a valid snapshot of their etcd cluster, no matter if it is being overwritten from another node. In the case when multiple etcd nodes exist, taking a snapshot from any node will work.

**Comment by catherineluse** [comment]
@maggieliu is this change part of the rancher-backup feature docs?

**Comment by maggieliu** [comment]
@catherineluse nope this is the regular etcd snapshot for cluster manager. You can document it when you are free. Low priority.

**Comment by deniseschannon** [comment]
@superseb can you review the PR that's made around this as it relates to: https://rancher.zendesk.com/agent/tickets/10274
