### ISSUE TITLE
403 Forbidden- Some links are broke. 

### ISSUE THREAD

**Issue by EminUZUN** [rancher/docs#2752]
Hi @catherineluse
Some webpage links are broken.
I guess it is because of last PR's.
https://github.com/rancher/docs/blob/master/content/rancher/v2.x/en/installation/%7B%7B%3Cbaseurl%3E%7D%7D/rancher/v2.x/en/installation/k8s-install

https://rancher.com/docs/rancher/v2.x/en/installation/k8s-install/

**Comment by EminUZUN** [comment]
@catherineluse

**Comment by catherineluse** [comment]
Closing this issue because the links are fixed
