### ISSUE TITLE
Broken link in alerting docs

### ISSUE THREAD

**Issue by aiyengar2** [rancher/docs#2776]
https://github.com/rancher/docs/blame/master/content/rancher/v2.x/en/monitoring-alerting/_index.md#L86 is broken as it points to the link `https://rancher.com/docs/rancher/v2.x/en/configuration`, which does not exist.

It should point to `https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/configuration/`.

**Comment by catherineluse** [comment]
Closing this issue because the link is fixed
