### ISSUE TITLE
Expected behavior for workloads created `natively`

### ISSUE THREAD

**Issue by alena1108** [rancher/docs#278]
When workload gets created `natively` (using kubectl), it gets discovered by Rancher and displayed in the UI. And if user edits such workload using Rancher UI/API, there are chances that the pods would get recreated, even if the update only changes the workload scale. It happens because Rancher's API require some data to be put to k8s annotations on the pod spec, and pod spec changes trigger workload upgrade/pod recreation.

https://github.com/rancher/rancher/issues/13655
We should document this behavior.

@deniseschannon

**Comment by panho66** [comment]
Without using kubectl CLI to create workload, what is other CLI option in Rancher 2.x to create workload without GUI
