### ISSUE TITLE
Do the cert manager versions in the docs need updating?

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#2803]
cert-manager is at version v1.0.3 atm, but we still have users installing v0.15.0 in the docs.
Is this intentional or do we need to do some QA and update the docs?

https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/#5-install-cert-manager

**Comment by bashofmann** [comment]
There are already two open and already tested PRs for this:

* https://github.com/rancher/docs/pull/2578
* https://github.com/rancher/docs/pull/2579

They are referencing 1.0.1 though and one of them would need to be rebased.

@catherineluse Should I maybe create a new PR that updated cert-manager in both places to the current 1.0.4? I have been running this version without problems for a two weeks now and already had several prospects asking me why we are referencing an old 0.x version of cert-manager in our docs.

**Comment by bashofmann** [comment]
Also a bit related to this: https://github.com/rancher/docs/pull/2802

**Comment by catherineluse** [comment]
Raul is the go-to person for the cert-manager docs.
@rawmind0 Can you please review these PRs?

**Comment by catherineluse** [comment]
Closing this issue because the cert-manager version is now updated to v1.0.4 in the Helm chart install and air gap installation docs.
