### ISSUE TITLE
Apps - Apps deployed from Ember UI that are tagged as upgrade available are not shown upgrade in Dashboard

### ISSUE THREAD

**Issue by izaac** [rancher/docs#2811]
Rancher version: `master-head (10/30/2020)` _5d3ffc1_
Rancher version: `v2.5-head (10/30/2020)` _cc777eb_

- Deploy Wordpress 7.3.8 from Ember UI
- The App is shown with an upgrade available.

 
![Screen Shot 2020-10-30 at 10 10 03 AM](https://user-images.githubusercontent.com/27659/97736052-5cd8df00-1a98-11eb-9c0d-28442316a907.png)

![Screen Shot 2020-10-30 at 10 09 55 AM](https://user-images.githubusercontent.com/27659/97736058-606c6600-1a98-11eb-90b8-2f9269143699.png)

**Workaround**: add the helm2 chart repo to show it.
This looks straightforward and probably even obvious but can lead to some confusion. We might need to document this.

![Screen Shot 2020-10-30 at 10 15 51 AM](https://user-images.githubusercontent.com/27659/97736436-e8527000-1a98-11eb-936f-506cd29d93a5.png)

rancher/dashboard#1693

**Comment by izaac** [comment]
However if i try to upgrade I get this failure:

```
helm upgrade --history-max=5 --install=true --namespace=wordpress --timeout=10m0s --values=/home/shell/helm/values-wordpress-9.0.3.yaml --version=9.0.3 --wait=true wordpress /home/shell/helm/wordpress-9.0.3.tgz
Release "wordpress" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "wordpress-mariadb" in namespace "wordpress" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "wordpress"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "wordpress"
```

**Comment by cbron** [comment]
The helm v2 and v3 tools work differently:

> v2 and v3 release (history) storage are independent of each other. The changes include the Kubernetes resource for storage and the release object metadata contained in the resource. Releases will also be on a per user namespace instead of using the Tiller namespace (for example, v2 default Tiller namespace kube-system). v2 uses "ConfigMaps" or "Secrets" under the Tiller namespace and `TILLER` ownership. v3 uses "Secrets" in the user namespace and helm ownership. Releases are incremental in both v2 and v3

- https://helm.sh/docs/topics/v2_v3_migration/

So you won't be able to manage a v2 app with the shell or with the vue UI. It appears that you can't edit/upgrade apps installed via ember in the dashboard unless you manually add those old catalogs as repo's. So basically, that is not a supported path. @catherineluse We should document that apps managed via ember must continue to only be managed via ember, and apps managed via dashboard must be managed only with dashboard.

**Comment by catherineluse** [comment]
Closing this issue because I added to the apps page:

>  Apps managed by the Cluster Manager should continue to be managed only by the Cluster Manager, and apps managed with the Cluster Explorer must be managed only by the Cluster Explorer.


https://github.com/rancher/docs/commit/f1285a9dd16af66775f191e73e4a24632a053ed9
