### ISSUE TITLE
reading down the k3s docs in order, it implies that the helm cmdline tool is installed in the path

### ISSUE THREAD

**Issue by SvenDowideit** [rancher/docs#2812]
https://rancher.com/docs/k3s/latest/en/cluster-access/

```
helm ls --all-namespaces
```

its not installed on my just started system, and there's not "pre-req's note"

similarly, the examples all don't use `sudo`, but 

```
dow184@onaci-010:~$ ls -la /etc/rancher
ls: cannot open directory '/etc/rancher': Permission denied
```

and I also didn't see anything before this dealing with this issue :)

**Comment by btat** [comment]
Closing based on https://github.com/rancher/docs/issues/2812#issuecomment-947806920.
