### ISSUE TITLE
docker command needs `--privileged`

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#2815]
https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/advanced/?query=persistentdata

The persistent data command here and on other related pages does not include the `--privileged` key.  This key is required as seen in the logs, but I can't see where the section is being pulled from so opening an issue to fix it.

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/2842 was merged
