### ISSUE TITLE
In cluster.yml, one needs to use kubeproxy instead of kube-proxy

### ISSUE THREAD

**Issue by leodotcloud** [rancher/docs#2817]
URL: https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/

It would be useful to add extra_args example for kubeproxy as well. It's not obvious at all that the top level key for kube proxy is `kubeproxy`, not `kube-proxy`.

Context: https://github.com/rancher/rke/issues/971

**Comment by superseb** [comment]
This was added to https://rancher.com/docs/rke/latest/en/config-options/services/
