### ISSUE TITLE
[Rancherd] Document airGap setup

### ISSUE THREAD

**Issue by maggieliu** [rancher/docs#2826]
QA will provide the detailed steps taken to setup the airgap environment for Rancherd per this [issue](https://github.com/rancher/rancher/issues/29797). The steps should be added in the Rancher docs.

**Comment by catherineluse** [comment]
Denise said that we need to document this for networking:

> As part of air gap docs, we also need a note that specifies if you are connecting to an external service through alertmanager or logging, the external service needs to be reachable from the cluster running the tool

**Comment by btat** [comment]
Not applicable with the deprecation of RancherD.
