### ISSUE TITLE
Using DHCP Options Sets limitation on AWS

### ISSUE THREAD

**Issue by maggieliu** [rancher/docs#2827]
We need to document that when using DHCP Options Sets with Windows, only one domain name can be specified in the domain-name field per this [doc](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_DHCP_Options.html)

Excerpt below:

**Important**
Some Linux operating systems accept multiple domain names separated by spaces. However, other Linux operating systems and Windows treat the value as a single domain, which results in unexpected behavior. If your DHCP options set is associated with a VPC that has instances with multiple operating systems, specify only one domain name.

**Comment by catherineluse** [comment]
@maggieliu who should review this?

**Comment by maggieliu** [comment]
@luthermonson can review

**Comment by catherineluse** [comment]
Closing because https://github.com/rancher/docs/pull/2845 is merged
