### ISSUE TITLE
Versioning of docs

### ISSUE THREAD

**Issue by maggieliu** [rancher/docs#2835]
* Create different versions of docs for the different Rancher minor versions.

Need to check for:

- [ ] Redirect links
- [ ] Branch docs repo

**Comment by catherineluse** [comment]
Need to also raise issue on rancherlabs/website repo about adding a dropdown menu to allow a user to select a product version when reading the docs.

**Comment by catherineluse** [comment]
I opened an issue in rancherlabs/website so that we can have a banner saying the 2.x docs will no longer be maintained. https://github.com/rancherlabs/website/issues/2548

As soon as that is merged, we can merge staging to master.
