### ISSUE TITLE
[EKSv2] Add docs for clusters with private API endpoint

### ISSUE THREAD

**Issue by thedadams** [rancher/docs#2849]
Describe the process for creating an EKS cluster with private-only endpoint.

Describe the process for import an EKS cluster with private-only endpoint.

In both cases, it should also be noted that the extra steps can be avoided by enabling public API access until the cluster is completely created or imported. After these points, public access can be disabled in the Rancher UI without any extra steps.

**Comment by catherineluse** [comment]
https://github.com/rancher/docs/pull/2887
