### ISSUE TITLE
[Rancher2] Need to update a link on the Istio setup guide page.

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#2864]
**Request Summary:**
Need to update a link on the Istio setup guide page.

**Details:**
1. URL: https://rancher.com/docs/rancher/v2.x/en/istio/v2.5/setup/#generate-traffic-and-see-istio-in-action
2. Location: under "Install"section, step 6"Generate traffic and see Istio in action." the link should be https://rancher.com/docs/rancher/v2.x/en/istio/v2.5/setup/view-traffic/ instead of what is it right now.
3. Another problem is the topics listed in the sidebar is inaccurate. Either a step 3 is missing, or the topics are named incorrectly.
See screenshot below for more details.

![image](https://user-images.githubusercontent.com/36651058/100071423-0338ba00-2e76-11eb-8957-b1b9030cb866.png)

**Comment by catherineluse** [comment]
https://github.com/rancher/docs/commit/ddda2168c88381b79548fa1ba0b10438412fda96
