### ISSUE TITLE
[Rancher2] Typo in Generate and View Traffic page

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#2865]
**Request Summary:**
Typo in Generate and View Traffic page.

**Details:**
1. URL: https://rancher.com/docs/rancher/v2.x/en/istio/v2.5/setup/view-traffic/
2. Description: "namesace"should be "namespace".
![image](https://user-images.githubusercontent.com/36651058/100077130-f2d80d80-2e7c-11eb-844d-aa18b3aacdc4.png)

**Comment by catherineluse** [comment]
https://github.com/rancher/docs/commit/ddda2168c88381b79548fa1ba0b10438412fda96
