### ISSUE TITLE
[Rancher2] Update Windows and RBAC sections in Logging

### ISSUE THREAD

**Issue by nickgerace** [rancher/docs#2867]
**Request Summary:**

The Windows support information is outdated in the [logging docs](https://rancher.com/docs/rancher/v2.x/en/logging/v2.5/).
The RBAC section of logging can be streamlined. There are also a few grammatical errors that can be cleaned up as well.

**Details:**

- Windows support information concerning the `fluentd-configcheck`
- Refactor RBAC section to be more streamlined
- Add note on incoming syslog support
- General grammatical errors

**Comment by catherineluse** [comment]
https://github.com/rancher/docs/pull/2869
