### ISSUE TITLE
[Rancher2] Typo in "Add Deployments and Services with the Istio Sidecar" page

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#2875]
**Request Summary:**
A typo occurs in this page, "worklod" should be "workload" instead.

**Details:**
1. URL: https://rancher.com/docs/rancher/v2.x/en/istio/v2.5/setup/deploy-workloads/#add-deployments-and-services
2. Description:  "worklod" should be "workload" instead.

![image](https://user-images.githubusercontent.com/36651058/100418459-c19a5000-30bd-11eb-99e3-edd28748a93a.png)

**Comment by catherineluse** [comment]
https://github.com/rancher/docs/commit/847d603a2b0f08d9ecf8df09b398b85acac93250
