### ISSUE TITLE
[Rancher2] Istio v2: CNI documentation update

### ISSUE THREAD

**Issue by brendarearden** [rancher/docs#2877]
**Request Summary:**
CNI is now available as part of the istio installation instead of a separate experimental installation, so documentation needs to be updated to detail how to enable the istio cni instead of installing it separately. 

**Details:**
https://rancher.com/docs/rancher/v2.x/en/istio/v2.3.x-v2.4.x/setup/enable-istio-in-cluster/enable-istio-with-psp
Step 1 can stay that same as this information is still relevant
Step 2 Would be to enable the cni component when installing or upgrading istio by checking the box next to cni in the component secton of the install / upgrade page or by setting cni to enabled in the values.yaml. 
Step 3 Would be something like "istio should install successfully with cni now enabled in your cluster. You can test verify this is working by deploying a sample application (https://istio.io/latest/docs/examples/bookinfo/) or attempting to deploy one of your own applications"

**Comment by brendarearden** [comment]
https://github.com/rancher/rancher/issues/27377#issuecomment-739075400. << need to also cover steps to enable istio in rke2 - this involves manually making changes to the deamonset. See linked comment for steps

**Comment by brendarearden** [comment]
This would be for v2 docs only - legacy docs should remain the same to ensure those running older version of rancher can install the cni pluggin if needed.

**Comment by catherineluse** [comment]
I have added the steps to install Istio on an RKE2 cluster in staging here: 
https://staging.rancher.com/docs/rancher/v2.x/en/istio/v2.5/#additional-steps-for-installing-istio-on-an-rke2-cluster

And the CNI documentation update is in the staging branch here: 
https://staging.rancher.com/docs/rancher/v2.x/en/istio/v2.5/setup/enable-istio-in-cluster/enable-istio-with-psp/

@brendarearden and @rancher-max can you please review?

**Comment by rancher-max** [comment]
Awesome, those docs LGTM, thanks @catherineluse!

**Comment by brendarearden** [comment]
Just reviewed! Everything LGTM!!
