### ISSUE TITLE
[Rancher2] Add section to ingress-nginx for default-http-backend

### ISSUE THREAD

**Issue by nickgerace** [rancher/docs#2881]
**Request Summary:**

Related PR: https://github.com/rancher/rke/pull/2346
Related issue: rancher/rancher#25590

Add section in `ingress-nginx` for `default-http-backend`. This section will need to indicate the following...

1. The default behavior will remain the same.
1. If the new `default_backend` flag is set to `false` on an existing installation, then the `default-http-backend` service and deployment will need to be uninstalled.

**Details:**

https://rancher.com/docs/rke/latest/en/config-options/add-ons/ingress-controllers/

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/2890 was merged
