### ISSUE TITLE
[Rancher2] Missing Information on "Monitoring in Rancher v2.5" page

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#2883]
**Request Summary:**
On "Monitoring in Rancher v2.5" page, under "Monitoring Components" section, information about "Alertmanager", "Prometheus Operator", and "Prometheus Adapter" are missing. 

**Details:**
1. URL: https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.5/#about-prometheus-adapter
2. Location: Right under the notes says that "Before enabling monitoring, be sure to review the resource requirements. The default values in this section are the minimum required resource limits and requests".
3. Issue:  information about "Alertmanager", "Prometheus Operator", and "Prometheus Adapter" are missing. See attached screenshot for detailed information.

![image](https://user-images.githubusercontent.com/36651058/101118705-974c1380-3624-11eb-8113-f56952c48542.png)

**Comment by catherineluse** [comment]
Closing because in https://github.com/rancher/docs/pull/2933 I have removed the empty sections
