### ISSUE TITLE
[Rancher2] Missing RBAC subtile on "Backup and Restore in Rancher v2.5" page

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#2889]
**Request Summary:**
Missing RBAC subtile on "Backup and Restore in Rancher v2.5" page.
**Details:**
1. URL: https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/
2. Location: "RBAC" section
3. Descirption: "RBAC" section is not listed in the beginning of this page. Maybe you should consider adding it to the top part of this page. See screenshots below for more details.

![image](https://user-images.githubusercontent.com/36651058/101325922-8101ba00-38a7-11eb-8bdb-ec0c65f1b9e9.png)
![image](https://user-images.githubusercontent.com/36651058/101325991-95de4d80-38a7-11eb-878b-5ee4de990e09.png)

**Comment by catherineluse** [comment]
Closing because it is addressed in https://github.com/rancher/docs/pull/2933
