### ISSUE TITLE
[Rancher2] Update links to K3s docs to point to new docs.k3s.io website

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#2891]
**Request Summary:**

This may not be ready just yet, but when we create docs.k3s.io we should review any links in Rancher2 documentation that link directly to k3s docs pages. We should instead update these so they no longer point to rancher.com k3s docs, rather pointing to the necessary docs page on docs.k3s.io.

It's possible we may actually be planning a solution to redirect links. If this happens, we can do one of the following:
- Not worry about updating the links, since redirects should save us
- Update the links, but as a lower priority since redirects should work.

I vote for the second option (assuming redirects work) because as we eventually refactor k3s docs down the road, those links may break. So it makes sense to actually update them to properly link to rke2 docs at some point (assuming rke2 docs will also be able to redirect to any new pages as we make changes). Plus I think it's just nicer/cleaner to properly link to the correct location rather than relying on redirects.

If we do not have a solution to redirect then we must update links to k3s docs as soon as possible.

**Details:**

**Comment by catherineluse** [comment]
Removing from the 2.6 milestone because the k3s docs aren't published separately yet.

**Comment by btat** [comment]
No longer applicable.
