### ISSUE TITLE
[rke2] RKE2 -> Rancher 2.6 Integration

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#2900]
**Summary:**

In Rancher 2.6, additional support for RKE2 will be implemented. We currently plan to:
- Be able to provision RKE2 clusters in new Vue UI.
- Be able to support most or all the same CNI as RKE1 today
- Support Cluster templates
- Support config of nodes
- Support etcd backup and restore and rollback*
- Support addons
- Support CIS 1.6 in Rancher for RKE2
- Upgrades
- Airgap

In essence we should be very close to feature parity with RKE1. Everything I call out above may not need explicit documentation but I thought it would help to call these out. We may need to discuss further later to flush all this out.

**Details:**

**Comment by catherineluse** [comment]
@davidnuzik can you change all the same options for registered RKE2 clusters that you can for clusters created within Rancher?

**Comment by davidnuzik** [comment]
@catherineluse terribly sorry for the very late response. RKE2 won't have complete 100% feature parity, no. Happy to ask a dev on k3s/rke2 team to help identify differences if you would like. Just let me know.

**Comment by catherineluse** [comment]
Confirmed flannel/weave aren't supported for RKE2.

**Comment by btat** [comment]
Related issues:
- [ ] https://github.com/rancher/docs/issues/3258
- [x] https://github.com/rancher/docs/issues/3326
- [x] https://github.com/rancher/docs/issues/3343
- [ ] https://github.com/rancher/docs/issues/3369
- [x] https://github.com/rancher/docs/issues/3450
- [x] https://github.com/rancher/docs/issues/3463
- [x] https://github.com/rancher/docs/issues/3466
