### ISSUE TITLE
Edit quick start guides to use RancherD instead of docker run

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#2928]
Also edit any other place in the docs that seems to encourage the use of docker run.

The docker run installation method will be deprecated in a future rancher version.

**Comment by catherineluse** [comment]
@deniseschannon Should the quick start guides not be updated until RancherD goes GA?

**Comment by catherineluse** [comment]
Docker isn't currently mentioned by name in the quick start guides. It's part of the automation stuff in the related GitHub repository. So currently the guides don't endorse the Docker install.

**Comment by catherineluse** [comment]
I removed the v2.5.4 milestone because RancherD is not going to be GA in v2.5.4.

I think we should talk about additional changes to the quickstart guides. My questions are:

- As of Rancher v2.5, we want to target users who will only be using the local Kubernetes cluster, in addition to users who will be using Rancher to manage other clusters. Does that mean we should have two quickstart guides, one for cluster manager with a downstream cluster (which is what we have already) and one for just Rancher on a local Kubernetes cluster? Or should we just get rid of the cluster manager quickstart guides entirely?
- Should RancherD completely replace the quickstart guides when it goes GA?
- If we keep the quickstart guides, should they be renamed to "Terraform guides" and edited so that they deploy high-availability Rancher for cluster manager? (Right now it deploys a single-node cluster manager which we discourage.)

@SheilaghM The above list are the questions I think we should talk about regarding the quickstart guides

**Comment by catherineluse** [comment]
In a meeting with Sheilagh, Caleb, and William, we discussed that we should probably make the following changes:

- Reduce the six quickstart guides to one guide, which is just a guide about how to install RancherD on a single node.
- Say in the prerequisites that if you need help setting up a Linux node, refer to the EC2 tutorial or to the old quickstart (Terraform or Vagrant) guides. Might also link out to upstream cloud provider docs for help setting up the node.
- Say that if you want to do multi-cluster management, you should go through the full installation documentation.
- Move the Terraform/Vagrant guides into the "Resources" section so that people who are looking for Terraform can still find it. https://rancher.com/docs/rancher/v2.x/en/installation/resources/
- Change the Terraform/Vagrant guides to use RancherD instead of Docker. Talk about what each of them is doing in more detail than the current description, and properly introduce the Rancher Terraform provider there.

These changes aren't planned to take effect until RancherD is GA.

We also need to run this by Denise.

**Comment by jtravee** [comment]
Closing as RancherD has been discontinued. Will re-open if a future iteration requires. Related: [#3825](https://github.com/rancher/docs/issues/3825).
