### ISSUE TITLE
RancherD Doc Changes

### ISSUE THREAD

**Issue by rancher-max** [rancher/docs#2935]
**Summary:**

Reviewed RancherD docs on staging branch and have a few important edits that should be made

**Details:**

Many of these are suggestions and open for discussion, but 2 and 4 are required.

1. https://staging.rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/#node-requirements
- If we link node requirements, we should probably specifically mention Docker is NOT necessary to have on the Linux Host. It currently looks like it is required when we link that page.

2. https://staging.rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/#1-set-up-the-config-yaml in "If you do not specify a pre-shared secret, RancherD will generate one and place it at /var/lib/rancher/rancherd/server/node-token."
- this should be  /var/lib/rancher/rke2/server/node-token

3. https://staging.rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/#2-launch-the-first-server-node
- In step 1 here, should we specify available environment variables? The relevant one to me is: `INSTALL_RANCHERD_VERSION`
- So an example curl command would be like: `curl -sfL https://get.rancher.io | INSTALL_RANCHERD_VERSION=v2.5.4-rc6 sh -`

4. https://staging.rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/rancherd-configuration/#customizing-the-rancherd-helm-chart In "Put this manifest on your host in /var/lib/rancher/rancherd/server/manifests before running RancherD."
- should be /var/lib/rancher/rke2/server/manifests

5. https://staging.rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/#4-verify-that-rancher-is-installed-on-the-kubernetes-cluster 
Should we mention that there will be many things installed? If watching pods, you'll see:
  - `helm-operation` pods in `cattle-system` namespace
  - a `rancher` pod and `rancher-webhook` pod in `cattle-system` namespace
  - a `fleet-agent`, `fleet-controller`, and `gitjob` pod in `fleet-system` namespace
  - a `rancher-operator` pod in `rancher-operator-system` namespace
 
6. https://staging.rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/#fixed-registration-address
- We should mention that the Rancher UI is served on port 8443 by default, as opposed to 443 which is what happens in standard rancher installs, so LBs or whatever is used should be setup appropriately. For example, in my testing, I setup a single LB in AWS and 4 Target Groups using TCP to 6443, 9345, 8080, and 8443. In the LB I forwarded like: 6443 -> 6443, 9345 -> 9345, 80 -> 8080, 443 -> 8443. NOTE that we do mention these ports in https://staging.rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/rancherd-configuration/#customizing-the-rancherd-helm-chart
but I think it would be helpful in this section as well for clarity.
- This can be as simple as adding it to https://staging.rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/#fixed-registration-address at the end with the other ports.

7. Would it be useful to mention that installing this way is using rancher generated certs, and if they want to use a different cert method, follow the configuration guide here? https://staging.rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/rancherd-configuration/#certificates-for-the-rancher-server
- I'd imagine this should be mentioned in https://staging.rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/#1-set-up-the-config-yaml
- We can link to the certificates. 
- Maybe this section can be called "Setup configurations" and link to certificates, have this information about config.yaml, and also link to the values.yaml configurations at https://staging.rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-linux/rancherd-configuration/#customizing-the-rancherd-helm-chart

**Comment by rancher-max** [comment]
Also, can we mention at the beginning of Part I that "this is using rancher generated certs, and if you want to bring your own self-signed or valid certs, to follow instructions in configuration reference on each node before running steps" -- I'm not sure what the best wording would be, but something that alerts the user of the certs used by default and what they would need to do BEFORE running install if they wanted to use a different option. cc @jiaqiluo

**Comment by catherineluse** [comment]
closing because https://github.com/rancher/docs/pull/2947 was merged
