### ISSUE TITLE
rancher has to be manually started with the lower/previous version after a rollback using rancher backup

### ISSUE THREAD

**Issue by sowmyav27** [rancher/docs#2956]
`rancher-backup-operator version: 1.0.2`

**Steps:**

- Deployed Rancher HA on 2.5.3
- Take a backup b1 using rancher backups
- Upgrade to 2.5.4-rc8
- Restore from backup b1

After restore of rancher on the same setup, the rancher version continued to be on 2.5.4-rc8

**Expected:**
Rancher should get rolled back to 2.5.3

**Note:**
Additional steps:
- Change the image of rancher to 2.5.3 on the local cluster.
- The agents on the downstream clusters go back to 2.5.3
- Validation checks look good (pre upgrade checks)

Docs here - https://rancher.com/docs/rancher/v2.x/en/installation/upgrades-rollbacks/rollbacks/ha-server-rollbacks/ should be changed

**Comment by catherineluse** [comment]
@sowmyav27 How did you restart Rancher? Was that using Helm? like

> helm install rancher rancher-latest/rancher \
> --namespace cattle-system \
> --set hostname=rancher.my.org \
> --version=X.Y.Z

**Comment by catherineluse** [comment]
I believe this can be closed because it is addressed by https://github.com/rancher/docs/pull/3004/files
