### ISSUE TITLE
[Rancher2] Update air gap docs to say how to use K3s install version environment variable

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#2974]
I already updated the Rancher and K3s install docs to mention the K3s version environment variable, and referred to the support matrix to find which Kubernetes versions Rancher supports.

Now the same needs to be done for the air gap Rancher install docs.

**Comment by btat** [comment]
https://rancher.com/docs/rancher/v2.5/en/installation/other-installation-methods/air-gap/launch-kubernetes/

**Comment by btat** [comment]
Already added via https://github.com/rancher/docs/commit/0a0590df5ccb1524f9df8af04ec0a40943979dfa
