### ISSUE TITLE
[Rancher2] Cluster Provisioning Table Ambiguity

### ISSUE THREAD

**Issue by capta1nk1rk** [rancher/docs#2975]
**Request Summary:**

On the page [Setting Up Clusters In Rancher](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/), there is a table which compares features between Rancher, Hosted, and Imported clusters.  Some of these fields are a bit too ambiguous without further clarification.

**Details:**

For example, "Cloning Clusters" in this context is referring to cloning the RKE config, not cloning/migrating Rancher components (such as with the Rancher Backup Operator).  

Also, the differences between "Ability to back up your Kubernetes Clusters" and "Ability to recover and restore etcd" are effectively the same in this context.  I would suggest that either the distinction is clarified, or one of the lines is removed, as it is confusing for many customers.

Lastly, for an imported cluster using EtcD as a control plane, EtcD snapshots could still be taken manually, it's just not integrated into the rancher UI.

Perhaps the table should change to have an additional "star/half check" option, for features that are technically possible, but not yet integrated into the Rancher WebUI.

**Comment by SheilaghM** [comment]
Related ticket:  https://zube.io/rancher/rancher-2x-docs/c/2876

**Comment by catherineluse** [comment]
Denise merged the PR I had done to update the table, so the additional changes will need to be an a separate PR.
