### ISSUE TITLE
[Rancher2] - add ingress.enabled Rancher helm flag

### ISSUE THREAD

**Issue by izaac** [rancher/docs#2976]
**Request Summary:**
Starting with 2.5.6-rc2 a new flag is available for users that would set an ingress by their own. This new flag will tell helm to not install a Rancher ingress.

**Details:**
The users will have this option if they are planning to configure their own infrastructure or configuration to get access to Rancher.

the flag is  `--set ingress.enabled=false`.
Default value is true.

https://github.com/rancher/rancher/issues/30535
https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/chart-options/

**Comment by catherineluse** [comment]
https://github.com/rancher/docs/commit/d385733a0c5afc76747a5cbf1734138e5984c8f4
