### ISSUE TITLE
[Rancher2] Document steps to update a private CA

### ISSUE THREAD

**Issue by dkeightley** [rancher/docs#2980]
**Request Summary:**

Add the steps needed to update the Rancher private CA, for eg, updating the downstream cluster/node agent `CATTLE_CA_CHECKSUM` environment variable.

[This gist](https://gist.github.com/janeczku/d96c4d4923334f40a959b90bda5d0d51) is a good reference. 

**Details:**

An additional heading under [Using a Private CA Signed Certificate](https://rancher.com/docs/rancher/v2.x/en/installation/resources/tls-secrets/#using-a-private-ca-signed-certificate) could be a good area to add this.

gz#14567

gz#14029

gz#13662

**Comment by superseb** [comment]
We can only document this if this is a supported action, the open issue for this is https://github.com/rancher/rancher/issues/14731

**Comment by catherineluse** [comment]
Denise said it's ok to document these steps.
