### ISSUE TITLE
[Rancher2] resources: requests > limits

### ISSUE THREAD

**Issue by DamianFekete** [rancher/docs#2990]
**Request Summary:**
[Resources table](https://rancher.com/docs/rancher/v2.x/en/istio/v2.5/resources/) lists limits for Istio-ingressgateway that are smaller than requests.

**Details:**
Limits have to be equal or bigger than the requests.
![image](https://user-images.githubusercontent.com/150717/106274573-c6ea5700-6234-11eb-9626-7f876a0e7fdc.png)

**Comment by catherineluse** [comment]
Fixed in this PR https://github.com/rancher/docs/pull/3041
