### ISSUE TITLE
[Rancher2] Istio CPU / Memory Usage updates

### ISSUE THREAD

**Issue by brendarearden** [rancher/docs#2999]
**Request Summary:**
Istio 1.8.1 removed additional resources and need to be redone. https://rancher.com/docs/rancher/v2.x/en/istio/v2.5/resources/

**Details:**

|workload   | request cpu  | request memory  |  limit cpu  |  limit memory |
|---|---|---|---|---|
|  ingress gateway |  100m | 128mi  | 2000m  |  1024mi |
| egress gateway  |  100m |  128mi |   2000m|  1024mi |
| istiod |  500m |  2048mi |   |   |
|proxy|  10m | 10mi| 2000m| 1024mi|
|||||||
|Totals:|710m|2314mi|6000m|3072mi|

**Comment by catherineluse** [comment]
@brendarearden I have two questions about this one -

- Can you confirm that there is no CPU or memory limit for istiod?
- Are these values configurable and if so, which values in the overlay file let you configure them? We've previously documented that the values can be configured in the overlay file, but now that I look at the file, I don't see exactly how you would update the requests/limits for those values. For example I don't see egress gatway:

```yaml
#apiVersion: install.istio.io/v1alpha1
#kind: IstioOperator
#spec:
#  components:
#    ingressGateways:
#    - enabled: true
#      name: istio-ingressgateway
#    - enabled: true
#      k8s:
#        resources:
#          requests:
#            cpu: 200m
#        service:
#          ports:
#          - name: tcp-citadel-grpc-tls
#            port: 8060
#            targetPort: 8060
#          - name: tcp-dns
#            port: 5353
#        serviceAnnotations:
#          cloud.google.com/load-balancer-type: internal
#      name: ilb-gateway
#      namespace: user-ingressgateway-ns
#    - enabled: true
#      k8s:
#        resources:
#          requests:
#            cpu: 200m
#        service:
#          ports:
#          - name: tcp-citadel-grpc-tls
#            port: 8060
#            targetPort: 8060
#          - name: tcp-dns
#            port: 5353
#        serviceAnnotations:
#          cloud.google.com/load-balancer-type: internal
#      name: other-gateway
#      namespace: istio-system
```

**Comment by brendarearden** [comment]
1. There is no CPU or memory limit for istiod, just the cpu and memory request. 
2. So the overlay file can be any variation of the values in here https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioOperatorSpec. The overlay file we included is just an example of one potential configuration of the overlay file, but essentially as long as you have `kind: IstioOperator` and you have put valid yaml options, it can be used as an overlay. So in the example we provided, it is the 
```
#      k8s:
#        resources:
#          requests:
#            cpu: 200m
```
section that allows you to change k8s resources (not all are available for changing but most are. Let me know if that didn't answer your question.
