### ISSUE TITLE
[Rancher2] Broken links in Security section

### ISSUE THREAD

**Issue by yzeng25** [rancher/docs#3016]
**Request Summary:**

these links should redirect to pdf files. it seems like either the links are wrong, or there are no such pdf files available for users. 

**Details:**
URLs: 
1. https://rancher.com/docs/rancher/v2.x/en/security/rancher-2.5/1.5-hardening-2.5/
2. https://rancher.com/docs/rancher/v2.x/en/security/rancher-2.5/1.5-benchmark-2.5/
3. please check other links in this "docs/rancher/v2.x/en/security" section as well.

Screenshots: 
![image](https://user-images.githubusercontent.com/36651058/107461540-334e4a00-6b95-11eb-8404-c86b3c6f0ca0.png)
![image](https://user-images.githubusercontent.com/36651058/107461560-3cd7b200-6b95-11eb-91a9-20ffa6f4a0bc.png)

**Comment by yzeng25** [comment]
hello @SheilaghM , are we gonna fix it or not?

**Comment by SheilaghM** [comment]
Yes, we will fix this. Milestone is TBD.
