### ISSUE TITLE
[Rancher2] Backup, Restoration, and Configuration docs should cover CLI or API process

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#3024]
**Request Summary:**
These pages (especially but not exclusively) should feature instructions on methods for running with CLI and / or API.  Many customers are restricted from using UI or use automation that can only interface with the CLI and API.  In times of outage, there will often be no option to restore via the UI that is out.

**Details:**

https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/back-up-rancher/
https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/restoring-rancher/
https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/configuration/backup-config/

gz#14762

**Comment by catherineluse** [comment]
Closing this issue because it sounds like it is outside the scope of what is officially supported. The issue can be reopened if the supported scope changes.
