### ISSUE TITLE
Install Rancher on EKS

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#3046]
Need to include Bastian's steps for how to set up an ingress.

**Comment by catherineluse** [comment]
https://github.com/rancher/docs/issues/2758

**Comment by catherineluse** [comment]
Bastian's steps are:


That’s what I did a couple of days ago, when a prospect wanted to see Rancher on EKS:Install nginx-ingress-controller with a LoadBalancer Service to automatically get a ELB in front of it:

helm upgrade --install \\  
  ingress-nginx ingress-nginx/ingress-nginx \\  
  --namespace ingress-nginx \\  
  --set controller.service.type=LoadBalancer \\  
  --version 3.12.0 --create-namespace

Then you can either create a DNS entry pointing to the LB, or take the AWS ELB DNS name.The rest follows the standard Rancher installation instructionsInstall cert-manager

helm upgrade --install \\  
  cert-manager jetstack/cert-manager \\  
  --namespace cert-manager \\  
  --set installCRDs=true \\  
  --version v1.0.4 --create-namespace

Install Rancher

helm upgrade --install rancher rancher-latest/rancher \\  
  --namespace cattle-system \\  
  --version 2.5.5 \\  
  --set hostname=a72e2f493f402478aa4aa33379a30760-24445120.eu-central-1.elb.amazonaws.com --create-namespace

**Comment by catherineluse** [comment]
@izaac Can you please test the instructions here https://staging.rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/amazon-eks/#creating-an-eks-cluster-for-the-rancher-server and leave feedback on this issue?

**Comment by izaac** [comment]
I reviewed this following the steps in staging and installing Rancher `v2.5.7` on EKS k8s 1.18.

- In the `PREREQUISITES` we can link to the `eksctl` official IAM requirements https://eksctl.io/usage/minimum-iam-policies/ In case anyone is interested in getting more details about `AdministratorAccess`.
- One of the `eksctl` parameters  `instance-type` didn't work for us when we use it in one region in our AWS QA project, we can either leave it as-is now or remove it.
- The get cluster info output is missing some formatting.

This is the output I get
```
eksctl get cluster
2021-03-18 15:09:35 [ℹ]  eksctl version 0.40.0
2021-03-18 15:09:35 [ℹ]  using region us-west-2
NAME		REGION		EKSCTL CREATED
iztest2		us-west-2	True
```

And this is in the Document:

```
2021-03-14 21:23:30 [ℹ]  eksctl version 0.40.0
2021-03-14 21:23:30 [ℹ]  using region us-west-2
NAMEREGIONEKSCTL CREATED
rancher-server-clusterus-west-2True
```

Everything else looks correct to me.

**Comment by catherineluse** [comment]
I've addressed Izaac's feedback in this PR https://github.com/rancher/docs/pull/3155
