### ISSUE TITLE
Install Rancher on GKE

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#3048]
https://github.com/rancher/docs/issues/2758

The new page is here: https://staging.rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/gke/

**Comment by izaac** [comment]
Validated on `v2.5.8` 
I did a quick check on links in the document
And also followed the instructions they look good. I was able to setup a GKE HA Rancher install and provision a downstream cluster.
