### ISSUE TITLE
[K3s] Fix references to "experimental" to etcd

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#3049]
**Request Summary:**

embedded etcd for k3s is no longer experimental. We should remove the (experimental) references on https://rancher.com/docs/k3s/latest/en/installation/datastore/ the main page was already fixed (https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/) it's just the /datastore/ page that needs the fix.

**Details:**

**Comment by catherineluse** [comment]
Addressed by https://github.com/rancher/docs/pull/3051
