### ISSUE TITLE
[Rancher2] Change Requirements for Windows Clusters

### ISSUE THREAD

**Issue by sowmyav27** [rancher/docs#3052]
[This section](https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/windows-clusters/#os-and-docker-requirements) has to change now that we support other versions of windows

**Comment by sowmyav27** [comment]
The rancher docs still do not reflect the versions of windows we support on 2.5.x. @catherineluse Can you please confirm if any changes have been made?

**Comment by catherineluse** [comment]
@sowmyav27 Yes, the support changed to support the Windows Server versions supported by Microsoft. We updated the docs to reflect it.
