### ISSUE TITLE
[Rancher2] Add  RKE2 as an installation method to Rancher2 docs

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#3056]
**Request Summary:**
Add a k8s tutorial to https://rancher.com/docs/rancher/v2.x/en/installation/resources/k8s-tutorials/ specifically for RKE2. This in most but not all regards is very much like the existing K3s one.
- We also should call out additional step for the ingress (nginx chart) so that it will either deploy as a daemon set or otherwise work in a HA (multi master node) setup for Rancher. It's important that this gets called out so that Rancher is effectively still properly HA (so we can avoid/limit single points of failure).
- We should update https://rancher.com/docs/rancher/v2.x/en/installation/install-rancher-on-k8s/ below the K3s entry in prerequisties section so it points to the tutorial.

**Details:**
Must have for Rancher 2.5.6 release.

**Comment by catherineluse** [comment]
@davidnuzik is this installation method experimental or GA?

**Comment by davidnuzik** [comment]
GA. @catherineluse and @galal-hussein will take first pass on this and we can review the PR together if you have the time.

**Comment by catherineluse** [comment]
Sounds good to me
