### ISSUE TITLE
Add example YAML for PagerDuty config for Rancher before v2.5.4

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#3058]
https://rancher.slack.com/archives/C6U4L2DS9/p1611862994016600?thread_ts=1611789510.013200&cid=C6U4L2DS9

Right now we just say to enter the values as pure YAML.

It would help to link to relevant upstream docs to help users out.

**Comment by SheilaghM** [comment]
Grab example from Prometheus documentation and link to or put into our docs as an example.
