### ISSUE TITLE
[Rancher2] Add docs for allowing non-Project members to access Monitoring components

### ISSUE THREAD

**Issue by aiyengar2** [rancher/docs#3061]
**Request Summary:**

Need to update https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.5/rbac/#users-with-k8s-clusterrole-based-permissions to include [`monitoring-ui-view` ClusterRole](https://github.com/rancher/charts/blob/9114480996d7abfe87e1f07c80ddccb0e20169d1/charts/rancher-monitoring/rancher-monitoring/9.4.204-rc04/templates/rancher-monitoring/clusterrole.yaml#L94-L122)

Also need to update https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.5/rbac/#users-with-rancher-cluster-manager-based-permissions with the new `View Monitoring` Rancher RoleTemplate.

**Details:**

#### https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.5/rbac/#users-with-k8s-clusterrole-based-permissions

Add a new subsection for `Additional ClusterRoles`. 

It should have a statement that specifies that these ClusterRoles are not aggregated by default but can be bound to a namespace by deploying a RoleBinding that references it.

There should then be a table with the following entry

Name: `monitoring-ui-view` 

Available From: 9.4.204+

Description:
```
Provides read-only access to external Monitoring UIs by giving a user permission to list the Prometheus, Alertmanager, and Grafana endpoints and make GET requests to Prometheus, Grafana, and Alertmanager UIs through the Rancher proxy.
```

#### https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.5/rbac/#users-with-rancher-cluster-manager-based-permissions

Below the table, add the following description:
```
In addition to these default Roles, the following additional Rancher Project Roles can be applied to members of your Cluster to provide additional access to Monitoring. These Rancher Roles will be tied to ClusterRoles deployed by the Monitoring chart.
```

Followed by another table with the following fields:

Cluster Manager Role: View Monitoring*

Available In Rancher From: 2.4.8+

k8s ClusterRole: monitoring-ui-view (link to above ClusterRole for description)

Available in Monitoring V2 From: 9.4.204+

There should also be a caveat listed below that says something similar to the following:
```
Note: A User bound to the View Monitoring Rancher Role only has permissions to access external Monitoring UIs if provided links to those UIs. In order to access the Monitoring Pane on Cluster Explorer to get those links, the User must be a Project Member of at least one Project.
```

**Comment by aiyengar2** [comment]
@catherineluse I don't think there's a label that tracks a dependency on a backend issue in this repository, but we should not start working on this issue until https://github.com/rancher/rancher/issues/31411 is resolved. 

Once that is resolved, I will come back to this issue, update it based on the content that was actually merged, and leave another comment here that this issue is ready to be addressed!

**Comment by aiyengar2** [comment]
@catherineluse issue has been updated. Ready to be addressed after https://github.com/rancher/dashboard/issues/2521 is complete.

**Comment by catherineluse** [comment]
Does it make sense to put the additional ClusterRoles table in a similar format to the existing table of existing roles for monitoring? like this?

### Additional Monitoring Roles

Monitoring also creates additional `Roles` that are not assigned to users by default but are created within the cluster. They can be bound to a namespace by deploying a RoleBinding that references it.

Admins should use these roles to provide more fine-grained access to users:

| Role | Purpose  |
| ------------------------------| ---------------------------|
| monitoring-config-admin | Allow admins to assign roles to users to be able to view / modify Secrets and ConfigMaps within the cattle-monitoring-system namespace. Modifying Secrets / ConfigMaps in this namespace could allow users to alter the cluster's Alertmanager configuration, Prometheus Adapter configuration, additional Grafana datasources, TLS secrets, etc. |
| monitoring-config-edit | Allow admins to assign roles to users to be able to view / modify Secrets and ConfigMaps within the cattle-monitoring-system namespace. Modifying Secrets / ConfigMaps in this namespace could allow users to alter the cluster's Alertmanager configuration, Prometheus Adapter configuration, additional Grafana datasources, TLS secrets, etc. |
| monitoring-config-view | Allow admins to assign roles to users to be able to view Secrets and ConfigMaps within the cattle-monitoring-system namespace. Viewing Secrets / ConfigMaps in this namespace could allow users to observe the cluster's Alertmanager configuration, Prometheus Adapter configuration, additional Grafana datasources, TLS secrets, etc. |
| monitoring-dashboard-admin | Allow admins to assign roles to users to be able to edit / view ConfigMaps within the cattle-dashboards namespace. ConfigMaps in this namespace will correspond to Grafana Dashboards that are persisted onto the cluster. |
| monitoring-dashboard-edit | Allow admins to assign roles to users to be able to edit / view ConfigMaps within the cattle-dashboards namespace. ConfigMaps in this namespace will correspond to Grafana Dashboards that are persisted onto the cluster. |
| monitoring-dashboard-view | Allow admins to assign roles to users to be able to view ConfigMaps within the cattle-dashboards namespace. ConfigMaps in this namespace will correspond to Grafana Dashboards that are persisted onto the cluster. |

### Additional Monitoring ClusterRoles

Monitoring also creates additional `ClusterRoles` that are not assigned to users by default but are created within the cluster.  They are not aggregated by default but can be bound to a namespace by deploying a RoleBinding that references it.

| Role | Purpose  |
| ------------------------------| ---------------------------|
| monitoring-ui-view | <a id="monitoring-ui-view"></a>_Available as of Monitoring v2 9.4.204+_ Provides read-only access to external Monitoring UIs by giving a user permission to list the Prometheus, Alertmanager, and Grafana endpoints and make GET requests to Prometheus, Grafana, and Alertmanager UIs through the Rancher proxy. |

**Comment by aiyengar2** [comment]
@catherineluse added a comment to https://github.com/rancher/docs/pull/3179#pullrequestreview-637232071.
