### ISSUE TITLE
Can not scroll right. 

### ISSUE THREAD

**Issue by TheColetrain** [rancher/docs#3110]
**Summary:**
I am unable to either scroll right to read all the text or shrink the page any further to read all the text in the documentation. This issue is persistent throughout all of the rancher documentation. 

**Details:**
I am using a Samsung galaxy note 8 and Google Chrome not in desktop mode. 
I cannot move the screen to the right, perhaps referred to as scroll, to the right to read many of the tables or commands. It doesn't seem to affect the writen documentation. It applies to lists of commands and text box's. 
I cannot shrink the screen to read it either, it allows my to zoom in, but stops at a point when I try and zoom out. 

If I use "desktop mode" I can see all of the text box's and drop downs but lose access to other items, menu bars I believe. 

Toggling it back and forth makes the page reset and I can not resume where I left off. 

Thanks in advance.

**Comment by TheColetrain** [comment]
![Uploading Screenshot_20210315-211033_Chrome.jpg…]()

**Comment by TheColetrain** [comment]
![Uploading Screenshot_20210315-211033_Chrome.jpg…]()

**Comment by btat** [comment]
No longer applicable on new site.
