### ISSUE TITLE
[Rancher2] Clarify node role requirements for RKE provisioned cluster

### ISSUE THREAD

**Issue by dbason** [rancher/docs#3126]
**Request Summary:**
In Rancher versions >= 2.5.6 RKE clusters won't begin provisioning until all 3 node roles (worker,etcd,controlplane) are present.  Previously etcd and controlplane nodes would be provisioned without the presence of worker nodes.  We should probably highlight this behaviour in the docs.

gz#15970

**Comment by catherineluse** [comment]
Closing because it is addressed in https://github.com/rancher/docs/issues/3126
