### ISSUE TITLE
[Rancher2] Two docs dissagree on the pre-req

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#3129]
**Request Summary:**
Regarding:
- https://rancher.com/docs/rancher/v2.x/en/cluster-admin/volumes-and-storage/out-of-tree-vsphere/
- https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/cloud-providers/vsphere/out-of-tree/

These two docs disagree on the prereq vSphere version.  I believe it has to do with the two things.  We weren't able to test thoroughly on 6.7U3 and I've heard there may be issues provisioning volumes.  Basically, we've tested it all on v7.0U11.  @bmdepesa helped me out on that one.

See: https://github.com/rancher/rancher/issues/23357 for the testing summaries

Opening an issue rather than 'fixing' it myself in case my data is outdated or I misunderstood something here

**Comment by Tejeev** [comment]
**Request Summary:**
Regarding:
- https://rancher.com/docs/rancher/v2.x/en/cluster-admin/volumes-and-storage/out-of-tree-vsphere/
- https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/cloud-providers/vsphere/out-of-tree/

These two docs disagree on the prereq vSphere version.  I believe it has to do with the two things.  We weren't able to test thoroughly on 6.7U3 and I've heard there may be issues provisioning volumes.  Basically, we've tested it all on v7.0U1. @bmdepesa helped me out on that one.

See: https://github.com/rancher/rancher/issues/23357 for the testing summaries


Opening an issue rather than 'fixing' it myself in case my data is outdated or I misunderstood something here

**Comment by ansilh** [comment]
Based on the information in the test, below two features were enabled only on vSphere 7.0 U+ and we tested these two on `v7.0U11.`

- Storage -> Enable migration of volumes provisioned by in-tree vSphere provider to CSI
- Migration -> Enable CSI Volume Resizer 

In this case, can we say the pre-requisite in the Helm chart's `README`  is still valid when we disable these two features?
Cc: @bmdepesa

**Comment by catherineluse** [comment]
Closing this issue because I think it's been fixed already. Couldn't find references to 6.7U3 in the docs.
