### ISSUE TITLE
Document CVE Image Scanning - Mirroring and fix one CVE issue

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#3138]
https://github.com/rancher/rancher/issues/29893
Point of contact: Ricky

**Comment by catherineluse** [comment]
Closing because the only unfinished part of the work is being tracked in https://github.com/rancher/docs/issues/3399

**Comment by btat** [comment]
Reopening as feature is being delayed from 2.6.0 to 2.6.x.

When the time comes, updates from https://github.com/rancher/docs/pull/3364 should be reapplied.

**Comment by cbron** [comment]
Can I be added as reviewer when that PR gets made. I was still planning on reviewing initial changes, and in future it might change.

**Comment by btat** [comment]
Removing 2.6.4 milestone as per https://github.com/rancher/docs/issues/3399#issuecomment-1061942553

**Comment by btat** [comment]
Closing as only remaining part is tracked in https://github.com/rancher/rancher-docs/issues/91.
