### ISSUE TITLE
Document Fleet updates

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#3145]
https://suse.okta.com/login/login.htm?fromURI=%2Fapp%2Fzendesk%2Fexk7ja185qZMnagJx357%2Fsso%2Fsaml%3FRelayState%3Dhttps%253A%252F%252Francher.zendesk.com%252Fagent%252Ftickets%252F14091%26brand_id%3D1685747%26SAMLRequest%3DfZFLb8IwEITv%252FArLdyd2QqFYJCgCVUKiVQVtD70ZZyui%252BkG9Dn38%252Boa0SPRQ%250Arrszmtlvp7MPa8gBAjbeFVQknM7KwRSVNXtZtXHn1vDWAkbS6RzKflHQNjjp%250AFTYonbKAMmq5qW5XMku43AcfvfaGnlkuOxQihNgVoGS5KOjREFim8mw8yjWb%250AjGvFhIAtUzDhbJTprbgSIt9y0ekRW1g6jMrFgmY8E4wPGR8%252FiIkcXkueP1Py%250AdLquy6KkOoXNvcPWQthAODQaHtergu5i3KNM06Cc3kFIvsDVgK%252BJ9jZVWgNi%250AemxHy56Q7NNDecE1Tc%252BFv1zvOgLLxb03jf4klTH%252BfR5ARShoDC1QcuODVfF%252F%250AZiIR%252FaSp2UsvlWBVY6q6Dl1DmpY%252FqX8fWA6%252BAQ%253D%253D%250A

Point of contact: Kinara/Daishan

- basic auth for helm repos in fleet/rancher CD
- fleet agent working behind proxy

**Comment by catherineluse** [comment]
May need basic auth for helm repos in rancher

**Comment by catherineluse** [comment]
Closing this issue because Daishan said that he already wrote the docs and I'll review them separately

**Comment by catherineluse** [comment]
These changes were made to the Fleet documentation https://github.com/rancher/fleet/pull/350

**Comment by catherineluse** [comment]
I closed this issue because I thought no Rancher docs changes were needed. But we do need to update the Rancher docs.

Jan's feedback:

The proxy settings for fleet agent are a cluster level configuration using a new UI field available since 2.5.8 (Agent Environment Variables).

The steps QA used to validate the feature: https://github.com/rancher/rancher/issues/29993#issuecomment-782766995

Specifically we need to call out the required NO_PROXY exceptions. If they are not configured correctly then the fleet agent will not work.
127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local

**Comment by catherineluse** [comment]
@slickwarren @janeczku 

I've added this to the docs about setting up Fleet to work with a proxy. Is this accurate?


_Available as of v2.5.8_

In this sections, you'll learn how to enable Fleet in a setup that has a Rancher server with a public IP and a registered K3s cluster that has no public IP, but is configured to use a proxy.

Rancher does not establish connections with registered downstream clusters. The Rancher agent deployed on the downstream cluster must be able to establish the connection with Rancher.

To set up Fleet to work behind a proxy, you will need to set the **Agent Environment Variables* * for the downstream cluster. These are cluster-level configuration options.

To add the environment variable,

1. In the Rancher UI, go to the cluster view for the registered K3s cluster that needs to use a proxy.
1. Click **&#8942; > Edit**.
1. Click **Advanced Options.**
1. Click **Add Environment Variable.**
1. Enter environment variables according to the table below.
1. Click **Save.**

**Result:** The Fleet agent works behind a proxy.

### Required Environment Variables

When adding Fleet agent environment variables for the proxy, replace <PROXY_IP> with your private proxy IP.

| Variable Name | Value |
|------------------|--------|
| `HTTP_PROXY` | http://<PROXY_IP>:8888 |
| `HTTPS_PROXY | http://<PROXY_IP>:8888
| `NO_PROXY`     | 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local |

**Comment by slickwarren** [comment]
I think these instructions look good for public downstream clusters.  Here are some clarifications:

* It would be worth adding that these can be configured for **any cluster type** (rke, k3s, imported, custom, etc.). basically anywhere in the UI that we have the option to add environment vars, proxy should also work.  
* Also, this can be done on create through rancher (you don't have to wait for the clusters to come to active, then edit. You can directly add these environment vars on create).  


One more note, if you're proxying to a _private node or cluster_, that setup should have `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` as global (exported) vars on the nodes themselves, in addition to adding them to rancher when provisioning the cluster (this is typically an import/custom cluster case). [more on that here](https://github.com/rancher/rancher/issues/29993#issuecomment-782766995) if that's a use case you think should be added.

**Comment by catherineluse** [comment]
Modifying the registration YAML is no longer required, right?

Now I've got this:

----------------------

---
title: Using Fleet Behind a Proxy
weight: 3
---

_Available as of v2.5.8_

In this section, you'll learn how to enable Fleet in a setup that has a Rancher server with a public IP a Kubernetes cluster that has no public IP, but is configured to use a proxy.

Rancher does not establish connections with registered downstream clusters. The Rancher agent deployed on the downstream cluster must be able to establish the connection with Rancher.

To set up Fleet to work behind a proxy, you will need to set the **Agent Environment Variables* * for the downstream cluster. These are cluster-level configuration options.

Through the Rancher UI, you can configure these environment variables for any cluster type, including registered and custom clusters. The variables can be added while editing an existing cluster or while provisioning a new cluster.

For public downstream clusters, it is sufficient to [set the required environment variables in the Rancher UI.](#setting-environment-variables-in-the-rancher-ui)

For private nodes or private clusters, the environment variables need to be set on the nodes themselves. Then the environment variables are configured from the Rancher UI, typically when provisioning a custom cluster or when registering the private cluster. For an example of how to set the environment variables on Ubuntu node in a K3s Kubernetes cluster, see [this section.](#setting-environment-variables-on-private-nodes)

# Required Environment Variables

When adding Fleet agent environment variables for the proxy, replace <PROXY_IP> with your private proxy IP.

| Variable Name | Value |
|------------------|--------|
| `HTTP_PROXY` | http://<PROXY_IP>:8888 |
| `HTTPS_PROXY` | http://<PROXY_IP>:8888
| `NO_PROXY`     | 127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local |

# Setting Environment Variables in the Rancher UI

To add the environment variable to an existing cluster,

1. In the Rancher UI, go to the cluster view for Kubernetes cluster that needs to use a proxy.
1. Click **&#8942; > Edit**.
1. Click **Advanced Options.**
1. Click **Add Environment Variable.**
1. Enter the [required environment variables](#required-environment-variables)
1. Click **Save.**

**Result:** The Fleet agent works behind a proxy.

# Setting Environment Variables on Private Nodes

For private nodes and private clusters, the proxy environment variables need to be set on the nodes themselves, as well as configured from the Rancher UI.

This example shows how the environment variables would be set up on an Ubuntu node in a K3s Kubernetes cluster:

```
ssh -o ForwardAgent=yes ubuntu@<public_proxy_ip>
ssh <k3s_ip>
export proxy_private_ip=<private_proxy_ip>
export HTTP_PROXY=http://${proxy_private_ip}:8888
export HTTPS_PROXY=http://${proxy_private_ip}:8888
export NO_PROXY=127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
```

**Comment by slickwarren** [comment]
Right. I think this looks good
