### ISSUE TITLE
Document SeLinux support for Logging v2

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#3150]
Point of contact: Colleen

**Comment by catherineluse** [comment]
SeLinux support is in v2.5.8. Bala to update the support maintenance terms to reflect this.

**Comment by SheilaghM** [comment]
Caleb's comment: The fix going into 2.5.8 is very limited: only for logging v2, and only for rhel/centos 7 and 8.

**Comment by catherineluse** [comment]
Should we say "Logging v2 was tested with SeLinux on RHEL/CentOS 7 and 8."?
