### ISSUE TITLE
[Rancher2] Add Monitoring v2 SSL instructions for email/webhook receivers

### ISSUE THREAD

**Issue by slickwarren** [rancher/docs#3154]
**Request Summary:**

We have added ssl options for alerts in monitoring v2, namely webhooks and email alerts. However, we need to add some clear instruction to documentation so that users can easily use this feature.
<img width="1219" alt="Screen Shot 2021-03-31 at 4 26 12 PM" src="https://user-images.githubusercontent.com/16691014/113223354-d50d2180-923d-11eb-86ac-1f597a13475e.png">
it seems like [this might be a good place](https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/v2.5/#enable-monitoring) to add documentation but if you find a better location please add this there. 

**Details:**
In order for ssl to be used for alerts, the user must do the following: 
* add the `ca`, `cert`, and `key` files to a secret in the `cattle-monitoring-namespace`. If this namespace doesn't exist, please create it first, then add secrets there
* deploy (or redeploy) monitoring, adding the secrets as `additional secrets` under the `alerts` section via the UI, or `alertmanager.alertmanagerSpec.secrets` via yaml. 

<img width="650" alt="Screen Shot 2021-03-31 at 4 16 29 PM" src="https://user-images.githubusercontent.com/16691014/113223809-ddb22780-923e-11eb-833f-25e1c2206234.png">

* navigate to the `receivers` section of monitoring, add a ssl-enabled receiver such as webhooks or email
* fill in all relevant information for this receiver.  under ssl, enter the file paths to each `ca`, `cert`, and `key` . It will look something like `/etc/alertmanager/secrets/<name-of-file-in-secret>`

**Comment by btat** [comment]
Closed via https://github.com/rancher/docs/pull/3208
