### ISSUE TITLE
[Rancher2] document the new behavior when uninstalling Rancher in HA mode

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/docs#3159]
**Request Summary:**

A helm post-delete-hook is added to Rancher's helm chart, which will do some cleanup when Rancher is uninstalled from the cluster. 

All the `helm-operation-*` pods and the following apps will be deleted:
- fleet
- fleet-agent
- rancher-operator
- rancher-webhook

PR in rancher/rancher: https://github.com/rancher/rancher/pull/31670

**Comment by SheilaghM** [comment]
Checking with PM to see if this actually needs to be documented.

**Comment by SheilaghM** [comment]
Discussion with PM:  Yes, need to document.  in 2.5 we added pieces under the Rancher hood - Operator, Webhook, Fleet.  Jaq's work cleans those up when Rancher is uninstalled.  Bill would like a small section about this in the "Rancher is No Longer Needed" section with a caveat/note that it does not remove custom resources or custom spaces and those will need to be removed manually.
