### ISSUE TITLE
[Rancher2] document the new app rancher-alerting-drivers

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/docs#3173]
A new chart named `rancher-alerting-drivers` will be released along with the Rancher v2.5.8 release. 
The chart will show as `Alerting Drivers` in Rancher's builtin catalog in the Cluster Explorer UI

![image](https://user-images.githubusercontent.com/6218999/114248678-222f7880-994d-11eb-81d2-cff3228b839e.png)

This chart installs one or more [Alertmanager Webhook Receiver Integrations](https://prometheus.io/docs/operating/integrations/#alertmanager-webhook-receiver).
Those Drivers can be targeted by an existing deployment of Alertmanager to send alerts to notification mechanisms that are not natively supported.

Currently, it supports the following Drivers:
- Microsoft Teams, based on [prom2teams](https://github.com/idealista/prom2teams)
- SMS, based on [Sachet](https://github.com/messagebird/sachet)

**Comment by btat** [comment]
Related links:
https://github.com/rancher/rancher/issues/29951
https://github.com/rancher/charts/pull/1085

**Comment by btat** [comment]
Closed via https://github.com/rancher/docs/pull/3209 and https://github.com/rancher/docs/pull/3228
