### ISSUE TITLE
[K3s] CIS 1.6 Hardening Guide and Self Assessment Guide

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#3184]
**Request Summary:**
Add guides for k3s CIS 1.6 to https://rancher.com/docs/k3s/latest/en/security/

**Details:**

**Comment by davidnuzik** [comment]
Once complete, we should update the security page as well as indicated here: https://github.com/rancher/docs/issues/3185

**Comment by catherineluse** [comment]
Closing because the K3s hardening and self assessment guides are complete and we linked to them here: https://rancher.com/docs/rancher/v2.5/en/security/rancher-2.5/#k3s-guides
