### ISSUE TITLE
[Security page] Once RKE2 benchmark/hardening docs are done, link to them on the main page

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#3185]
**Summary:**
Once https://github.com/rancher/docs/issues/3184 and/or https://github.com/rancher/rke2/issues/876 have been completed, they should be linked to on the https://rancher.com/docs/rancher/v2.x/en/security/rancher-2.5/ page as well.

**Details:**

**Comment by catherineluse** [comment]
Already linked to the K3s guides.

**Comment by catherineluse** [comment]
Addressed by https://github.com/rancher/docs/pull/3290
