### ISSUE TITLE
[RKE] Remove iptables kernel modules from RKE requirements for CentOS 8.x and RHEL 8.x systems

### ISSUE THREAD

**Issue by axeal** [rancher/docs#3187]
**Summary:**

The list of kernel modules in the RKE requirements documentation (https://rancher.com/docs/rke/latest/en/os/#general-linux-requirements) should not include iptables modules for CentOS 8.x and RHEL 8.x systems (these now use netfilter)

**Details:**

The list of kernel modules that should be enabled in the RKE requirements documentation includes iptable_filter iptable_nat iptable_mangle iptable_raw

CentOS 8.x and RHEL 8.x systems use netfilter and enabling these iptables-legacy kernel modules breaks cluster networking.

**Comment by catherineluse** [comment]
Closing this issue because I believe it is addressed in this PR. https://github.com/rancher/docs/pull/3292
