### ISSUE TITLE
[K3s] Document default SUC deployment with Rancher k3s upgrades

### ISSUE THREAD

**Issue by dkeightley** [rancher/docs#3190]
**Request Summary:**
When changing the k3s version for a cluster in the Rancher UI/API, the system upgrade controller is automatically deployed as a convenience and manages the plans to perform the change. The docs currently suggest the SUC is deployed manually, which can be confusing if a mixture of upgrade options are used.

For eg, an upgrade in the Rancher UI is performed, later an upgrade is performed by rolling in a new k3s binary, in this scenario the new k3s binary is unexpectedly downgraded to match the version stored in Rancher and the plan.

This may better suit the Rancher docs, but relates to k3s.

gz#16344

**Comment by fapatel1** [comment]
This is an ask for support @catherineluse, any chance of getting this scheduled? cc: @sirredbeard
