### ISSUE TITLE
[Rancher2]  append the flag --no-hooks to helm template command for airgap installation 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/docs#3226]
**Request Summary:**

in v2.5.8, we update the Rancher chart to auto-delete leftovers after uninstalling Rancher from the cluster: https://github.com/rancher/rancher/issues/30924
This feature is implemented based on [Helm Chart Hooks](https://helm.sh/docs/topics/charts_hooks/) 

However, when we install Rancher in the airgap environment, Helm is only used to generate the YAML files where the post-delete-hook files are also generated.  

We should exclude those files by adding the `--no-hooks` to the `helm template` command.

I found 2 places where we need to update the `helm template` command but there might be more:
- https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/air-gap/install-rancher/#option-a-default-self-signed-certificate
- https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/air-gap/install-rancher/#option-b-certificates-from-files-using-kubernetes-secrets

The change should be something like this 
 
```
	  helm template rancher ./rancher-<VERSION>.tgz --output-dir . \
+++    --no-hooks # prevent files for Helm hooks from being generated \
	   --namespace cattle-system \
	   --set hostname=<RANCHER.YOURDOMAIN.COM> \
	   --set certmanager.version=<CERTMANAGER_VERSION> \
	   --set rancherImage=<REGISTRY.YOURDOMAIN.COM:PORT>/rancher/rancher \
	   --set systemDefaultRegistry=<REGISTRY.YOURDOMAIN.COM:PORT> \ # Available as of v2.2.0, set a default private registry to be used in Rancher
	   --set useBundledSystemChart=true # Available as of v2.3.0, use the packaged Rancher system charts
```

**Comment by catherineluse** [comment]
@jiaqiluo Can you please review the updated commands in my PR? The PR is ugly because I had to reorganize some things, but the changed commands are in these sections:

- docs on upgrading Rancher on Kubernetes in an air gap environment: https://staging.rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/upgrades/#3-upgrade-rancher
- air gapped Helm CLI install docs: https://staging.rancher.com/docs/rancher/v2.5/en/installation/other-installation-methods/air-gap/install-rancher/#3-render-the-rancher-helm-template
- The feature flag docs: https://staging.rancher.com/docs/rancher/v2.5/en/installation/resources/feature-flags/#rendering-the-helm-chart-for-air-gap-installations

**Comment by jiaqiluo** [comment]
@catherineluse   I have reviewed the above 3 pages and here are my feedbacks: 

1. The indent of the helm command has multiple different versions. Can you unify the format across all pages? 
For example,  [this section](https://staging.rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/upgrades/air-gap-upgrade/#option-a-default-self-signed-certificate)
<img width="941" alt="Screen Shot 2021-05-04 at 10 19 10 AM" src="https://user-images.githubusercontent.com/6218999/117043584-479c7180-acc2-11eb-9ecc-f3007bec3a9d.png">

And [this section](https://staging.rancher.com/docs/rancher/v2.5/en/installation/other-installation-methods/air-gap/install-rancher/#2-render-the-rancher-template)
![image](https://user-images.githubusercontent.com/6218999/117044545-68b19200-acc3-11eb-9b2d-8fc5cb6b3d10.png)



2. In[ this section](https://staging.rancher.com/docs/rancher/v2.5/en/installation/resources/feature-flags/#rendering-the-helm-chart-for-air-gap-installations), it looks like the `kuebctl install` and `docker install` are the parent-level tabs and should not be listed here.  
<img width="894" alt="Screen Shot 2021-05-04 at 10 31 55 AM" src="https://user-images.githubusercontent.com/6218999/117045172-12911e80-acc4-11eb-92fa-a2c1fd8cd1f0.png">


3. For the name of tabs, both `Rancher v2.5.8` and `Rancher v2.5.8+` are used. Can you unify them into one?

**Comment by catherineluse** [comment]
I've fixed the formatting errors in this commit https://github.com/rancher/docs/commit/e3ce36d0b73a5482a25e7c04cc3d1adb1244b0a0

**Comment by Martin-Weiss** [comment]
Is it possible to add the --no-hooks parameter in case we deploy Rancher as helmchart CRD with the helm operator in RKE2?
