### ISSUE TITLE
[Rancher2] Clarify Logging v2 Configuration

### ISSUE THREAD

**Issue by oxr463** [rancher/docs#3244]
**Request Summary:**

When reading the Logging v2 docs, one of our customers assumed that all of the configurations were to be done via the command line / YAML. Is it possible to add screenshots of the new UI, or at least provide some kind of clarification that this can be accomplished via the Cluster Explorer UI? 

**Details:**

See: https://rancher.com/docs/rancher/v2.5/en/logging/#output-to-splunk

gz#16866

**Comment by catherineluse** [comment]
I have updated the logging configuration docs to better advertise the fact that the logging UI was improved:

- https://staging.rancher.com/docs/rancher/v2.5/en/logging/custom-resource-config/flows/
- https://staging.rancher.com/docs/rancher/v2.5/en/logging/custom-resource-config/outputs/

**Comment by nickgerace** [comment]
The changes look great! I _love_ the tabbed approach to versions too. I have only two comments on this:

1. For the tabbed version boxes: the Flows and Outputs tab names are not consistent. We may want to decided on one, such as `Rancher v2.5.0-v2.5.7`, or `Before Rancher 2.5.8`, etc.
2. Sometimes, CRDs appear in lowercase, such as `output`. We may want to make a consistent standard for CRD names. Perhaps, we may even want them in `plaintext`.

**Comment by catherineluse** [comment]
I've addressed the feedback in https://github.com/rancher/docs/pull/3295
