### ISSUE TITLE
Document support for Keycloak using OIDC

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#3256]
Issue: https://github.com/rancher/rancher/issues/30280
Point of contact: Brenda

**Comment by brendarearden** [comment]
A specific note should be made that users migrating from SAML keycloak to OIDC keycloak will need to re-do the rancher user permissions. The permissions will not migrate automatically.

**Comment by catherineluse** [comment]
Since Izaac tested the Keycloak auth I think it would be helpful to see if he has feedback as well.

**Comment by izaac** [comment]
We should confirm if the nested groups feature that supported by other auth providers will be or not supported by Keycloak OIDC
https://github.com/rancher/rancher/issues/33337#issuecomment-880212646

**Comment by btat** [comment]
Closed via https://github.com/rancher/docs/pull/3358
