### ISSUE TITLE
Document cluster templates with RKE2

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#3258]
Issue: https://github.com/rancher/rancher/issues/30099
Point of contact: Daishan

**Comment by catherineluse** [comment]
related
https://github.com/rancher/docs/issues/3369
https://github.com/rancher/rke2/issues/1215

**Comment by deniseschannon** [comment]
One of the things around using cluster templates for 2.6 is that in order to use a template as part of continuous delivery/gitops, the template/cluster definition would need to be deployed in the fleet-local namespace of the local cluster
