### ISSUE TITLE
[Rancher2] Make requirement for TLS termination on loadbalancer for Authorized Cluster Endpoint (ACE) explicit

### ISSUE THREAD

**Issue by axeal** [rancher/docs#3261]
**Request Summary:**

When configuring a loadbalancer with Authorized Cluster Endpoint, it is required to perform TLS termination on the loadbalancer (the user can either use a public CA signed cert, in which case they just define the FQDN in the ACE configuration, or they can also define the private CA certificate, in case of using a private CA signed certificate). This requirement to perform TLS termination is not explicit in the ACE [architecture docs](https://rancher.com/docs/rancher/v2.5/en/overview/architecture-recommendations/#architecture-for-an-authorized-cluster-endpoint), leading to some confusion that Authorized Cluster Endpoint can be enabled via a Loadbalancer without TLS termination, i.e. Layer-4 loadbalancing, with TLS termination on the kube-apiserver using the cluster CA, which is not possible.

**Comment by catherineluse** [comment]
Addressed in https://github.com/catherineluse/docs/commit/1d30f699a0c29f58e5a44769b738bd4600a8e1ab
