### ISSUE TITLE
[K3s] Revise 'how it works' diagram

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#3268]
We need to update this diagram based on feedback:

> The How It Works diagram isn’t really accurate and it keeps confusing users. It makes it look like servers lack kubelet and containerd and therefore cannot run pods, which leads to them asking how to run server and agent on the same node. 
https://k3s.io/images/how-it-works-k3s.svg

**Comment by brandond** [comment]
In terms of what to change:
- change the server "tunnel proxy" box to say “supervisor”
- add kube-proxy, flannel, kubelet, containerd, and pods from Agent to the Server. Kubelet and Kube-proxy on the server should have arrows pointing directly to API Server instead of Tunnel Proxy.

**Comment by lvuch** [comment]
<img width="1089" alt="Screen Shot 2021-05-17 at 3 03 53 PM" src="https://user-images.githubusercontent.com/3013118/118562218-22c3e780-b721-11eb-893d-7c758d44e4e2.png">
@brandond @catherineluse please review

**Comment by brandond** [comment]
Looking much better! A couple more tweaks:
* Only the server side of 'tunnel proxy' needed to be changed to 'supervisor' - on the agent it should still say 'tunnel proxy'
* On the server side, 'kube proxy' should be connected directly to 'api server'

**Comment by brandond** [comment]
I missed this on Slack, but @lvuch sent me this last week and it looks good!
<img width="728" alt="Screen Shot 2021-05-18 at 4 00 18 PM" src="https://user-images.githubusercontent.com/370103/119732554-2fd18c80-be2d-11eb-9568-53e51ebee4f0.png">

**Comment by lvuch** [comment]
Final svg sent via slack

**Comment by jtravee** [comment]
Closed; moved to https://github.com/rancherlabs/k3s-website/pull/64.
