### ISSUE TITLE
Update search that it searches in specific versions

### ISSUE THREAD

**Issue by ganomi46** [rancher/docs#3314]
**Summary:**
Currently search searches through all website often suggesting results from  EOL versions (archived versions). We should provide choice to search in specific doc version to narrow down the search.

**Details:**
There is no specific documentation search. The search is used for searching the whole website. We should improve the search that customers can search in specific versions. Many of the first results go for RancherOS. It is very cumbersome to use that search.

**Comment by btat** [comment]
Address via move to new site.
