### ISSUE TITLE
Image scanning

### ISSUE THREAD

**Issue by rmweir** [rancher/docs#3354]
**Description:**
Add docs explaining image scanning:
* the url for the repo and the github page where information is published
* how it works
* the fact the results are produced by Trivy, which may produce different results than other scanning tools
* how often it's updated
* what information will be displayed
* an overview of what to expect once CVE's are found.
* Add to istio docs that istio 1.5 is deprecated
* Add to pipeline docs that it is deprecated

**Comment by catherineluse** [comment]
Closing because this all done except for adding the URL, which is tracked in https://github.com/rancher/docs/issues/3399.
