### ISSUE TITLE
[Rancher2] [rke2 install tutorial] Update to mention 1.20 channel during install

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#3361]
**Summary:**

We should update https://rancher.com/docs/rancher/v2.5/en/installation/resources/k8s-tutorials/ha-rke2/ such that the curl install example includes the necessary environment variable and value to pull down the 1.20 line, not 1.21. This is for Rancher 2.5 docs.

This is because only Rancher 2.6 will be supporting Kubernetes 1.21 and up -- Rancher 2.5 should not use 1.21. The K3s/RKE2 team will be marking v1.21.2+rke2r1 as stable on July 7th (assuming there are no serious issues that should prevent this). When that happens, 1.21 will be stable and thus the default version used when installing (if following this docs page as it is written today).

**Details:**

What we should do is:

Modify this section to be like:
```
curl -sfL https://get.rke2.io | INSTALL_RKE2_CHANNEL=v1.20 sh -
systemctl enable rke2-server.service
systemctl start rke2-server.service
```

We can publish this now, rather than waiting later until 1.21 release. But it should get published before July 7th.

**Comment by davidnuzik** [comment]
@ShylajaDevadiga @rancher-max question for you two:
For RHEL-like OS'es do we need to specify anything else here? Or is just INSTALL_RKE2_CHANNEL=v1.20 enough?

**Comment by ShylajaDevadiga** [comment]
@davidnuzik Passing just INSTALL_RKE2_CHANNEL=v1.20 is enough

**Comment by catherineluse** [comment]
Closing because https://github.com/rancher/docs/pull/3362 was merged
