### ISSUE TITLE
[Rancher2] [rancher-backup] call out that backup should be restored into the same Rancher version 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/docs#3375]
In the [documentation](https://rancher.com/docs/rancher/v2.x/en/backups/v2.5/) for the rancher backup feature which uses the rancher-backup app, we should call it out that when restoring a backup into a new Rancher setup, the version of the new setup should be the same as the one where the backup is made. 

For example, if you make a backup of Rancher v2.5.9, you can only restore it into another v2.5.9 setup.

**Comment by catherineluse** [comment]
Addressed by https://github.com/rancher/docs/commit/60203446ff7a1755c3e18dbac48800a0a495911c
