### ISSUE TITLE
docker dev environment: link in the top nav doesn't work

### ISSUE THREAD

**Issue by 0xErnie** [rancher/docs#3376]
**Summary:**
When cloning into master and starting `./scripts/dev` the webserver serves the start page of rancher docs, but when following links to `http://localhost:9001/docs/` I just get `404 page not found`

**Details:**
Let me know if you need any more info or if am doing something wrong.
I am running Docker Desktop 3.5.1 on Mac OS 11.4 (20F71).

**Comment by catherineluse** [comment]
The Docs link in the top nav won't work. The reason has to do with the Rancher website being built from different Git repositories.

However, if you click the card to go to the docs, you will go to a link that should work, such as `http://localhost:9001/rancher/v2.5/en/`.

I'll update the docs readme to reflect this.
