### ISSUE TITLE
code block in listing is broken in "Set up RKE2 for Rancher"

### ISSUE THREAD

**Issue by 0xErnie** [rancher/docs#3378]
**Summary:**
It seems like it fails to render a code listing inside a numbered list.

In [the article](https://rancher.com/docs/rancher/v2.5/en/installation/resources/k8s-tutorials/ha-rke2/)  the is list starting with  _To join the rest of the nodes_.
Link to the code: [docs/rancher/v2.5/en/installation/resources/k8s-tutorials/ha-rke2/](https://github.com/rancher/docs/blame/8959dffc48a45d26750e5b0d86835e128b2dc5e1/content/rancher/v2.5/en/installation/resources/k8s-tutorials/ha-rke2/_index.md#L46-L61)

I am not shure if this is a upstream bug in hugo or an error in the markdown code, so I am posting this here first.

**Details:**
````
1. To join the rest of the nodes, you need to configure each additional node with the same shared token or the one generated automatically. Here is an example of the configuration file:
```
token: my-shared-secret
server: https://<DNS-DOMAIN>:9345
tls-san:
  - my-kubernetes-domain.com
  - another-kubernetes-domain.com
```
After that you need to run the installer and enable then start rke2
```
curl -sfL https://get.rke2.io | sh -
systemctl enable rke2-server.service
systemctl start rke2-server.service
```

1. Repeat the same command on your third RKE2 server node.
````

<img width="773" alt="Screenshot of the redered markdown code" src="https://user-images.githubusercontent.com/234937/124101581-cb26d480-da5f-11eb-8f5b-e6d5b3bf8faa.png">

When adding a newline over the code block it gets rendered, but the listing is broken and restarts the counter.

Notes:
Github renders the block, but then restarts the counter:
<img width="1054" alt="Screenshot of the github redered markdown code" src="https://user-images.githubusercontent.com/234937/124103900-088c6180-da62-11eb-9202-03d9dc3b0ccc.png">

**Comment by btat** [comment]
Closed via https://github.com/rancher/docs/pull/3379
