### ISSUE TITLE
[Rancher2] Update v2.5 CA update doc to include Force Update of Fleet Clusters

### ISSUE THREAD

**Issue by axeal** [rancher/docs#3381]
**Request Summary:**
fleet-agents in Rancher managed clusters store a kubeconfig used to connect to Rancher proxied kube-api in the fleet-agent secret of the fleet-system Namespace. The kubeconfig contains a certificate-authority-data block containing the Rancher CA. Therefore when changing the Rancher CA this needs to be updated in order to allow the fleet-agent in downstream clusters to successfully connect to Rancher. This can be done by selecting 'Force Update' for the clusters within the Continuous Delivery view of the Rancher Explorer UI as a fifth step, after `4. Reconfigure Rancher agents to trust the private CA`

**Details:**
Related issue in https://github.com/rancher/rancher/issues/33323

**Comment by divya-mohan0209** [comment]
Hello @axeal, would this fit in best in the Troubleshooting section [here](https://rancher.com/docs/rancher/v2.5/en/deploy-across-clusters/fleet/). Or were you intending for it to be placed somewhere else?

**Comment by axeal** [comment]
@divya-mohan0209 Apologies for unhelpfully not providing a link initially, I was referring to the Rancher private CA update documentation at https://rancher.com/docs/rancher/v2.6/en/installation/resources/update-ca-cert/

**Comment by divya-mohan0209** [comment]
Hey @axeal , not a problem at all. I've added this to both v 2.6 & v2.5 docs and have submitted a PR. Please review & let me know your comments, if any.
