### ISSUE TITLE
Document ECR plugin in RKE

### ISSUE THREAD

**Issue by superseb** [rancher/docs#3401]
Docs for https://github.com/rancher/rancher/issues/28693

Contact: @ibrokethecloud

**Comment by dkeightley** [comment]
Just a note to help clarify this further

There are two areas where the credentials are used:
  - kubelet - addons, custom workloads etc, the instance profile or credentials are used by the downstream cluster nodes 
  - pulling system images (directly via docker) - bootstrap, upgrades, reconcile, the instance profile or credentials are used by nodes running `rke` or running the Rancher pods

This could be confusing and raise issues while creating a new cluster, or issues pulling images during reconcile/upgrades, so worthy of noting

In both of these areas the [configuration snippet](https://github.com/rancher/rancher/issues/28693#issuecomment-895624996) adding hard-coded credentials in environment variables for the `kubelet` and credentials under `credentialPlugin` are only needed if the node:
 - Is not an EC2 instance
 - Or, is EC2 but doesn't have an instance profile configured
 - Or, does have all the above, but no permissions for ECR (not sure why you would do this)

From a security point of view it's important to highlight that using an instance profile to provide the ECR credentials (when running in EC2, etc.) is a much more secure approach, the instance profile will be autodetected and use these by default (using the Go AWS SDK credential lookup process).
