### ISSUE TITLE
[Rancher2] 

### ISSUE THREAD

**Issue by Alexsaphir** [rancher/docs#3411]
**Request Summary:**
Correct a typo

**Details:**
https://rancher.com/learning-paths/how-to-manage-kubernetes-with-kubectl/

at the end inside "Additional Reference Information"
a '-' is missing for the command of "List pods for all namespace"
it should be `kubectl get pods --all-namespaces` not `kubectl get pods -all-namespaces`

**Comment by btat** [comment]
Fix has been merged via another repo.
