### ISSUE TITLE
[Rancher2] Monitoring v1 k8s limited to <= 1.20.x

### ISSUE THREAD

**Issue by cbron** [rancher/docs#3414]
Note in docs that v1 doesn't work on k8s 1.21 yet. This will be release noted also, so if we typically only release note those things then we can skip this issue. 
https://github.com/rancher/rancher/issues/33465

**Comment by jiaqiluo** [comment]
### The explanation for why monitoring v1 does not work on the 1.21 cluster

Grafana sends the request for querying metrics to Prometheus and includes a token in its request, the container `prometheus-agent` determines if the request is authorized by checking if the token from the request is the same as the token in the Secret for `prometheus-agent`’s ServiceAccount. If they are different, `prometheus-agent` will try to create a new `apiContext` in which the `namespaceSet` is where the Grafana’s token comes from. https://github.com/rancher/prometheus-auth/blob/e3a74d01c885fdcd1b46a96735f5ee69631ed29e/pkg/agent/http.go#L69-L85

Those two above-mentioned tokens are the same in the k8s 1.20 cluster, but not in the 1.21 cluster. `prometheus-agent` also fails to find the `namespaceSet` for that token from the request.

In 1.21, the feature [BoundServiceAccountTokenVolume](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#bound-service-account-token-volume) is enabled by default. As the result, although the pods are in the same namespace and use the same serviceAccount, they will get different tokens and the tokens are rotated each hour. This breaks the current implantation of the [rancher/prometheus-auth](https://github.com/rancher/prometheus-auth) which is the image used in the container `prometheus-agent`.

**Comment by catherineluse** [comment]
We normally don't document which Kubernetes versions are supported because it is better to use the support terms as the single source of truth. However, if this limitation differs from what is stated in the support terms, we should document it.
