### ISSUE TITLE
[Rancher2] Update Docker version

### ISSUE THREAD

**Issue by davidnuzik** [rancher/docs#3418]
**Request Summary:**

https://rancher.com/docs/rancher/v2.5/en/installation/requirements/installing-docker/ references older Docker version. Looks like in https://github.com/rancher/rancher/issues/30406 we validated newer docker 20.10. Looks like this was supported as of 2.5.6

**Comment by btat** [comment]
Looks this change was only applied to the v2.x directory https://github.com/rancher/docs/pull/3355

**Comment by btat** [comment]
Updated via https://github.com/rancher/docs/pull/3425
