### ISSUE TITLE
[Rancher2] - Document use of --no-hooks when installing/upgrading Rancher on Airgap HA

### ISSUE THREAD

**Issue by izaac** [rancher/docs#3438]
**Request Summary:**

We should document the use of `--no-hooks` during the Rancher Airgap HA which makes use of `kubectl apply` over a Rancher helm template.

**Details:**

Basically the user will end up with `rancher-post-delete` hook throwing `invalid` errors.
The use case is described in this `rancher/rancher` issue: https://github.com/rancher/rancher/issues/34184

`--no-hooks` is basically needed when doing the `helm template`

@jiaqiluo

**Comment by btat** [comment]
Looks like `--no-hooks` was previously added to the `helm template` examples already.

https://github.com/rancher/docs/blob/staging/content/rancher/v2.6/en/installation/install-rancher-on-k8s/upgrades/air-gap-upgrade/_index.md
https://github.com/rancher/docs/blob/staging/content/rancher/v2.6/en/installation/other-installation-methods/air-gap/install-rancher/_index.md
