### ISSUE TITLE
[Rancher2] Avoid using the word "rollback" in the docs - Verification only

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#3442]
A rollback is the same thing as a restore, but with an extra step of changing the Rancher version in the deployment.

To clarify that they are essentially the same thing, we should just use the word restore and avoid saying "rollback."

https://rancher.slack.com/archives/C016F31TPFX/p1628871167089400

**Comment by jtravee** [comment]
Verification only.

**Comment by jtravee** [comment]
Verified that all documentation pertaining to rollbacks explains the need to restore from backup when a rollback is required. Since the two processes do differ, rollback wasn't replaced with restore.
