### ISSUE TITLE
[Rancher2] Need to update port requirements for RKE2 nodes

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/docs#3450]
As part of this ticket (https://github.com/rancher/rancher/issues/34300) we are going to be adding a new port as a part of `rancher-machine` for RKE2 nodes and calico support. Can we add this to the port list/requirements for RKE2 nodes?

**Comment by catherineluse** [comment]
For whoever works on this docs ticket, the part that needs to be updated is:

https://rancher.com/docs/rancher/v2.5/en/installation/requirements/ports/#ports-for-rancher-server-nodes-on-rancherd-or-rke2

(That's a 2.5 docs link but we need to update the equivalent table in the 2.6 docs.)

The table in that accordion needs to have a new row with info from this comment (https://github.com/rancher/rancher/issues/34300#issuecomment-901305349):

- Protocol: TCP
- Port: 5473
- Source: Calico-node pod connecting to typha pod when more than three nodes are deployed
- Description: Required when deploying with Calico. When a cluster is deployed with Calico with more than three nodes, the calico-node pod can't connect to a typha pod.

**Comment by btat** [comment]
Closed via https://github.com/rancher/docs/issues/3463
