### ISSUE TITLE
Rancher Logging Journald path value needs to be documented

### ISSUE THREAD

**Issue by paynejacob** [rancher/docs#3454]
In rancher logging the `systemdLogPath` needs to be configured but the value is not intuitive or easy to predict.  We should add a section to the rancher logging docs to explain what this value is for and how to use it.  See the attached pr for details.

https://github.com/rancher/charts/pull/1420/files

**Comment by catherineluse** [comment]
@jtravee We can talk about this one after the other items in your queue are done

**Comment by btat** [comment]
Closed via #3475
