### ISSUE TITLE
[Rancher2] New Steps for Rolling Back Rancher v2.5.0+

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/docs#3460]
Related Issue: https://github.com/rancher/rancher/issues/34247

**Request Summary:**

The existing steps on [this page for rolling back Rancher in 2.5.0+](https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/rollbacks/#rolling-back-to-rancher-v2-5-0) is not correct anymore. and we need to update it to the following:

step 1: find the deployment Rancher ( either in UI or command line) to scale it down to replica=0.
step 2: restore the backup, which is the same as the existing section [Create the Restore Custom Resource](https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/rollbacks/#create-the-restore-custom-resource)
step 3: run Helm rollback command to roll back rancher to its previous version. 
```
> helm rollback rancher -n cattle-system
```
Note: run `helm history rancher -n cattle-system` to determine which revision you should roll back to if the previous revision is not the target one; run `helm rollback -h` for help.

**Comment by btat** [comment]
Closed via #3477
