### ISSUE TITLE
Document that manage nodes role is different for RKE and RKE2

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#3466]
https://github.com/rancher/rancher/issues/34474

The manage nodes permission for RKE1 meant scaling up and down, deleting, SSH access. Manage nodes for RKE2 means deleting, SSH access. If you want to scale clusters up and down with RKE2, you only need the edit cluster permission.

**Comment by btat** [comment]
Closed via https://github.com/rancher/docs/pull/3472
