### ISSUE TITLE
[Rancher2] Need a docs entry explaining our charts versioning scheme

### ISSUE THREAD

**Issue by aiyengar2** [rancher/docs#3500]
**Request Summary:**

We recently switched to a new versioning scheme starting 2.6.0 for Rancher feature charts, where the version of ~all~ most of the charts are 100.0.0 and `+up` annotations inform the user of what actual chart version they are installing.

I think the methodology we use for versioning charts needs to be explained in the docs so that users can understand what the versioning scheme entails so that they do not perform faulty upgrades.

**Details:**

Specifically we should document the following:
- This new versioning scheme only starts in 2.6
- For users, only two things matters: the major version of the chart and the +up annotation, if included:
  - Major Version is tied to Rancher minor version. When a user upgrades to a new Rancher minor version, they should ensure all their Apps & Marketplace charts are also upgraded to the correct release line for the chart.
    - We should have a table of some kind that shows all the starting major versions (e.g. 100.x.x for Rancher Monitoring, 2.x.x for CIS Benchmark, etc.) based on what we released in 2.6 (documented [here](https://github.com/rancher/rancher/issues/32294))
    - We should also document that any major versions that are less than the ones mentioned above are meant for 2.5 and below only, e.g. users are not advised to be using <100.x.x versions of Monitoring in 2.6.x+
  - For charts that are based on upstreams, the +up annotation should inform the user of what upstream version this Rancher chart is tracking. This should also be considered on upgrades
    - e.g. 100.x.x+up16.6.0 for Monitoring tracks upstream kube-prometheus-stack 16.6.0 with some Rancher patches added to it
    - On upgrades, users should ensure that they are not downgrading the version of the chart they are using. e.g. if in Rancher 2.5 the user is using a version of Monitoring >`16.6.0`, they should not upgrade to `100.x.x+up16.6.0`; instead, they should upgrade to the appropriate version in the next release.

**Comment by aiyengar2** [comment]
cc: @cbron

**Comment by cbron** [comment]
There have been some customer questions about this, so I am bumping up to 2.6.1. It doesn't have to go out by 2.6.1 release date, but sometime soon.
