### ISSUE TITLE
[Rancher2] Rancher 2.6 doc Ingress Quick Start points to v2.5 details

### ISSUE THREAD

**Issue by peteingithub** [rancher/docs#3515]
**Request Summary:**
Ingress config details point to v2.5 steps.

**Details:**
https://staging.rancher.com/docs/rancher/v2.6/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/

![image](https://user-images.githubusercontent.com/86831399/133219296-f38cb6cd-6198-4ac5-8581-66b4510ad61e.png)

**Comment by jtravee** [comment]
Closing in favor of new issue created to address this and workload steps. See #3710.
