### ISSUE TITLE
[Rancher2] Complementing Service Discovery entries are no longer created for new workloads using dashboard UI

### ISSUE THREAD

**Issue by sgapanovich** [rancher/docs#3522]
**Request Summary:**
https://rancher.com/docs/rancher/v2.6/en/k8s-in-rancher/service-discovery/

While using v2.6 and dashboard UI discovered that the following is no longer true:
```For every workload created, a complementing Service Discovery entry is created. This Service Discovery entry enables DNS resolution for the workload’s pods using the following naming convention: `<workload>.<namespace>.svc.cluster.local.` ```

**Details:**

While using Ember UI complementing Service Discovery entires were created but they are not created when creating a workload using:
- Dashboard UI
- kubectl command

**Comment by btat** [comment]
Closed by https://github.com/rancher/docs/pull/3600
