### ISSUE TITLE
[Rancher2] quickstart - workload - documentation steps reference things not in UI

### ISSUE THREAD

**Issue by jmcsagdc** [rancher/docs#3525]
**Request Summary:**

Things on the page direct the user to take actions that are not possible and elements of the page reference things that are named differently in the UI

URL: https://rancher.com/docs/rancher/v2.6/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/

**Details:**

See screenshots for things that are inaccurate. They're annotated in the images. These are examples on the page, but probably are not the only things that need fixing or adjusting

In the second example (see arrow in image), it includes a reference to Resources>Workloads>Load Balancing and a Load Balancing tab. On the page in question, there is no Resources and there are no tabs

![cluster_dashboard](https://user-images.githubusercontent.com/15971368/133676418-22247352-7dd6-4244-86a1-9dad59afa2d0.png)
![no Resources or tabs](https://user-images.githubusercontent.com/15971368/133676423-8350fa15-f267-4a78-8551-728613f849a5.png)
![projects-namespaces 2](https://user-images.githubusercontent.com/15971368/133676425-7c8b542f-3a53-4359-9edb-3ce2a6e05dee.png)
![url-2 6-quickstart-deploy-workload-ingress](https://user-images.githubusercontent.com/15971368/133676426-d8bb7cbd-a76d-4423-a46e-72bd5a213933.png)

**Comment by dveni** [comment]
Seconded this, having issues testing workload deployment. What's the actual workflow to deploy a workload and expose it with a lb?

**Comment by btat** [comment]
Closed via https://github.com/rancher/docs/pull/3711
