### ISSUE TITLE
[Rancher2] Wrong link to Rancher Backup Operator

### ISSUE THREAD

**Issue by hmike96** [rancher/docs#3528]
**Request Summary:**

Hi the link to the helm chart of the rancher-backup-operator seems to be pointing to an outdated repo. [Here](https://github.com/rancher/backup-restore-operator) is the link to the new repo i believe it should be pointing to. [This](https://rancher.com/docs/rancher/v2.5/en/backups/)is the link to the page in the docs.

**Details:**

The following is the line in the docs with the link to old deprecated link to operator.

- Helm chart is [here](https://github.com/rancher/charts/tree/main/charts/rancher-backup).

**Comment by btat** [comment]
Hi @jiaqiluo would it be more appropriate to link to https://github.com/rancher/backup-restore-operator as suggested, or should the links point to the `dev-v2.X.Y` branches (e.g., https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-backup and https://github.com/rancher/charts/tree/dev-v2.5.9/charts/rancher-backup)?

**Comment by jiaqiluo** [comment]
@btat here is where the released charts are from:
- for rancher 2.6.x https://github.com/rancher/charts/tree/release-v2.6/charts/rancher-backup
- for rancher 2.5.x https://github.com/rancher/charts/tree/release-v2.5/charts/rancher-backup

(The links you mentioned point to the development branch.)
