### ISSUE TITLE
Enhance RKE2 Documentation with full config.yaml examples

### ISSUE THREAD

**Issue by TestInProduction0** [rancher/docs#3550]
**Summary:**

Currently, the RKE2 Docs has a server [configuration reference](https://docs.rke2.io/install/install_options/server_config/). I would like to enhance the RKE2 docs with a full config.yaml example in similar fashion to the RKE full cluster.yaml example seen [here](https://rancher.com/docs/rke/latest/en/example-yamls/#full-cluster-yml-example).

**Details:**
The recommended way to configure RKE2 at scale is via config.yaml and not via bash commands and flags. It would be helpful to see a yaml example of all the potential configuration options and their comments.

**Comment by jtravee** [comment]
Please note for future issues, you may request updates to the RKE2 docs in the RKE2 repo (https://github.com/rancher/rke2). Docs directory is here: https://github.com/rancher/rke2/tree/master/docs.

**Comment by brandond** [comment]
There is no difference between the CLI flags and config.yaml keys; the CLI flag help and comments are the exact same as the config.yaml help.

There is no schema for the config file, it is just a `map[string]interface{}`. Internally the config YAML is ranged over, and keys/values merged into the flags provided via the CLI, at which point the standard CLI parser kicks in to actually operate on the flags.
