### ISSUE TITLE
[Rancher2] Rancher URL migration instructions need update

### ISSUE THREAD

**Issue by SheilaghM** [rancher/docs#3557]
**Request Summary:**
Some areas of the documentation that could be clarified to avoid confusion:

The migration documentation requires the rancher URL to be migrated to the new Rancher (restored on the 

- destination cluster), it's not clear as part of the steps, where users will find Rancher downstream clusters as 'Unavailable' while the agents are not connected. This is a large consideration when planning or considering where to restore etc.
- The S3 credentials Secret, the secret examples require the values (accessKey/secretKey) to be base64 encoded when creating the object directly, this isn't clear and presents errors while attempting to backup/restore if pasting the values without knowing that encoding is required - perhaps there is a better way to create the secret when guiding users?
- Recently tokens were excluded during backups, during restore or migration users are required to re-generate kubeconfig/API tokens, this is not documented - https://github.com/rancher/backup-restore-operator/pull/148 
- 

**Details:**
Two areas that need to be updated are:
https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/
https://rancher.com/docs/rancher/v2.6/en/backups/configuration/backup-config/#example-credentialsecret 

It would be ideal if the Rancher Backup and Restore documentation stated that there is a requirement to configure the HTTPS 443 connectivity between the Rancher Server and downstream clusters when undertaking a restore. 

This refers to the EKS cluster security group (assigned to the control plane), where Rancher was unable to connect to the apiserver for kubectl exec/logs etc. after the restore-migration.

**Comment by jtravee** [comment]
Hi @SheilaghM, following up here from Slack: can you advise, or let me know whom to ask, where exactly the downstream clusters will show unavailable when agents are not connected? Did you pinpoint the step in which this happens? Or was the intent for us just to document that they would be unavailable while agents are not connected? Thanks in advance!
