### ISSUE TITLE
Typos in the Rancher support doc

### ISSUE THREAD

**Issue by msvec** [rancher/docs#3572]
**Summary:**
Typos in https://rancher.com/support-maintenance-terms/all-supported-versions/rancher-v2.6.0/

**Details:**

Whole doc:
- "openSUSE Leap" spelling
- openSUSE Leap is using NN.N notation, e.g. 15.3 (not 15 SP3)

OS & Docker
 - a comma missing in the SLES line
 - openSUSE Leap missing?

**Comment by btat** [comment]
Reported this issue on the repository that handles the support page.
