### ISSUE TITLE
[Rancher2] Imported/Registered cluster Project network isolation

### ISSUE THREAD

**Issue by cloudnautique** [rancher/docs#3575]
**Request Summary:**
2.6 added support for project network isolation on imported clusters in this issue: https://github.com/rancher/rancher/issues/33016

Based on current docs, I can't find the reference to it. It is also not clear how the user would go about leveraging it. 

Also this link: https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/#importing-existing-clusters
on this page https://rancher.com/docs/rancher/v2.6/en/cluster-provisioning/ doesn't go anywhere.

**Comment by jtravee** [comment]
https://github.com/rancher/docs/pull/3671 corrected links mentioned.

**Comment by jtravee** [comment]
Waiting for UI update https://github.com/rancher/dashboard/issues/4574 to be completed.
