### ISSUE TITLE
[Rancher2] "Rancher 2.6 doc Ingress Quick Start" needs to be updated

### ISSUE THREAD

**Issue by brudnak** [rancher/docs#3577]
**Request Summary:**
This page of the Rancher 2.6 documentation is a bit confusing and appears to be outdated from the previous version: [Workload with Ingress Quick Start](https://rancher.com/docs/rancher/v2.6/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/)

>Ingress settings are under the services tab with the new UI.

**Details:**
The steps begin to break down under the main step 2. **Expose The Application Via An Ingress**. At step 5:

`Click Resources > Workloads > Load Balancing. Click on the Load Balancing tab.`

![Screen Shot 2021-09-30 at 3 13 32 PM](https://user-images.githubusercontent.com/40877149/135537247-cf1c1250-f8a7-4ffe-ab7f-350d7f67211e.png)

With the new UI for 2.6 step 5 and the steps after can't be completed as described.

![docs](https://user-images.githubusercontent.com/40877149/135537578-77c62bcb-74ce-4d71-8572-3f443e0a2d86.gif)

There is also a duplicate issue created which is located here: [https://github.com/rancher/docs/issues/3515](https://github.com/rancher/docs/issues/3515)

[Link to the page in question on GitHub :octocat:](https://github.com/rancher/docs/blob/master/content/rancher/v2.6/en/quick-start-guide/workload/quickstart-deploy-workload-ingress/_index.md)

**Comment by chrisbward** [comment]
Also having the issue here with documentation - can't find "Load Balancing" - now what?

**Comment by jtravee** [comment]
Closing in favor of new issue created to address this and workload steps. See #3710.
