### ISSUE TITLE
Add tiles for RKE2 and Longhorn to rancher.com/docs

### ISSUE THREAD

**Issue by sirredbeard** [rancher/docs#3632]
Based on feedback from Support.

We may need an assist from web team on this.

**Comment by lvuch** [comment]
![image](https://user-images.githubusercontent.com/3013118/141146305-7ec4fe79-64ca-4a02-af58-1b1d9b5c018c.png)

**Comment by lvuch** [comment]
https://github.com/rancher/docs/pull/3676 these have been added but the cache needs to be cleared

**Comment by sirredbeard** [comment]
![image](https://user-images.githubusercontent.com/33820650/141481930-c3034227-bb2c-45bf-9189-2f33a4a07bf3.png)

**Comment by sirredbeard** [comment]
Thank you @lvuch
