### ISSUE TITLE
The 2.6 monitoring enablement guide refers to an option that does not exist

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#3635]
Ref: https://rancher.com/docs/rancher/v2.6/en/monitoring-alerting/guides/enable-monitoring/
"Optional: Click Chart Options and configure alerting, Prometheus and Grafana. For help, refer to the configuration reference."

`Chart Options` is not an option.  Is this perhaps be referring to `Customize Helm options before install`?
![image](https://user-images.githubusercontent.com/8906089/139481965-793146b4-5e70-441d-9e18-621cd16788f6.png)

**Comment by Tejeev** [comment]
After clicking it I see it leads to a very minor set of options.  From the description of the step, it looks like it's actually just talking about configuring the options exposed in `Install: Step 2` `Values` instead

Values:
![image](https://user-images.githubusercontent.com/8906089/139483379-facd599b-1946-46c3-a6ec-2e61f00f0282.png)
vs Helm Options:
![image](https://user-images.githubusercontent.com/8906089/139483430-bd346ba3-f24b-4809-8070-84d5b8390ce3.png)

**Comment by btat** [comment]
Closed via https://github.com/rancher/docs/pull/3636.
