### ISSUE TITLE
[Rancher2] Add note to v2.5 and v2.6 rollbacks docs clarifying that UI will be unavailable during the process

### ISSUE THREAD

**Issue by nickgerace** [rancher/docs#3642]
**Request Summary:**
Add note to both the v2.5 and v2.6 rollbacks docs clarifying that the UI will be unavailable until the rollback process is completed. This is because scaling the `rancher` deployment pod down to `0` will result in both Rancher and its UI to not be in a running state.

https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/rollbacks/
https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/rollbacks/

**Details:**
cc @flrichar

**Comment by wpwoodjr** [comment]
Since the UI is not available, you need to use the original cluster kubeconfig (since rancher pods are unavailable to authenticate you) with the restore yaml file.  I copied the Restore yaml before scaling down the Rancher pods, then edited the yaml to give a value to metadata.name, then ran:
```
kubectl apply -f restore.yaml
```

**Comment by wpwoodjr** [comment]
It might be better as an enhancement if the restore operator scaled down the Rancher pods for you, then did the restore.

**Comment by nickgerace** [comment]
>It might be better as an enhancement if the restore operator scaled down the Rancher pods for you, then did the restore.

@wpwoodjr I'd recommend filing an issue in [rancher/rancher](https://github.com/rancher/rancher). Feel free to tag me in a comment for it.
