### ISSUE TITLE
[Rancher2] Missing docs how to create Rancher Apps

### ISSUE THREAD

**Issue by bashofmann** [rancher/docs#3648]
**Request Summary:**
Rancher Apps are helm charts with additional meta data (`questions.yml`) to configure the installation UI and nicer integrate them into Rancher.

In the Rancher 2.6 documentation the page to document this is missing, even though the feature is still relevant for 2.6 and the new UI.

Existing page for Rancher 2.x: https://rancher.com/docs/rancher/v2.0-v2.4/en/helm-charts/creating-apps/

**Comment by btat** [comment]
Closed via https://github.com/rancher/docs/pull/3559
