### ISSUE TITLE
Not possible to create a Docker registry on the project level.

### ISSUE THREAD

**Issue by victord-huma** [rancher/docs#3654]
**Summary:**

According to the [document](https://rancher.com/docs/rancher/v2.6/en/k8s-in-rancher/registries/?query=deactivate) it is possible to add an image registry to a **project**:

> Your secret is added to the project or namespace, depending on the scope you chose.

But from the UI, I can select only namespaces - refer to the attached screenshot. So please update the document accordingly.

**Details:**

Rancher ver: 2.6.2

<img width="655" alt="rancher2 6-no-projects-2-add-image-registry" src="https://user-images.githubusercontent.com/91327520/140378542-3773f40e-41f4-4aac-aee4-570e89795307.png">

**Comment by jtravee** [comment]
Related to https://github.com/rancher/rancher/issues/35251
