### ISSUE TITLE
[K3s] add --audit-policy-file parameter in hardening guide

### ISSUE THREAD

**Issue by davinkevin** [rancher/docs#3656]
**Request Summary:**

In current hardening guide example, we don't have any `--audit-policy-file` parameter defined in the `k3s server` command example.

**Details:**

If we don't provide any `--audit-policy-file`, the audit logging is disabled ([default behaviour of k8s](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy)). 

Having some kind of "default" `audit.k8s.io/v1:Policy`  file and the parameter in the command example could be a better description of "how to enable it", especially when we enable every other parameters about `audit-log`.

Thank you

BTW, if you provide me some information about what we should do on this one, I would be able to do a PR.

**Comment by jtravee** [comment]
Hi @davinkevin, please close this issue and create a new one at https://github.com/k3s-io/docs instead. Thanks!

**Comment by davinkevin** [comment]
@jtravee Done 😇
