### ISSUE TITLE
[Rancher2] Improvements to Rancher backup-operator documentation regarding Fleet

### ISSUE THREAD

**Issue by axeal** [rancher/docs#3665]
**Request Summary:**
This request is for improvements to the Rancher backup-operator documentation to address two points, one v2.5 specific and the second applicable to both v2.5 and v2.6

**Details:**
1. For Rancher v2.5 Fleet is inoperable following a restore using the backup-restore operator, per SURE-3497 and https://github.com/rancher/backup-restore-operator/issues/164 This is currently tracked for backport of the fix (present in v2.6.x) in v2.5.12. For now the workaround (based upon my testing) following a restore in v2.5.x is:
    1. If two service account tokens are listed in the secets list of the fleet-controller and fleet-controller-bootstrap service accounts in the fleet-system Namespace of the local cluster, remove the entry which references a non-existent token secret, so only one entry is present for the service account token secret that actually exists. Then delete the fleet-controller Pod in the fleet-system Namespace to re-schedule this.
    2. To force redeployment of the fleet-agents (once service account token issue is fixed) Force Update clusters in Continuous Delivery UI. If the fleet-agent bundles remain in 'Modified' state after this, delete them to force recreation and remove the 'Modified' state.
2. Per SURE-3503 and https://github.com/rancher/backup-restore-operator/issues/163 clientSecretName and helmSecretName secrets for Fleet gitrepos are not included in the backups created by the backup-restore-operator. It should be noted that users will need to re-create these secrets if they are performing a disaster recovery restore/migration of Rancher into a fresh cluster.

**Comment by jtravee** [comment]
@StrongMonkey, please review, ty!

**Comment by StrongMonkey** [comment]
@jtravee The proposed changes look good. Minor changes:
> To force redeployment of the fleet-agents (once service account token issue is fixed) Force Update clusters in Continuous Delivery UI. If the fleet-agent bundles remain in 'Modified' state after this, ~delete them to force recreation and remove the 'Modified' state~ Increment `spec.forceSyncGeneration` of fleet-agent bundle should be the proper workaround.

Also the first bullet should really be a temporary workaround as the fix is on track. 
For the second bullet, we should document it that by default we don't backup user defined secrets. What users can do is to follow docs [here](https://github.com/rancher/backup-restore-operator#user-flow) to modify resourceSet to include extra resources they want to backup.
