### ISSUE TITLE
[Rancher2] Wording can be misleading on Project Resource Quotas Page

### ISSUE THREAD

**Issue by paynejacob** [rancher/docs#3687]
https://rancher.com/docs/rancher/v2.6/en/project-admin/resource-quotas/

**Request Summary:**
At the bottom of the page there is a note: `The resource quota is applied to your project and namespaces. When you add more namespaces in the future, Rancher validates that the project can accommodate the namespace. If the project can’t allocate the resources, Rancher won’t let you save your changes.`  The last sentence is ambiguous and can be interpreted as rancher will not let you create a namespace if the project resource quota does not allow it.  Namespaces can be created but they will be given a resoruce quota of 0.  If you try to create any resources restricted by the quota rancher will not allow it.

**Comment by eumel8** [comment]
@paynejacob This is absolutly true and a completely other behavior as in Rancher 2.5.  In Rancher 2.6.2 I can add more namespaces to the project, but if the resources are almost full for one (like cpu limit), Rancher will add *all* resource limits to the new namespace:

```bash
$ kubectl describe  ns demoapp
Name:         demoapp
Labels:       field.cattle.io/projectId=p-xq75k
Annotations:  cattle.io/status:
                {"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2021-11-18T16:53:20Z"},{"Type":"InitialRolesPopu...
              field.cattle.io/projectId: c-pzk8b:p-xq75k
              field.cattle.io/resourceQuota: {"limit":{"limitsCpu":"500","limitsMemory":"1000000"}}
              lifecycle.cattle.io/create.namespace-auth: true
Status:       Active

Resource Quotas
 Name:                   default-pnp82
 Resource                Used  Hard
 --------                ---   ---
 configmaps              2     0
 limits.cpu              0     0
 limits.memory           0     0
 persistentvolumeclaims  0     0
 pods                    0     0
 replicationcontrollers  0     0
 requests.cpu            0     0
 requests.memory         0     0
 requests.storage        0     0
 secrets                 1     0
 services                0     0
 services.loadbalancers  0     0
 services.nodeports      0     0
```

If you increase the project quota, Rancher will remove this and switch back to the configured quota:

```
kubectl describe ns demoapp
Name:         demoapp
Labels:       field.cattle.io/projectId=p-xq75k
Annotations:  cattle.io/status:
                {"Conditions":[{"Type":"ResourceQuotaInit","Status":"True","Message":"","LastUpdateTime":"2021-11-18T17:06:05Z"},{"Type":"InitialRolesPopu...
              field.cattle.io/projectId: c-pzk8b:p-xq75k
              field.cattle.io/resourceQuota: {"limit":{"limitsCpu":"500","limitsMemory":"1000000"}}
              lifecycle.cattle.io/create.namespace-auth: true
Status:       Active

Resource Quotas
 Name:          default-fhddm
 Resource       Used  Hard
 --------       ---   ---
 limits.cpu     0     500
 limits.memory  0     1M
```

Maybe there are people on the planet they can handle this. If this behavior is expected, then it should be definitly better explained in the documentation. Thx!
