### ISSUE TITLE
Update fleet documentation for HTTP secrets

### ISSUE THREAD

**Issue by slickwarren** [rancher/docs#3717]
**Summary:**
HTTP secrets are no longer supported for github (this comes up when testing fleet with private git repositories)
```
Support for password authentication was removed on August 13, 2021. Please use a personal access token instead. remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
```

**Details:**

A workaround for this is to create a [github token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token), and through rancher create an http secret with your github username, and using the token as the secret.

**Comment by StrongMonkey** [comment]
@jtravee are you able to add this through fleet troubleshooting docs? pretty much the detail that @slickwarren has filled out ^^

**Comment by jtravee** [comment]
Yes, I can, no problem!
