### ISSUE TITLE
[Rancher2] Change v2.x aliases to v2.6

### ISSUE THREAD

**Issue by MAFLO321** [rancher/docs#3757]
**Request Summary:**
All rancher v2.x URLs should not redirect/alias to v2.5 docs. Instead, they should redirect/alias to v2.6.
Because this is a bit confusing for new users that for example the URLs listet under https://github.com/rancher/rancher#installation link to the old-stable docs and not to the current stable/latest release.

**Details:**
For example the URL https://rancher.com/docs/rancher/v2.x/en/installation/other-installation-methods/single-node-docker/ redirects to v2.5.

**Comment by catherineluse** [comment]
This isn't a simple matter of find and replace, so when this worked on I can help with this, or we can discuss.

**Comment by btat** [comment]
No longer relevant with the new site.
