### ISSUE TITLE
[Rancher2] Port requirements for Monitoring V2

### ISSUE THREAD

**Issue by watarumohawk** [rancher/docs#3777]
**Request Summary:**
Some more ports that are not mentioned on the doc ['Enable Monitoring'](https://rancher.com/docs/rancher/v2.5/en/monitoring-alerting/guides/enable-monitoring/) are needed to access Grafana dashboard on Monitoring V2.
If these ports are not configured correctly, UI shows 'Resource Unavailable' for the link of Grafana dashboard, so you can't access it.

**Details:**
On the aforementioned doc, only port 9796 is mentioned. However, port 80, 9090, and 9093 are used [in the source code](https://github.com/rancher/dashboard/blob/v2.5.9-rc1/pages/c/_cluster/monitoring/index.vue#L53-L88), and on [a GitHub issue](https://github.com/rancher/dashboard/issues/2494#issuecomment-873741761) the user fixed the 'Resource Unavailable' issue by adding port 8080, 8081, and 9093.

Could you add these ports on one of the following docs?

- Enable Monitoring
https://rancher.com/docs/rancher/v2.5/en/monitoring-alerting/guides/enable-monitoring/

- Port Requirements
https://rancher.com/docs/rancher/v2.5/en/installation/requirements/ports/

**Comment by Tejeev** [comment]
https://github.com/rancher/docs/issues/2493

**Comment by sirredbeard** [comment]
Related to Jira https://jira.suse.com/browse/SURE-3910

**Comment by jtravee** [comment]
cc @MKlimuszka

**Comment by jtravee** [comment]
Working with QA to develop a plan for minimum port requirement testing.

**Comment by jtravee** [comment]
> Working with QA to develop a plan for minimum port requirement testing.

Working also with tech support eng to try and reproduce steps in a test env.

**Comment by jtravee** [comment]
Issue is being closed as the support case is closed and no docs updates are required at this time.
