### ISSUE TITLE
[Rancher2] Windows RKE2: HostProcess container support

### ISSUE THREAD

**Issue by luthermonson** [rancher/docs#3779]
**Request Summary:**
When rke2 + windows goes GA there is a pretty major feature we're trying to get in which is HostProcess containers. This is supported upstream from k8s v1.23 + containerd v1.6+ and we are looking for a place to document that we support HostProcess containers and link to documentation from upstream showing you how to configure them.

**Details:**

the upstream pod spec changes are here: https://kubernetes.io/docs/tasks/configure-pod-container/create-hostprocess-pod/
the tracking issue for windows is here: https://github.com/rancher/windows/issues/69

We are waiting on containerd to release v1.6.0 to make this official but it is looking likely we'll have it soon and this will ship. So dont put much effort into this issue until after the windows tracking issue is closed.

- [x] Add note to 2.6.7 release notes
- [x] Update docs

**Comment by jtravee** [comment]
HostProcess container support will ship with 1.24.1 in Rancher 2.6.6. Will update docs at that time.

**Comment by jtravee** [comment]
RN for 2.6.7-

**New in RKE2 Windows:** HostProcess containers are now supported in Kubernetes v1.24.1 and up.

**Comment by btat** [comment]
Added to https://github.com/rancherlabs/release-notes/pull/260/
