### ISSUE TITLE
[Rancher2] AWS Quickstart IAM Policy

### ISSUE THREAD

**Issue by maxpastor** [rancher/docs#3782]
**Request Summary:**
Add a blueprint or a complete IAM policy in the documentation. 

**Details:**

The template is supposed to deploy a bunch of things inside one's AWS account. To do so, you a requiring AWS credentials. These credentials are from a User and this user needs to have a proper IAM policy. 
You do not specify the services and actions that need to be authorized for the template to be deployed properly. 
By not providing any information or ready-to-use policy, you open the door to people creating a user with admin permissions or using their own credentials. This is not good practice. 

So, by listing the services:actions or providing an IAM policy, this problem would be solved and it would also improve the experience of people reading the documentation, as a simple copy and paste would do the trick.

**Comment by btat** [comment]
@bashofmann would you be able to provide the IAM policy used in the quickstart?

**Comment by bashofmann** [comment]
I'll try to get to it in the next days.

**Comment by bashofmann** [comment]
The AWS module just creates an EC2 KeyPair, an EC2 SecurityGroup and an EC2 instance. A simple policy would be:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "ec2:*",
            "Resource": "*"
        }
    ]
}
```

We could limit it further, but I'd rather document something a bit broader. Otherwise we need to adapt it every time we or AWS change something. What do you think?
