### ISSUE TITLE
CIS Hardening Guide for v2.6

### ISSUE THREAD

**Issue by btat** [rancher/docs#3792]
Placeholder until more details are available.

**Comment by macedogm** [comment]
@btat This https://github.com/rancher/docs/pull/3761 is a first PR where I briefly restructured the contents of the security area in the docs and mentioned that a new version of the hardening guides is coming. IMO this PR can be quickly approved in the meantime.

I'm working on a second PR with the updates itself to the hardening guides. I'll let you know when it's ready.

**Comment by macedogm** [comment]
Original issue is https://github.com/rancher/rancher/issues/35735

**Comment by macedogm** [comment]
@btat Please see https://github.com/rancher/docs/pull/3810 for the final PR.

**Comment by macedogm** [comment]
@btat FYI this is also a proposal to update K3s hardening guide - https://github.com/rancher/docs/pull/3897.

**Comment by macedogm** [comment]
@btat both Rancher/RKE and K3s hardening guides are updated in master. It should be okay to close this issue.
