### ISSUE TITLE
[Rancher Desktop] Document nerdctl and moby CLIs with examples on how to build and run

### ISSUE THREAD

**Issue by gaktive** [rancher/docs#3806]
**Summary:**
For Rancher Desktop (docs.rancherdesktop.io), we've had requests to have written examples from sample videos or animated GIFs on how to build and run a Docker file and use CLIs like nerdctl and moby.

From @catherineluse:
> - They said they would like to see a written example of how to build and run a Dockerfile and a docker-compose file using nerdctl - for people who would rather see written example than the video
> - The site and README should be updated to mention the technical preview of Rancher Desktop on Linux https://community.suse.com/posts/rancher-desktop-v06-including-linux-tech-preview (which is now behind registration)

Source: https://github.com/rancher-sandbox/rancher-desktop/issues/786 

**Details:**
From the 0.5 announcement regarding `nerdctl`, we had examples like this:

To expose port 8000 for a container
```
$ nerdctl run -d -p 8000:80 nginx
```

You can then access the container via browser: http://localhost:8080

```
$ nerdctl build -t demo:latest /code/demos/rd/anvil-app
```

You can also target a Kubernetes namespace with the `--namespace` parameter:

```
$ nerdctl --namespace k8s.io build -t demo:latest /code/demos/rd/anvil-app
$ nerdctl --namespace k8s.io ps
```

We'd need something similar for `moby`

**Comment by jtravee** [comment]
Closed, completed in [#30](https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/30) on RD docs repo.
