### ISSUE TITLE
[Rancher2] Examine what QA-related documentation can be made public

### ISSUE THREAD

**Issue by sirredbeard** [rancher/docs#3815]
Both general QA, such as basic test plans, and performance testing-related testing.

cc @leodotcloud @spgardiner

**Comment by btat** [comment]
May be a better fit to have someone from QA to review what's appropriate for public consumption.

To confirm with Guna whether this should go in QA's repo (https://github.com/rancher/qa-tasks)

**Comment by btat** [comment]
Closing as not actionable by us.
