### ISSUE TITLE
[Rancher2] Release notes addition: One process remains for each shell connection In cluster explorer

### ISSUE THREAD

**Issue by sirredbeard** [rancher/docs#3822]
> when opening a shell terminal for a pod in the cluster explorer, the corresponding processes won't be shut down after closing the terminal in the browser. So everytime after somone opens a terminal the following processes will remain running for each terminal in the pod indefinetly

Pending a fix in https://github.com/rancher/rancher/issues/16192 this needs to be release noted.

Details: https://jira.suse.com/browse/SURE-3540?filter=102481

**Comment by sirredbeard** [comment]
As far as I can tell this only affects 2.5.x but we need to confirm.

**Comment by sadhugit** [comment]
This is still applicable to 2.6.5 as well. Opened the shell of of pod for three to 4  times  and saw the number of processes increase from 15 to 30
root@overlaytest-lhqpn:~# ps -ef|wc -l
30
root@overlaytest-lhqpn:~# ps -ef      
UID          PID    PPID  C STIME TTY          TIME CMD
root           1       0  0 Jun28 ?        00:00:00 sh -c tail -f /dev/null
root           7       1  0 Jun28 ?        00:01:11 tail -f /dev/null
root           8       0  0 Jun28 pts/0    00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh
root          15       8  0 Jun28 pts/0    00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh
root          16      15  0 Jun28 pts/0    00:00:00 /usr/bin/script -q -c /bin/bash /dev/null
root          17      16  0 Jun28 pts/1    00:00:00 sh -c /bin/bash
root          18      17  0 Jun28 pts/1    00:00:00 /bin/bash
root          42       0  0 04:20 pts/2    00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh
root          50      42  0 04:20 pts/2    00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh
root          51      50  0 04:20 pts/2    00:00:00 /usr/bin/script -q -c /bin/bash /dev/null
root          52      51  0 04:20 pts/3    00:00:00 sh -c /bin/bash
root          53      52  0 04:20 pts/3    00:00:00 /bin/bash
root          68       0  0 04:21 pts/4    00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh
root          77      68  0 04:21 pts/4    00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh
root          78      77  0 04:21 pts/4    00:00:00 /usr/bin/script -q -c /bin/bash /dev/null
root          79      78  0 04:21 pts/5    00:00:00 sh -c /bin/bash
root          80      79  0 04:21 pts/5    00:00:00 /bin/bash
root          93       0  0 04:28 pts/6    00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh
root         100      93  0 04:28 pts/6    00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh
root         101     100  0 04:28 pts/6    00:00:00 /usr/bin/script -q -c /bin/bash /dev/null
root         102     101  0 04:28 pts/7    00:00:00 sh -c /bin/bash
root         103     102  0 04:28 pts/7    00:00:00 /bin/bash
root         122       0  0 04:29 pts/8    00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh
root         130     122  0 04:29 pts/8    00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh
root         131     130  0 04:29 pts/8    00:00:00 /usr/bin/script -q -c /bin/bash /dev/null
root         132     131  0 04:29 pts/9    00:00:00 sh -c /bin/bash
root         133     132  0 04:29 pts/9    00:00:00 /bin/bash
root         145     133  0 04:29 pts/9    00:00:00 ps -ef

**Comment by jtravee** [comment]
cc @gaktive

**Comment by jtravee** [comment]
> This is still applicable to 2.6.5 as well. Opened the shell of of pod for three to 4 times and saw the number of processes increase from 15 to 30 root@overlaytest-lhqpn:~# ps -ef|wc -l 30 root@overlaytest-lhqpn:~# ps -ef UID PID PPID C STIME TTY TIME CMD root 1 0 0 Jun28 ? 00:00:00 sh -c tail -f /dev/null root 7 1 0 Jun28 ? 00:01:11 tail -f /dev/null root 8 0 0 Jun28 pts/0 00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh root 15 8 0 Jun28 pts/0 00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh root 16 15 0 Jun28 pts/0 00:00:00 /usr/bin/script -q -c /bin/bash /dev/null root 17 16 0 Jun28 pts/1 00:00:00 sh -c /bin/bash root 18 17 0 Jun28 pts/1 00:00:00 /bin/bash root 42 0 0 04:20 pts/2 00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh root 50 42 0 04:20 pts/2 00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh root 51 50 0 04:20 pts/2 00:00:00 /usr/bin/script -q -c /bin/bash /dev/null root 52 51 0 04:20 pts/3 00:00:00 sh -c /bin/bash root 53 52 0 04:20 pts/3 00:00:00 /bin/bash root 68 0 0 04:21 pts/4 00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh root 77 68 0 04:21 pts/4 00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh root 78 77 0 04:21 pts/4 00:00:00 /usr/bin/script -q -c /bin/bash /dev/null root 79 78 0 04:21 pts/5 00:00:00 sh -c /bin/bash root 80 79 0 04:21 pts/5 00:00:00 /bin/bash root 93 0 0 04:28 pts/6 00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh root 100 93 0 04:28 pts/6 00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh root 101 100 0 04:28 pts/6 00:00:00 /usr/bin/script -q -c /bin/bash /dev/null root 102 101 0 04:28 pts/7 00:00:00 sh -c /bin/bash root 103 102 0 04:28 pts/7 00:00:00 /bin/bash root 122 0 0 04:29 pts/8 00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh root 130 122 0 04:29 pts/8 00:00:00 /bin/sh -c TERM=xterm-256color; export TERM; [ -x /bin/bash ] && ([ -x /usr/bin/script ] && /usr/bin/script -q -c "/bin/bash" /dev/null || exec /bin/bash) || exec /bin/sh root 131 130 0 04:29 pts/8 00:00:00 /usr/bin/script -q -c /bin/bash /dev/null root 132 131 0 04:29 pts/9 00:00:00 sh -c /bin/bash root 133 132 0 04:29 pts/9 00:00:00 /bin/bash root 145 133 0 04:29 pts/9 00:00:00 ps -ef

@sadhugit thank you for your contribution. We will add this known issue to 2.6.x as well.
