### ISSUE TITLE
[Rancher2] Minimum EKS permissions may need to be updated

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#3828]
Someone in the Rancher Users Slack said they needed an additional permission, `ec2:DescribeInstanceType`, to provision an EKS cluster. They were following this doc https://rancher.com/docs/rancher/v2.5/en/cluster-provisioning/hosted-kubernetes-clusters/eks/permissions/ 

Source: https://rancher-users.slack.com/archives/C010H59M335/p1643293517883559?thread_ts=1643280757.015679&cid=C010H59M335

Field engineering should review this change

**Comment by jtravee** [comment]
@thedadams Hi Donnie, please review and advise, ty!

**Comment by thedadams** [comment]
@jtravee The user referenced here was trying to alter the permissions described in the Rancher docs to be a minimum for importing EKS clusters and not managing them through Rancher. I indicated to the user that this is not something supported by Rancher and he would be on his own in trying to reduce the number of permissions.

The permission he needed to add to his tests was `ec2.DescribeInstances`. This is included with many of the other permissions. For example, `eks.CreateCluster` includes the permission `ec2.DescribeInstances`.

Therefore, I don't think any update is required at this time.
