### ISSUE TITLE
Feature Request: Context/Page aware versioning switching in docs

### ISSUE THREAD

**Issue by jamesongithub** [rancher/docs#3837]
**Summary:**

It would be nice to stay on the same page when changing versions in the rancher docs, like a lot of other versioned docs do. Often I come to a 2.5 page from google and want to see the 2.6 version of the docs. When I switch versions, it just takes me to the root page of 2.6 https://rancher.com/docs/rancher/v2.6/en/. A lot of times I can't find the corresponding 2.6 page after that. 

**Details:**

Understandably some features will be deprecated from version to version (or new features added in newer version and switching to an older version), so some pages will have to updated.

**Comment by btat** [comment]
Thank you for the request. This is a feature we on our roadmap and will be working towards adding.

**Comment by btat** [comment]
Addressed via move to Docusaurus.
