### ISSUE TITLE
v2.6.4 Release Task - Contact Product for Major Features

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/docs#3844]
**Docs Release Task**
This is a release task (https://github.com/rancher/rancher/issues/36375) for the docs team to reach out to @cloudnautique and get a write-up for the major features for this release.

**Comment by jtravee** [comment]
Confirmed that @deniseschannon will be providing the feedback for product in 2.6.4.

**Comment by jtravee** [comment]
Received feedback for product features [here](https://github.com/rancher/dashboard/issues/5041#issuecomment-1071061787), updated RN PR accordingly.

**Comment by deniseschannon** [comment]
In the RN, we should probably do a bit more about elevating/graduating that k8s 1.22 is now no longer experimental. I didn't do that in the product but I would expect it in the release notes.

**Comment by nunix** [comment]
@Jono-SUSE-Rancher Denise's feedback has been incorporated in 2.6.4 Release notes
