### ISSUE TITLE
v2.6.4 Release Task - Publish Initial PRs of Release Notes

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/docs#3845]
**Docs Release Task**
This is a release task (https://github.com/rancher/rancher/issues/36375) for the docs team to publish the first draft of the PRs of the release notes for v2.6.4.

The engineering team should have added `release-note` labels to all associated features by now.

**Comment by nunix** [comment]
Started the release notes draft for 2.6.4 and created an initial PR.

**Comment by nunix** [comment]
The 2.6.4 Release Notes are now completed and will be merged once last review is done.
