### ISSUE TITLE
v2.6.4 Release Task - Complete Writing of the RKE Release Notes

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/docs#3846]
**Docs Release Task**
This is a release task (https://github.com/rancher/rancher/issues/36375) for the docs team to finalize the RKE release notes for the upcoming version of RKE.

Check in with Team 2 to ensure there is nothing special going into the RKE that needs to be accounted for.

**Comment by nunix** [comment]
As per @jtravee feedback, the RKE release notes have been merged
