### ISSUE TITLE
[Rancher2] Installation results in defective nginx ingress 

### ISSUE THREAD

**Issue by cawoodm** [rancher/docs#3852]
**Request Summary:**
I followed the [installation docs](https://rancher.com/docs/rancher/v2.5/en/installation/install-rancher-on-k8s/) and the result was a `rancher` ingress which had no address. This may be an issue with the helm chart.

**Details:**
The `rancher` ingress resource was missing the following annotation:
```
    kubernetes.io/ingress.class: nginx
```
As a result the ingress got no address.

Perhaps the docs/helm chart assume we are using traefik?

**Comment by jtravee** [comment]
Thank you for your contribution. We have updated the docs with this information; please see [#3762](https://github.com/rancher/docs/pull/3762).

**Comment by btat** [comment]
Done via https://github.com/rancher/docs/pull/4227
