### ISSUE TITLE
[Rancher2] Update git-based charts repo documentation

### ISSUE THREAD

**Issue by PennyScissors** [rancher/docs#3864]
The fix for issue https://github.com/rancher/rancher/issues/31676, adds support for CA bundles for git-based charts repositories. Therefore, the documentation [here](https://rancher.com/docs/rancher/v2.6/en/helm-charts/#repositories) needs to be updated. The process to add CA bundles for git-based repos is the same as the HTTP based, so the docs should match.

**Comment by divya-mohan0209** [comment]
Awaiting confirmation from QA for signoff on this fix.

**Comment by btat** [comment]
Closed via https://github.com/rancher/docs/pull/3892

**Comment by PennyScissors** [comment]
@divya-mohan0209 @btat re-opening this issue because the original issue got pushed to the 2.6.5 milestone. The work done in the backend has been reverted, so docs need to be reverted as well.

**Comment by bmdepesa** [comment]
QA has validated this feature in v2.6.5.

**Comment by btat** [comment]
Fixed via https://github.com/rancher/docs/pull/4060
