### ISSUE TITLE
Algolia search broken & duplicate links issue

### ISSUE THREAD

**Issue by divya-mohan0209** [rancher/docs#3867]
**Summary:**
The algolia search results displayed on clicking the magnifying glass in the top bar displays 
- Duplicate links
- Broken results

for some particular queries.

**Details:**
For example, on searching for RBAC despite adding a redirect between versions the first result will always point to https://rancher.com/docs/rancher/v2.x/en/monitoring-alerting/rbac/ and throw a 404.

Per the instructions here, the issue can be fixed by 

- [X] Creation of JSON template under _layouts/default and naming it as list.algolia.json
- [X] Add atomic-algolia under scripts in package.json
- [] Updating index with every release: This potentially needs updation of the build variables on the docker environment. I don't seem to have access to the images and therefore will need assistance from someone who does.
- [] Potential removal of build & publish_algolia.js

**Comment by divya-mohan0209** [comment]
cc: @sirredbeard @catherineluse

**Comment by divya-mohan0209** [comment]
This cannot be tested without pushing it into one of the environments since the top bar is rendered unclickable on local builds. Which branch would a good guinea pig for this issue?

**Comment by btat** [comment]
No longer relevant after moving to a new site (rancher-docs).
