### ISSUE TITLE
[Rancher2] Banners config now has it's own tab inside Global Settings

### ISSUE THREAD

**Issue by aalves08** [rancher/docs#3876]
**Request Summary:**
The Banners config has moved from the `Branding` tab to it's own `Banners` tab. Check PR for additional information. Documentation should be updated accordingly, if needed (sorry, this is my first docs PR and not sure if you have this described in detail there)

Connected to Github issue: [#4594](https://github.com/rancher/dashboard/issues/4594)
Connected to Zube issue: [#4612](https://zube.io/rancher/dashboard-ui/c/4612)
PR: [merged](https://github.com/rancher/dashboard/pull/4979)

**Comment by btat** [comment]
Closed via https://github.com/rancher/docs/pull/3885
