### ISSUE TITLE
[Rancher2] Document how to set up an alert that triggers if a workload fails

### ISSUE THREAD

**Issue by catherineluse** [rancher/docs#3877]
Someone in the Rancher Users slack asked how to configure the monitoring application to let them know if a single workload fails. I don't know how to do that off the top of my head, but it would be good to document that simple use case if you can do that.

**Comment by jtravee** [comment]
Per @aiyengar2, the solution might be complicated. It would involve essentially writing a PrometheusRule (aka writing a PromQL expression that evaluates to non-zero when the alert needs to be triggered), but figuring out what the rule’s PromQL expression should be is the challenge. He advised that a simpler solution would be to bring in Alerting V2 (which is non-metric-based alerting; something we supported in Alerting V1 but we haven’t brought non-metric based alerting to v2), but he isn't sure when this will be prioritized based on the recent changes to Product.

**Comment by catherineluse** [comment]
Ah, that makes sense. It's not the only time we get questions in Rancher users slack about getting alerts for things that aren't based on metrics. For example, this week there was a question about how to get some notification to get an idea of how often a workload re-deploys. I would say that non-metrics-based alerts are outside the scope of what should be documented (at least until Alerting V2) so we can close the issue.
