### ISSUE TITLE
Fix link to the Architecture for an Authorized Cluster Endpoint (ACE)

### ISSUE THREAD

**Issue by Bafff** [rancher/docs#3891]
**Summary:**

"click here" of text from this [article](https://rancher.com/docs/rancher/v2.6/en/overview/architecture-recommendations/#architecture-for-an-authorized-cluster-endpoint-ace) below point nowhere:

> As of Rancher v2.6.3, ACE support is available for registered RKE2 and K3s clusters. To view the manual steps to perform on the downstream cluster to enable the ACE, click [here](https://rancher.com/docs/v2.6/en/cluster-provisioning/registered-clusters/#authorized-cluster-endpoint-support-for-rke2-and-k3s-clusters).

**Comment by btat** [comment]
Closed via https://github.com/rancher/docs/pull/3893
