### ISSUE TITLE
[Fleet] Fleet documentation requests: intro/howto and updating docs to reflect Rancher integration

### ISSUE THREAD

**Issue by sirredbeard** [rancher/docs#3903]
Requests:

- [ ] "a how-to, tutorial or introduction post of some kind to Continuous Delivery in Rancher"
- [ ] " documentation assumes that Fleet is an add-on (even explains how to install) not that it is already installed in the latest Rancher, nor does it explain the GUI available for it."

[JIRA](https://jira.suse.com/browse/SURE-4140?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel)

**Comment by btat** [comment]
Closing as per comment in JIRA.
