### ISSUE TITLE
[Harvester] rancher-integration suggests docker run as way to install Rancher

### ISSUE THREAD

**Issue by Tejeev** [rancher/docs#3930]
**Summary:**
Ref: https://docs.harvesterhci.io/v1.0/rancher/rancher-integration/

Installing Rancher on a cluster in a docker container like this is VERY bad practice and leads to failed and lost environments and easily avoidable customer tickets which can sometimes have no path of recovery for the cluster.  This is not supported by us and should suggest good practices of NOT running everything in a docker container, perhaps referring to the methods in the Rancher docs (where they are actually good practice.  Even as a quick start, this is bad practice and if it _must_ be the method in this doc, we should also make it clear that his is **ONLY** a quick start method and should be avoided in anything that is meant to live for any length of time outside of a quick test.

**Details:**
Install Rancher on K8s without further external encapsulation.  The k8s environment should **_NOT be ephemeral_**!

**Comment by btat** [comment]
Closing as this was transferred to the Harvest Docs already.
