### ISSUE TITLE
[Rancher2] Some v2.6 docs refer to older v2.5 / Cluster Manager UI

### ISSUE THREAD

**Issue by dkeightley** [rancher/docs#3935]
**Request Summary:**
Some documentation pages for the v2.6 version appear to show details that are no longer accurate in the new Dashboard UI.

**Details:**
An example would be creating a namespace, kubeconfig, or project admin. In these examples the first step is clicking on 'Cluster Management', this can be confusing as Cluster Management is used for the lifecycle of the cluster/nodes, not the viewing and managing the objects within the cluster. 
  * https://rancher.com/docs/rancher/v2.6/en/project-admin/namespaces/#creating-namespaces
  * https://rancher.com/docs/rancher/v2.6/en/cluster-admin/cluster-access/kubectl/#accessing-clusters-with-kubectl-shell-in-the-rancher-ui
  * https://rancher.com/docs/rancher/v2.6/en/project-admin/project-members/

**Comment by divya-mohan0209** [comment]
Hello @dkeightley , thank you for reporting the issue. Is there a wider scope of revamp expected or are these the only three documents requiring amendment?

**Comment by dkeightley** [comment]
Hi @divya-mohan0209, these were the links I could locate, quite possible there's more however, anything for v2.6 that refers to "Cluster Manager" is likely outdated.
