### ISSUE TITLE
[Rancher2] Update RKE CIS Benchmark 1.6 hardening guide and verification guide for 2.6x docs

### ISSUE THREAD

**Issue by anupama2501** [rancher/docs#3952]
**Request Summary:**

Forward port the changes in the PR in 2.6.
https://github.com/rancher/docs/pull/3902

**Comment by macedogm** [comment]
@anupama2501 please see PR https://github.com/rancher/docs/pull/3953 with the fix. I applied the hardening specs and reran a CIS scan with `rke-profile-hardened-1.6`, that's why the benchmarked file changed. I also regenerated both PDFs.

**Comment by macedogm** [comment]
@anupama2501 I believe that we can close this issue, as the fix is already in master.
