### ISSUE TITLE
[Rancher2] Rancher 2.5 & 2.6 docs don't mention how to rotate certificates

### ISSUE THREAD

**Issue by watarumohawk** [rancher/docs#3960]
**Request Summary:**
Regarding cert rotation, the 2.5 & 2.6 docs don't mention the procedure even though the 2.0-2.4 doc does. 

**Details:**
Can we add this back to our doc? I think this would be more user friendly.

- Rancher 2.5
https://rancher.com/docs/rancher/v2.5/en/cluster-admin/certificate-rotation/
- Rancher 2.0-2.4
https://rancher.com/docs/rancher/v2.0-v2.4/en/cluster-admin/certificate-rotation

![rancher2 0-2 4-doc](https://user-images.githubusercontent.com/4612196/158745827-97c5329c-dcb8-455a-8af5-c231748ee6eb.png)

**Comment by divya-mohan0209** [comment]
@watarumohawk : For this PR is the intent to copy the same two sections across to the v2.5/v2.6 documentation?
