### ISSUE TITLE
[Rancher2] Migrate AD release note to docs

### ISSUE THREAD

**Issue by cbron** [rancher/docs#3970]
_"Login to Rancher using ActiveDirectory with TLS -34325"_
Since that was introduced in [2.6.0](https://github.com/rancher/rancher/releases/tag/v2.6.0), we should now move that to docs and out of release notes. We could also do it slightly later in the 2.6.x lifecycle, but I don't think we need to carry over every note every time, or the notes get out of control.

**Comment by jtravee** [comment]
@cbron We will add this to our retrospective as we discuss how to streamline the docs for 2.6.5 and beyond. There are several items that carry over each time, but may not be needed in each new release (such as this one). For now, we'll leave it in 2.6.4, and I'll create docs for this as requested.

**Comment by btat** [comment]
- [x] Remove from release notes. Updated in [this commit](https://github.com/rancherlabs/release-notes/commit/a891bc966f3f2a1856871cf20310839bf0988460).
- [ ] Add to docs
