### ISSUE TITLE
[Rancher2] Update Rancher 2.6 docs on CNI Providers to include support for Calico on RKE

### ISSUE THREAD

**Issue by crisfrusu** [rancher/docs#3981]
**Request Summary:**

Update Rancher 2.6 docs on CNI Providers to include support for Calico on RKE

**Details:**

In the Rancher 2.6 version of the CNI providers document the Calico CNI was removed from the RKE section and it only appears in the RKE2 section.  The 2.5 version of the document shows the correct information.  Please see the link below:
[CNI providers](https://rancher.com/docs/rancher/v2.6/en/faq/networking/cni-providers/#what-cni-providers-are-provided-by-rancher)

**Comment by jtravee** [comment]
@manuelbuil
