### ISSUE TITLE
Unnecessary Code Block Tabs

### ISSUE THREAD

**Issue by MBishop17** [rancher/docs#399]
When you specify a lanugage for a code block, in the output, an extra tab gets added. This behavior doesn't occur in default code blocks.

Examples:

yml

![image](https://user-images.githubusercontent.com/37810556/42350833-fc38f004-8066-11e8-8bf7-d4603a645a9a.png)

bash

![image](https://user-images.githubusercontent.com/37810556/42350826-f6d0bec6-8066-11e8-98d0-a5bebbd8a1b9.png)

**Comment by lvuch** [comment]
@MBishop17 does the tab get copied over if you try and copy and paste the snippet?
