### ISSUE TITLE
[Rancher2] Note for Ember UI being unreachable with X-Frame-Option header

### ISSUE THREAD

**Issue by jordojordo** [rancher/docs#3991]
**Request Summary:**

Based on a conversation on the [Rancher forums](https://forums.rancher.com/t/blank-pages-in-rancher-ui-after-upgrade-to-2-6-3/37332), if a server containing Rancher has the `X-Frame-Options=DENY` header the Ember UI will be completely unreachable as it is an embedded `iframe` within the new Dashboard.

I think we should have a note/section explaining this to users who may be upgrading from the legacy UI.

**Comment by catherineluse** [comment]
I suggest putting it in the installation requirements under networking.
