### ISSUE TITLE
[Rancher2] Clarify EncryptionConfiguration for Rancher Backup Operator

### ISSUE THREAD

**Issue by oxr463** [rancher/docs#4008]
**Request Summary:**

Can we use this `EncryptionConfiguration` as-is for the Rancher Backups Operator? Does it really read `key1` and `key2` values?

**Details:**

https://rancher.com/docs/rancher/v2.6/en/backups/examples/#example-encryptionconfiguration

**Comment by brandond** [comment]
From Slack:
> The first example is of a Secret for encrypting the backup files themselves. The second example is an etcd secrets encryption config file, it has nothing to do with the backup operator; I’m not sure why it’s on that page… other than I guess if you’re backing up etcd you would also need to back up your encryption config, otherwise you wouldn’t be able to use your restored data.

So no, the backup operator does not read the secrets encryption file. It only uses the contents of the secret.

We should explain why we have a secrets encryption configuration file example on that page.
