### ISSUE TITLE
New Page Layouts

### ISSUE THREAD

**Issue by MBishop17** [rancher/docs#401]
We're finding a need for a couple new page templates.

1. A list page template that automatically generates links to subpages, like in the example below.

![image](https://user-images.githubusercontent.com/37810556/42351313-1e682936-8069-11e8-8147-72daa1ab251b.png)

2. A single page that has last/next pagination links, for reading pages in a sequential order. 

![image](https://user-images.githubusercontent.com/37810556/42351353-695c6718-8069-11e8-963b-4954a54b194b.png)

**Comment by deniseschannon** [comment]
@MBishop17 do we still need these?

**Comment by MBishop17** [comment]
No longer needed. Closing issue.
