### ISSUE TITLE
v2.6.5 Release Task - Publish Initial PRs of Release Notes

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/docs#4025]
**Docs Release Task**
This is a release task (https://github.com/rancher/rancher/issues/37315) for the docs team to publish the first draft of the PRs of the release notes for v2.6.5.

The engineering team should have added `release-note` labels to all associated features by now.

**Comment by jtravee** [comment]
Completed first draft of release notes today; tagged managers for review and posted in the release channel.
