### ISSUE TITLE
v2.6.5 Release Task - Complete Writing of the RKE Release Notes

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/docs#4026]
**Docs Release Task**
This is a release task (https://github.com/rancher/rancher/issues/37315) for the docs team to finalize the RKE release notes for the upcoming version of RKE.

Check in with Team 2 to ensure there is nothing special going into the RKE that needs to be accounted for.

**Comment by jtravee** [comment]
Verifying with @kinarashah as [v1.3.10](https://github.com/rancher/rke/releases/tag/v1.3.10) was already completed on 29 April outside of the docs team. Will complete 2.5 version if need be.

**Comment by btat** [comment]
Link to [v1.3.11](https://github.com/rancherlabs/release-notes/pull) PR
