### ISSUE TITLE
v2.6.5 Release Task - Complete Writing of the Rancher Release Notes

### ISSUE THREAD

**Issue by Jono-SUSE-Rancher** [rancher/docs#4027]
**Docs Release Task**
This is a release task (https://github.com/rancher/rancher/issues/37315) for the docs team to finalize the Rancher release notes for the version v2.6.5.

The corresponding PRs should have received ample approval for this task.

**Comment by jtravee** [comment]
Completed the 2.6.5 RN, final approvals received today.

**Comment by btat** [comment]
[Release notes PR](https://github.com/rancherlabs/release-notes/pull/237) has been merged
