### ISSUE TITLE
Cluster usage metrics will be removed from rancher homepage cluster list

### ISSUE THREAD

**Issue by aalves08** [rancher/docs#4028]
**Request Summary:**
Cluster usage metrics will be removed from rancher homepage cluster list for 2.6.5. Users can check usage per cluster, using cluster dashboard.

Connected to Github issue: [#5430](https://github.com/rancher/dashboard/issues/5430)
Connected to Zube issue: [#5416](https://zube.io/rancher/dashboard-ui/c/5416)
PR: [merged](https://github.com/rancher/dashboard/pull/5542)

FYI @richard-cox @nwmac

**Comment by btat** [comment]
Entry has been added to [release notes PR](https://github.com/rancherlabs/release-notes/pull/237).
