### ISSUE TITLE
Cluster Explorer UI documentation is either hard to find or doesn't exist

### ISSUE THREAD

**Issue by burkestar** [rancher/docs#4033]
**Detailed Description**
Is there any documentation for Cluster Explorer?

I'm using the Rancher Cluster Explorer v2.5.8 and would like to find documentation around how to filter pods with more advanced criteria (by metadata.annotations, for example).  Something like "kubectl get pods -o jsonpath" with some query expression to filter on matching metadata tags.

A quick google search shows no useful results.  I would like to understand what the capabilities and limitations of the Cluster Explorer UI are, so I try to navigate to the documentation.  I scroll to the bottom of the page and see "Docs" link.  That brings me to the [main page for Rancher documentation](https://rancher.com/docs/rancher/v2.6/en/) rather than an area specific to Cluster Explorer.  I couldn't find Cluster Explorer in the left-side navigation and a search using "?" in the top right shows a few pages mentioning it in passing, but without any details.
![image](https://user-images.githubusercontent.com/177557/139240513-7fd7674c-2504-4220-90d1-8dba4447d2de.png)

This leads me to the conclusion that documentation for the Cluster Explorer does not exist, but perhaps should.

**Context**
Having detailed documentation would be helpful, especially for more advanced features.

**Comment by btat** [comment]
Closing as issue seems to be addressed by the [comment above](https://github.com/rancher/docs/issues/4033#issuecomment-1100957985).
