### ISSUE TITLE
Please add reminder of Monitoring v1 deprecation to Release Notes for 2.6.5

### ISSUE THREAD

**Issue by SheilaghM** [rancher/docs#4037]
**Summary:**
With the delivery of Project Monitoring v2 in Rancher Manager v2.6.5, Monitoring v2 is now at parity with Monitoring v1.  Monitoring v1 was deprecated in Rancher v2.5 and will be removed in an upcoming release.

**Details:**
We do not want to be any more specific about "upcoming release" because we want customers still on v1 to contact us so we can estimate how many customers are still using it.  Otherwise, feel free to massage the language.

**Comment by btat** [comment]
Entry has been added to [release notes PR](https://github.com/rancherlabs/release-notes/pull/237).
