### ISSUE TITLE
RKE - Config Options Documentation Issues

### ISSUE THREAD

**Issue by Sheldons92** [rancher/docs#4041]
**Summary:**

There is differences between Cases and wording on the Secrets-Encryption RKE page https://rancher.com/docs/rke/latest/en/config-options/secrets-encryption/#example-using-custom-encryption-configuration-with-user-provided-32-byte-random-key

**Details:**

See line 5 of the code snippet it says “api_version” the rest of the documentation and the input i’d expect is “apiVersion” Also the document changes between lower and upper case R for "Resources" It would be good to clarify which should be used.

**Comment by jtravee** [comment]
@Sheldons92, we are still testing using upper and lowercase "resources" to give you the best information on how to proceed; I'll update you once we have a verdict.
