### ISSUE TITLE
[Rancher2] 2.6.7 release note about performance

### ISSUE THREAD

**Issue by cbron** [rancher/docs#4043]
We'll need to add a general notice/alert about upstream performance changes in 2.6.5. 

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.24.md#feature-1

> Kubernetes 1.24 bumped version of golang it is compiled with to go1.18, which introduced significant changes to its garbage collection algorithm. As a result, we observed an increase in memory usage for kube-apiserver in larger an heavily loaded clusters up to ~25% (with the benefit of API call latencies drop by up to 10x on 99th percentiles).

**Comment by cbron** [comment]
This will be bumped back, as 1.24 support has been bumped back.

**Comment by btat** [comment]
Added to https://github.com/rancherlabs/release-notes/pull/260/
