### ISSUE TITLE
[Rancher2] Document rancher cli is not compatible with apps[feature charts] from dashboard UI

### ISSUE THREAD

**Issue by anupama2501** [rancher/docs#4044]
**Request Summary:**
Dashboard apps or rancher feature charts cannot be installed via rancher CLI. 

https://rancher.com/docs/rancher/v2.6/en/cli/
https://rancher.com/docs/rancher/v2.6/en/helm-charts/

**Comment by btat** [comment]
Closed via https://github.com/rancher/docs/pull/4090
