### ISSUE TITLE
Document NeuVector Integration for 2.6.5

### ISSUE THREAD

**Issue by jtravee** [rancher/docs#4046]
In 2.6.5, there is a NeuVector sidebar and button after the chart is installed. We should document the NeuVector integration and how to navigate to it in the Rancher UI.

Reference: https://open-docs.neuvector.com/deploying/rancher#deploy-and-manage-neuvector-through-rancher-apps-marketplace

See [#5292](https://github.com/rancher/dashboard/pull/5292) for more details.

**Comment by cbron** [comment]
One note in linked issue above.
Another note: https://github.com/rancher/rancher/issues/37447
