### ISSUE TITLE
Update AzureAD auth provider setup instructions

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/docs#4047]
**Request Summary:**
Related to https://github.com/rancher/rancher/issues/29306
Needed for `v2.6.7`.

We need to add a new section with instructions on how to set up AzureAD (OAuth) as the external auth provider in Rancher through the new flow via the Microsoft Graph API. The current instructions describe how to set up an app in Azure for the deprecated flow via the Azure AD Graph API.

The update warrants two different tabs:
1. The Rancher 2.6.0 - 2.6.6 tab: the current setup instructions will be removed because it is impossible to grant the necessary permissions to apps on the Azure portal, since Microsoft have marked the old Azure AD Graph API as deprecated. They don't allow to use it (it's grayed out in the UI). Instead, the tab will describe the migration process for existing deprecated setups. 
1. The Rancher 2.6.7+ tab will have the full instructions on how to set Azure AD with Rancher on both sides (Azure portal and Rancher). There will be new screenshots.

This would need a backport for the v2.5.x version of the docs.

**Details:**
## New authentication and authorization flow via Microsoft Graph API:
- Provide instructions on how to set it up (namely what permissions are needed). Those are application (not delegated) permissions: `Graph.Read.All` and `User.Read.All`. This is the same for new and existing apps that need to be updated on Rancher upgrade and endpoint update.
## Existing (deprecated) authentication and authorization flow via Azure AD Graph API:
- It would be good to update the screenshots from the Azure portal, as its UI has changed significantly in the last couple of years.
- Explicitly say that Rancher has been changed to use the new Microsoft Graph API instead of the old Azure AD Graph API (to be retired by end of 2022)
- Describe the endpoint update process (migration) of deprecated setups (Rancher upgrade scenario)
  - Show a screenshot of the banner in the UI and the button that performs the endpoint update (which completes the move to the new Microsoft Graph API)
  - Refer to the table below for the full list of endpoint changes that Rancher performs (admins need not do this manually)
  - Mention that before admins are ready to press the button and commit to the endpoint update, they must ensure their Azure app has a new set of permissions (the old permissions would no longer be needed)
- Include a note on air-gap environments for customers who whitelist endpoints, since the Graph Endpoint URL is changing
## General
- Describe the steps to revert the migration (admins must edit the authconfig resource named `azuread` and specify the endpoints according to a table below, as well as remove the `auth.cattle.io/azuread-endpoint-migrated` annotation).
- Mention that Rancher does not make assumptions about Custom endpoints, it's on admins to ensure they are properly specified.
- Mention how Azure app owners who might want to rotate the Application Secret would need to do the same in Rancher (stored in a Kubernetes secret called `azureadconfig-applicationsecret` in the `cattle-global-data` namespace), since Rancher won't automatically update the Application Secret when it is changed in Azure.
- Mention that if admins upgrade to Rancher v2.6.7 with an existing Azure AD setup and choose to disable the auth provider, they won't be able to restore the previous setup and will need to register anew, now with the new auth flow in mind, as there won't be a way to explicitly set up Azure AD the old way, Rancher will use the new Graph API and, therefore, would need to have the proper permissions in the Azure portal.

#### Deprecated endpoints
Auth Endpoint:       https://login.microsoftonline.com/{tenantID}/oauth2/authorize
Endpoint:            https://login.microsoftonline.com/
Graph Endpoint:      https://graph.windows.net/
Token Endpoint:      https://login.microsoftonline.com/{tenantID}/oauth2/token

#### New endpoints
Auth Endpoint:       https://login.microsoftonline.com/{tenantID}/oauth2/v2.0/authorize
Endpoint:            https://login.microsoftonline.com/
Graph Endpoint:      https://graph.microsoft.com
Token Endpoint:      https://login.microsoftonline.com/{tenantID}/oauth2/v2.0/token

#### Deprecated endpoints
Auth Endpoint:       https://login.chinacloudapi.cn/{tenantID}/oauth2/authorize
Endpoint:            https://login.chinacloudapi.cn/
Graph Endpoint:      https://graph.chinacloudapi.cn/
Token Endpoint:      https://login.chinacloudapi.cn/{tenantID}/oauth2/token

#### New endpoints
Auth Endpoint:       https://login.partner.microsoftonline.cn/{tenantID}/oauth2/v2.0/authorize
Endpoint:            https://login.partner.microsoftonline.cn/
Graph Endpoint:      https://microsoftgraph.chinacloudapi.cn
Token Endpoint:      https://login.partner.microsoftonline.cn/{tenantID}/oauth2/v2.0/token

**Comment by jtravee** [comment]
Tasks for docs team:

- [ ] Update docs
- [ ] Add release note for 2.6.7

**Comment by btat** [comment]
Added to https://github.com/rancherlabs/release-notes/pull/260
