### ISSUE TITLE
[Rancher2] Add NeuVector Page

### ISSUE THREAD

**Issue by samjustus** [rancher/docs#4051]
**Request Summary:**
Add a page related to the new Neuvector integration

**Details:**
should link back to this: (https://open-docs.neuvector.com/deploying/rancher#deploy-and-manage-neuvector-through-rancher-apps-marketplace)

**Comment by cbron** [comment]
Docs team can handle this however they like. If fleet/longhorn have a pre-existing pattern. 
Also NeuVector will need a top-line release note, as it is a flagship feature of 2.6.5.

**Comment by samjustus** [comment]
closing as duplicate of https://github.com/rancher/docs/issues/4046
