### ISSUE TITLE
[Rancher2] Update 2.6.5 release notes/support matrix - RKE2 cluster provisioning fails using the public golden RHEL 8.5 AWS AMI

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/docs#4052]
**Request Summary:**
RKE2 cluster provisioning fails using the public golden RHEL 8.5 AWS AMI

**Details:**
Issue - https://github.com/rancher/rancher/issues/36731 ; pushed back to milestone 2.6.6.

Please document this in 2.6.5 release notes and in 2.6.5 support matrix

Workaround - https://github.com/rancher/rancher/issues/36731#issuecomment-1058230553

**Comment by btat** [comment]
Entry has been added to [release notes PR](https://github.com/rancherlabs/release-notes/pull/237).
