### ISSUE TITLE
[Rancher2] RHEL 8 installation instruction additions

### ISSUE THREAD

**Issue by paynejacob** [rancher/docs#4055]
**Request Summary:**
Redhat changed their default firewall in 8.4.  This prevents rke1 pods from reaching out to rancher to connect the cluster agent.  We need to add a note to the linked section to run the commands below before installing docker.  This will allow docker containers to reach out to the internet and connect to rancher.

```
firewall-cmd --zone=public  --add-masquerade --permanent
firewall-cmd --reload
```

**Details:**
https://rancher.com/docs/rke/latest/en/os/#red-hat-enterprise-linux-rhel-oracle-linux-ol-centos

**Comment by manuelbuil** [comment]
This change creates a bug: https://jira.suse.com/browse/SURE-4840

Note that it applies masquerade to ALL interfaces, even the ones used for internal cluster communication like flannel.1. It should avoid the masquerade when the destination IP is inside the internal clusterCIDR
