### ISSUE TITLE
[Rancher2] Release note OPA gatekeeper bug in presence of Windows nodes

### ISSUE THREAD

**Issue by sirredbeard** [rancher/docs#4061]
Synopsis: OPA Gatekeeper gets stuck when uninstalling on Windows clusters https://github.com/rancher/rancher/issues/37029
Resolved (or not): It is not resolved in 2.6.5
Status: A PR is open, fix is slated for 2.6.6 https://github.com/rancher/charts/pull/1872
Versions: 2.6.5

**Comment by btat** [comment]
Entry has been added to [release notes PR](https://github.com/rancherlabs/release-notes/pull/237).
