### ISSUE TITLE
[Rancher2] DaemonSet requirement (Step 5 of HA RKE2)

### ISSUE THREAD

**Issue by axsgitty** [rancher/docs#4072]
**Request Summary:**

https://rancher.com/docs/rancher/v2.6/en/installation/resources/k8s-tutorials/ha-rke2/
In step 5, I don't understand how to apply the values. What name should we provide the values file, or should we slip it into the existing yaml? How do we apply it after we create a new file or add it to the existing yaml? 

I know this is likely obvious to users who have worked with helm charts before, but I've gotten lost in a few places within the HA RKE2 Rancher install docs. I believe this is a good example of an assumption of knowledge that us new folks don't have. 

**Details:**

**Comment by brandond** [comment]
We actually just removed that section from the docs in https://github.com/rancher/docs/pull/4071 - I'm not sure how long it takes to show up live. That bit hasn't been necessary in while.

**Comment by axsgitty** [comment]
Thank you, a refresh of that page shows it's removed.

**Comment by axsgitty** [comment]
Reopened because a reference to the previous requirement and the since removed section is on this page: https://rancher.com/docs/rancher/v2.6/en/installation/requirements/#rke2-specific-requirements

"The Ingress should be deployed as DaemonSet to ensure your load balancer can successfully route traffic to all nodes. Currently, RKE2 deploys nginx-ingress as a deployment by default, so you will need to deploy it as a DaemonSet by following [these steps.](https://rancher.com/docs/rancher/v2.6/en/installation/resources/k8s-tutorials/ha-rke2/#5-configure-nginx-to-be-a-daemonset)"
