### ISSUE TITLE
[Rancher2] Backup restore app requires new changes to be documented

### ISSUE THREAD

**Issue by anupama2501** [rancher/docs#4081]
**Request Summary:**

**This is only applicable from rancher version 2.6.4+**

Following steps should be added at https://rancher.com/docs/rancher/v2.6/en/backups/restoring-rancher/#create-the-restore-custom-resource.

Note: These steps are required only when user wants to roll back rancher on the same cluster. 

**Details:**

1. Run the script `verify.sh` to retrieve the resources to be deleted.
2. Run the script `cleanup.sh` to delete all the retrieved resources. 
For additional info on the scripts please refer to https://github.com/superseb/support-tools/tree/636a06134951ab38ba9763a8658f5247716aeb05/cleanup-rancher-k8s-resources

```
Note: 

- The script deletes all the resources created by rancher
- The script can be run on any linux nodes. 
- Rancher will be down as the `cleanup.sh` runs as it deletes the resources created by rancher.
- Script took approximately 45 minutes to complete on a cloud shell on our test environment with 5 downstream clusters. For better performance script can be run on rancher local cluster nodes. In this case script takes 20 minutes approximately to complete depending on the number of clusters.

```
3. Once the cleanup.sh script finishes, run the script `verify.sh` to make sure all the resources are deleted. 
4. Follow the docs to install rancher backup/charts on the existing cluster and restore the previous state. https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/ excluding step3.
5. Install required rancher 2.6.x version on the local cluster to roll back rancher to the previous version.

**Comment by superseb** [comment]
This has been updated to https://github.com/rancherlabs/support-tools/tree/master/rancher-cleanup with the instructions in the README

**Comment by btat** [comment]
> This has been updated to https://github.com/rancherlabs/support-tools/tree/master/rancher-cleanup with the instructions in the README

@superseb Just to confirm, the instructions from the README should replace only steps 1-3 from the original issue description?

**Comment by anupama2501** [comment]
@btat that is correct. We would need to replace the steps 1-3 from the original posted description.

**Comment by JlKio** [comment]
I just clean up, and generate the restore like  indicate in the step4 :https://rancher.com/docs/rancher/v2.6/en/backups/migrating-rancher/ 

but  i have an error in the restore:

INFO[2022/07/08 17:57:58] Starting to restore CRDs for restore CR restore-migration
INFO[2022/07/08 17:57:58] restoreResource: Restoring catalogtemplateversions.management.cattle.io of type apiextensions.k8s.io/v1, Resource=customresourcedefinitions
INFO[2022/07/08 17:57:58] Processing controllerRef apps/v1/deployments/rancher
WARN[2022/07/08 17:57:58] Error getting object for controllerRef rancher, skipping it
ERRO[2022/07/08 17:57:58] Error restoring CRDs restoreCRDs: CustomResourceDefinition.apiextensions.k8s.io "catalogtemplateversions.management.cattle.io" is invalid: [spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required, spec.preserveUnknownFields: Invalid value: true: cannot set to true, set x-preserve-unknown-fields to true in spec.versions[*].schema instead]
ERRO[2022/07/08 17:57:58] error syncing 'restore-migration': handler restore: error restoring CRDs, check logs for exact error, requeuing
