### ISSUE TITLE
[Rancher2] Clarify "Hosted Kubernetes" terminology and when to (and not to) install ingress controller

### ISSUE THREAD

**Issue by edqallen** [rancher/docs#4109]
**Request Summary:**
The install documentation for Rancher via Helm indicates you should install an ingress controller if your cluster is "hosted."  This terminology is unclear and to be blunt, doesn't make any sense, as all clusters are "hosted", somewhere, on some sort of infrastructure.  The examples given of a "hosted" cluster are a few commercial cloud providers, where as my clusters are self-hosted.

The specific technical reasons that explain when you need to install an ingress controller vs. when you don't would be helpful here, instead of this unclear terminology.  The documentation indicates that Rancher will install it's own ingress controller, yet I have yet to see this happen.  I have been struggling with a fresh Rancher install via Helm for several days, and I think it's related to this.  My previous installs were all done with either the standalone single-node test, or the k3s quickstart.

My assumption upon reading the ambiguous documentation was that since I was not hosted at some commercial cloud provider that I did not need to manually install an ingress controller, and Rancher would do that for me.  This was just a guess though and now I am starting to think it may be incorrect.

**Comment by bashofmann** [comment]
It's actually quite simple: Rancher expects an ingress controller in the cluster and the Rancher UI and API is exposed through an Ingress. The Rancher Helm chart does not install an ingress controller, but expects one to be there.
Our own Kubernetes distributions (RKE1, RKE2 and K3s) bundle an ingress controller by default. That's why you don't have to install one.
Other distributions don't do this, e.g. if you install Rancher on a cluster created with kubeadm. Similarly, a lot of "Hosted Kubernets distrubtions" don't include one by default. In this context, the docs mean a fully managed "hosted" solution from one of the big cloud providers.

The process is, first:

* Provision a Kubernetes cluster with the distribution of your choice on the environment of your choice
* If not included, install an ingress controller
* Make sure that the ingress controller is exposed somehow (Load Balancer in front, DNS entry)

This highly depends on the environment and the chosen Kubernetes distribution. Because of this the docs have different tutorials for the most common distributions.

After that:
* Install cert-manager or provide your own TLS certificate
* Install Rancher

After the pre-requisites in the first step are done, this is the same for all distributions.

After re-reading the installation page, this should definitely be cleaned up a bit and structured better. All the information is there, but it could be structured and worded a bit differently to make this clearer.

@jtravee If you want, I can start a small PR to rework this and then we can iterate on it.

**Comment by edqallen** [comment]
> Rancher expects an ingress controller in the cluster and the Rancher UI and API is exposed through an Ingress. The Rancher Helm chart does not install an ingress controller, but expects one to be there. Our own Kubernetes distributions (RKE1, RKE2 and K3s) bundle an ingress controller by default. That's why you don't have to install one. Other distributions don't do this, e.g. if you install Rancher on a cluster created with kubeadm. Similarly, a lot of "Hosted Kubernets distrubtions" don't include one by default. In this context, the docs mean a fully managed "hosted" solution from one of the big cloud providers.

Thanks for the response!  I think just explaining it this way and forgetting that "hosted" term would help out a great deal.  Just swapping "non-Rancher kubernetes distribution" for "hosted" would make it clear, though explicitly listing them (RKE, K3S) would of course be even better.

> The process is, first:
> 
> * Provision a Kubernetes cluster with the distribution of your choice on the environment of your choice
> * If not included, install an ingress controller
> * Make sure that the ingress controller is exposed somehow (Load Balancer in front, DNS entry)
> 

> This highly depends on the environment and the chosen Kubernetes distribution. Because of this the docs have different tutorials for the most common distributions.

I don't think I agree with this, but I don't have much of a sample to draw on.  There's no tutorial for bog-standard K8S, which strikes me as more popular (or at least more "important") than e.g. AKS or even GKE.

> After that:
> 
> * Install cert-manager or provide your own TLS certificate
> * Install Rancher
> 
> After the pre-requisites in the first step are done, this is the same for all distributions.

I believe there is more to it than this when it comes to K8S, or that needed details are missing, which is the path which lead me to opening this issue.  I have a pretty standard K8S automated install for our vmware cluster which uses Packer, Terraform, and Ansible to create and setup a cluster consisting of three control plane nodes, three worker nodes, and an external load balancer.  The clusters are functional after being created and we use them to host a variety of workloads.  We use Rancher to administer them after creation by importing them as "Generic" without problems.

The cluster itself uses metallb to provide a "public" address for the cluster as well as nginx-ingress (note: nginx-ingress being the nginx release, `nginx-ingress nginx-stable/nginx-ingress` as opposed to `ingress-nginx` which is an nginx release from kubernetes.io).

When installing Rancher onto onto one of these clusters however, the connection between the ingress controller and Rancher just doesn't happen.  I struggled to figure out what was going on for a week or so, trying different configuration options for the nginx ingress as well as with and without metallb vs. the external haproxy LB, but finally gave up yesterday after spending too much time on it and just created new terraform/ansible configurations to create and deploy a K3S cluster for Rancher.

Thinking back on it now I wonder if it wasn't just an issue with the ingressClass or something -- I can't remember if I investigated this fully -- but this is one of the things the documentation should make clear, IMO.

> After re-reading the installation page, this should definitely be cleaned up a bit and structured better. All the information is there, but it could be structured and worded a bit differently to make this clearer.

I'm sure I'm not alone in my appreciation for any effort in this regard!  I clearly lack the knowledge required to author such changes myself or I would have just sent in a detailed change request, but I'm more than happy to try following the instructions from start to finish once they're updated to see if any steps are missing or not well explained.

**Comment by bashofmann** [comment]
@edqallen thanks for the detailed feedback. 

> When installing Rancher onto onto one of these clusters however, the connection between the ingress controller and Rancher just doesn't happen. I struggled to figure out what was going on for a week or so, trying different configuration options for the nginx ingress as well as with and without metallb vs. the external haproxy LB, but finally gave up yesterday after spending too much time on it and just created new terraform/ansible configurations to create and deploy a K3S cluster for Rancher.
> 
> Thinking back on it now I wonder if it wasn't just an issue with the ingressClass or something -- I can't remember if I investigated this fully -- but this is one of the things the documentation should make clear, IMO.

Sounds like your case is actually related to ingressClasses. To be compatible with different ingress controllers, the Rancher helm chart does not set an ingressClassName. There is a PR to make this optionally configurable though.

Depending on the ingress controller, you may need to configure the controller to also pick up ingresses without a class name. I think with the NGINX ingress from NGINX Inc, you can do this with `controller.setAsDefaultIngress` which defaults to `false` (https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/).

This is an important additional point, that I'll try to make clearer in the docs.

> I don't think I agree with this, but I don't have much of a sample to draw on. There's no tutorial for bog-standard K8S, which strikes me as more popular (or at least more "important") than e.g. AKS or even GKE.

From our data and conversations with open source users and customers, the most popular option by far is to install Rancher on top of a RKE or K3s cluster. Followed by GKE, EKS and AKS for projects that are running in the cloud only.
