### ISSUE TITLE
[Rancher2] Missing use of predefined node template in cluster pool settings

### ISSUE THREAD

**Issue by johnwc** [rancher/docs#4116]
**Request Summary:**
The docs talk about creating a node template for vSphere, but when deploying a cluster for vSphere there is no option to select the predefined node template. You have to fully configure the node settings in each pool.

**Details:**
[Create a cluster with node pools using the node template](https://github.com/rancher/docs/blob/master/content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/provisioning-vsphere-clusters/_index.md#3-create-a-cluster-with-node-pools-using-the-node-template)

**Comment by jtravee** [comment]
@phillipsj, would you be able to address this?

**Comment by phillipsj** [comment]
@jtravee there are not predefined node templates in v2prov. The only correct way in RKE2 is for the node settings for each pool. I think having someone from Team 2 look over the docs would be best.

**Comment by jtravee** [comment]
> **Request Summary:** The docs talk about creating a node template for vSphere, but when deploying a cluster for vSphere there is no option to select the predefined node template. You have to fully configure the node settings in each pool.
> 
> **Details:** [Create a cluster with node pools using the node template](https://github.com/rancher/docs/blob/master/content/rancher/v2.6/en/cluster-provisioning/rke-clusters/node-pools/vsphere/provisioning-vsphere-clusters/_index.md#3-create-a-cluster-with-node-pools-using-the-node-template)

Hi @johnwc, could you confirm that for the scenario you're describing, you are provisioning an RKE2 cluster? If so, RKE2 provisioning doesn't utilize node templates and so as you stated, there would be no way currently of refining or reusing one. This would be something we could request as a UI enhancement. Please confirm and thanks!

**Comment by johnwc** [comment]
Yes, it is for RKE2. Prior to creating this issue, I was not aware that the node templates were only for RKE and not RKE2. I created a issue over in the dashboard repo about this as well https://github.com/rancher/dashboard/issues/6020, and apparently there is a feature request for this very thing as well https://github.com/rancher/dashboard/issues/5981.

**Comment by jtravee** [comment]
Closing at this time as this pertains to a UI enhancement.
