### ISSUE TITLE
[Rancher2] AWS CSP Adapter Documentation

### ISSUE THREAD

**Issue by MbolotSuse** [rancher/docs#4131]
To complete the AWS marketplace integration, we need to produce documentation to assist customers in stalling and configuring the csp adapter. 

This documentation will need to include:
- Pre-requisites for the install
- Limitations on usage (which cluster types work, etc.)
- Additional required steps for auth integration (OIDC provider, IAM role with narrow trust policy + permissions)
- Helm command to install the chart
- Troubleshooting/Additional steps
- Information on issues that might occur if you attempt to uninstall/re-install the adapter within a 1 hour period

**Comment by MbolotSuse** [comment]
In line with the discussion on rancher/rancher#37888, these docs should also include uninstall commands for the csp adapter.

**Comment by jtravee** [comment]
Hi @MbolotSuse, would you be able to provide us with details to fill out the above bullet points? Currently we just have [this brief doc](https://rancher.com/docs/rancher/v2.6/en/quick-start-guide/deployment/amazon-aws-marketplace-qs/) that essentially refers back to Amazon. Thanks in advance.

**Comment by MbolotSuse** [comment]
@jtravee Definitely. Right now the plan is for me to write a good portion of this up in detail so that this is feasible on your end. I will attach a PR here when I get to that point.

**Comment by MbolotSuse** [comment]
PR: rancher/docs#4143

**Comment by MbolotSuse** [comment]
One note here: It looks like our docs to install rancher on an EKS cluster are out of date. Namely, it uses version 1.20 which [is EOL](https://kubernetes.io/releases/patch-releases/#support-period) as of the end of feburary.

**Comment by jtravee** [comment]
Docs team: Please add a note to 2.6.7 RN for new features.

**Comment by jtravee** [comment]
> One note here: It looks like our docs to install rancher on an EKS cluster are out of date. Namely, it uses version 1.20 which [is EOL](https://kubernetes.io/releases/patch-releases/#support-period) as of the end of February.

Thanks for this! I'll update this when I complete [this one](https://github.com/rancher/docs/issues/4192).

**Comment by btat** [comment]
Completed via https://github.com/rancher/docs/pull/4143
