### ISSUE TITLE
[Rancher2] Update API Tokens page

### ISSUE THREAD

**Issue by KevinJoiner** [rancher/docs#4139]
**Request Summary:**

Updates to the API Tokens page to explain the behavior of API tokens settings and how they interact with each other.

**Details:**

There have been [updates](https://github.com/rancher/rancher/pull/37703) to API tokens with the addition of new global settings to control TTL. We also have experience confusion about the behavior of different tokens due to unclear setting names.

**Comment by btat** [comment]
Closed via https://github.com/rancher/docs/pull/4140
