### ISSUE TITLE
[Rancher2] Conflicting instructions for creating readme file for Charts

### ISSUE THREAD

**Issue by leodotcloud** [rancher/docs#4154]
**Request Summary:**

URL: https://rancher.com/docs/rancher/v2.6/en/helm-charts/creating-apps/

It's not clear from the docs, if one needs to create `README.md` or `app-readme.md` in the chart.

**Comment by PennyScissors** [comment]
@leodotcloud They both need to be created, they are not interchangeable. `README.md` contains all the important information regarding an app like what it does, the values you can set to configure it, cluster requirements, maintainers, etc, whereas `app-readme.md` is a brief description of the app the UI displays in the app's installation page. The `app-readme.md` is commonly just a copy of the description of the app and important requirements found in the `README.md` as that's what we would like a user to see right away.

**Comment by jtravee** [comment]
Closing issue as per @PennyScissors, docs shouldn't need to be updated at this time.
