### ISSUE TITLE
Document new process to add Project Monitors

### ISSUE THREAD

**Issue by jtravee** [rancher/docs#4206]
- [x] Document steps to add Project Monitoring V2 to monitoring (new doc to be created)
- [ ] Update 2.6.7 release notes with the above updates, link to docs.

cc @MKlimuszka

**Comment by jtravee** [comment]
Creating a new issue for updating migration steps to be completed ~2.7.1.

**Comment by btat** [comment]
Removing release note component. Adding a Project Monitor is not a new feature so it'd be strictly calling out a doc update in the release note, which we normally don't do.
