### ISSUE TITLE
[Rancher2] RKE2 Encryption Key Rotation Docs

### ISSUE THREAD

**Issue by snasovich** [rancher/docs#4215]
**Request Summary:**
For 2.6.7, we're enabling encryption key rotation for RKE2 provisioned clusters (per https://github.com/rancher/rancher/issues/35436) and it needs to be documented.

**Details:**
As part of the overall RKE2 Provisioning docs issue (https://github.com/rancher/docs/issues/3752) it was determined that documentation covering encryption key rotation doesn't exist even for RKE1, so not sure if this should be done together. Still, creating this ticket to track the addition of RKE2-specific documentation.
Engineering contact: @jakefhyde

**Comment by jtravee** [comment]
Also create release note for 2.6.7.
