### ISSUE TITLE
[Rancher2] Rancher 2.5.9 - backup / restore causes two default-tokens in each namespace

### ISSUE THREAD

**Issue by DevOpsNewbie** [rancher/docs#4254]
**Request Summary:**

It seems to be a known issue in Rancher 2.5.x, that after restoring from the Rancher backup operator, it creates duplicated default-tokens secrets in restored namespaces.

Therefore I would suggest adding a section to the installation page warning about that fact and pointing the users to either upgrade to Rancher 2.6.4. or run a workaround script.

Maybe similar to how its done here: https://rancher.com/docs/rancher/v2.6/en/backups/restoring-rancher/#known-issues

**Details:**

Some example issues from [rancher/rancher](https://github.com/rancher/rancher/issues)

-   https://github.com/rancher/backup-restore-operator/issues/165

**Comment by DevOpsNewbie** [comment]
PR https://github.com/rancher/docs/pull/4253

**Comment by btat** [comment]
Closing. See [comment from PR #4253](https://github.com/rancher/docs/pull/4253#issuecomment-1237761239)
