### ISSUE TITLE
[K3s] Information on k3s log rotation

### ISSUE THREAD

**Issue by farbabzadah22** [rancher/docs#4268]
**Request Summary:**

Add a new section on k3s log rotation to the following page in the k3s documentation: [https://rancher.com/docs/k3s/latest/en/advanced/](url). 
Provide relevant information regarding the default configuration for log rotation in a k3s cluster; list configuration options (using customized kubelet flags, the INSTALL_K3S_EXEC environment variable, or the CONFIG file).
**Details:**

**Comment by jtravee** [comment]
cc @dereknola

**Comment by btat** [comment]
@dereknola @brandond When should we start redirecting folks to the K3s repo instead?

**Comment by dereknola** [comment]
@btat yes that would be helpful! We have stopped updating the rancher k3s docs.

**Comment by dereknola** [comment]
@farbabzadah22 K3s does not have log rotation support. Its simply a single log file. See https://rancher.com/docs/k3s/latest/en/faq/ (old site) or https://k3s-io.github.io/docs/docs/faq#where-are-the-k3s-logs (new site)

**Comment by farbabzadah22** [comment]
@dereknola - thanks for the reply. I am referring to container log rotation performed by the kubelet process ([https://www.suse.com/support/kb/doc/?id=000020071#:~:text=Two%20kubelet%20flags,as%20a%20service.](url)) Kubernetes default settings seem to suggest that a container log file is rotated when it grows beyond 10Mi in size, and that up to five (5) log files per container are kept.

**Comment by brandond** [comment]
We don't modify any of the kubelet behavior with regards to logging. You can find the default values in the upstream documentation: 

https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/#:~:text=container%2Dlog%2Dmax%2Dfiles
> --container-log-max-files int32     Default: 5
> --container-log-max-size string     Default: 10Mi
