### ISSUE TITLE
[Rancher2] aws listing docs url should be migrated correctly

### ISSUE THREAD

**Issue by cbron** [rancher/docs#4310]
We are linking out to this url from a AWS listing: https://rancher.com/docs/rancher/v2.6/en/installation/cloud-marketplace/

The listing takes a while to update so we don't want to have an out-of-band change here surprise us. The docs team can either leave that URL as-is, or add a 301 redirect to the new page, either is fine with us, as long as this url doesn't suddenly 404 in the future. Thanks!

**Comment by btat** [comment]
Closed via https://github.com/rancher/docs/pull/4311
