### ISSUE TITLE
Logos are getting trimmed on Devices

### ISSUE THREAD

**Issue by jino-suse** [rancher/docs#4329]
Hi, 

The product logos are getting trimmed on devices. Screenshots attached for reference.

![Screenshot_2](https://user-images.githubusercontent.com/88501140/193198714-8940debc-03b8-49fd-beef-baf87745feda.png)
![Screenshot_1](https://user-images.githubusercontent.com/88501140/193198725-6609ded1-ddea-47cc-874c-d70aab9b6a91.png)

**Comment by btat** [comment]
cc @catherineluse
