### ISSUE TITLE
Docs page Header menu to be synced with Rancher main header

### ISSUE THREAD

**Issue by jino-suse** [rancher/docs#4330]
Hi ,

Currently the header is not in sync with the rancher main header. Screenshot attached for reference.
![Screenshot_9](https://user-images.githubusercontent.com/88501140/193199232-272db172-5cf8-40dd-a8a7-e67e1b265f2c.png)
![Screenshot_8](https://user-images.githubusercontent.com/88501140/193199236-5fcd7b5f-3ff8-410b-bf23-80e43e9bf6a0.png)

**Comment by btat** [comment]
cc @catherineluse

**Comment by catherineluse** [comment]
@jino-suse Can you please send me the full scss file from the header source code in the other repo? it should be under `assets/sass/layout/_header.scss`.

**Comment by jino-suse** [comment]
[_header.zip](https://github.com/rancher/docs/files/9868589/_header.zip)

@catherineluse File has been attached

**Comment by btat** [comment]
Completed via https://github.com/rancher/docs/pull/4352.
