### ISSUE TITLE
[Rancher2] Broken link to Cluster Config File Reference

### ISSUE THREAD

**Issue by alphabet5** [rancher/docs#4358]
The Rancher Manager* documentation is moving. Please file any issues or pull requests at https://github.com/rancher/rancher-docs instead.

* = content/rancher

The link [here](https://rancher.com/docs/rancher/v2.6/en/cluster-admin/editing-clusters/rke2-config-reference/#editing-clusters-with-yaml) at the bottom under cluster config file reference points to [here](https://docs.rke2.io/install/install_options/server_config/) which is blank.

**Comment by btat** [comment]
This page should have redirected to our active [Rancher Manager docs site](https://ranchermanager.docs.rancher.com/v2.6/reference-guides/cluster-configuration/rancher-server-configuration/rke2-cluster-configuration#cluster-config-file-reference), which already has the broken link fixed, but there was an error in our config. The redirect is now fixed (#4359) so users won't land on this old site page with the broken link.
