### ISSUE TITLE
Default User Role: Ability to Configure

### ISSUE THREAD

**Issue by MBishop17** [rancher/docs#528]

**Comment by dramich** [comment]
To set the default user role on automatic creation:
A user is created automatically when a new user logs in for the first time through an auth provider (note this does not affecting creating a user through the UI or API as you set the required role/s when doing it this way). When this user is created it gets a globalRole assigned to it and bindings are created. The current default is User, which may have too much access so you can set a new default role that a user will get. For the role you want to set select the ellipses on the role > edit > New User Default > Yes > save. Do the same for the role you no longer want as default but select No for New User Default. Multiple roles can be set as the default. 

Cluster and Project tabs work the same way. When a user creates a project/cluster they are auto assigned as the creator and granted a specific role. Again, this role could have too much power so a custom role could be created or a current one with less access could be used. Different from global roles, cluster and project roles can also be locked. This will stop this role from being assigned going forward but will NOT remove the role if it has already been assigned to users. Multiple roles can be set as the default.
