### ISSUE TITLE
Rancher Azure Active Directory : Missing /verify-auth-azure in docs

### ISSUE THREAD

**Issue by sukrit007** [rancher/docs#555]
When configuring [Azure Active Directory](https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/azure-ad/#1-register-rancher-with-azure),  the sign on URL needs to contain /verify-auth-azure in the path, otherwise, the integration fails.

Can the screenshot be updated to capture the same (http://rancher-server-url/verify-auth-azure):
https://rancher.com/docs/img/rancher/new-app-registration.png

**Comment by superseb** [comment]
Thanks, this is covered in https://github.com/rancher/rancher/issues/14741

**Comment by deniseschannon** [comment]
Fixed docs and the next release (v2.1) should have  UI fix to make it more obvious.
