### ISSUE TITLE
rancher quick start vagrant cluster lunch kubectl not working as expected. 

### ISSUE THREAD

**Issue by senpx** [rancher/docs#566]
rancher quick start vagrant cluster lunch kubectl not working as expected, its keep trying to connect to shell for a long time. but the cluster is up and running fine.

**Comment by superseb** [comment]
As this is not really a docs issue, can you file it here: https://github.com/rancher/rancher/issues/new

Please include more info on what OS you are running Vagrant, what browser you are using, what is the actual network response from the API when you open developer tools?
