### ISSUE TITLE
Port Documentation

### ISSUE THREAD

**Issue by MBishop17** [rancher/docs#595]
- Port Requirements need more context.
- Port Requirements need charts.
- For the diagram, we need to explain that the ports used are for INSIDE the cluster.
- Need to set up two sets of port reqs. 1 for base install. 1 for addons.
- Remove outbound connection? (per Sheng)
- Add headers/update titles for different sections. (inside cluster, add ons, etc.)
- Requirements for ports between clusters
- Rest of the ports are RKE nodes to remote clusters

**Comment by jgreat** [comment]
<img width="666" alt="port-matrix-custom-nodes" src="https://user-images.githubusercontent.com/5324639/44607716-046e6e80-a7b7-11e8-89b2-47b941e9ebfd.png">

**Comment by catherineluse** [comment]
@MBishop17 I made a PR that affects the port documentation (https://github.com/rancher/docs/pull/1896) and I believe it addresses some of the points in this issue. 

- [ x]     Port Requirements need more context.
- [ x]     Port Requirements need charts.
- [ ]     For the diagram, we need to explain that the ports used are for INSIDE the cluster.
- [x ]     Need to set up two sets of port reqs. 1 for base install. 1 for addons.
- [ ]     Remove outbound connection? (per Sheng)
- [ ]     Add headers/update titles for different sections. (inside cluster, add ons, etc.)
- [ ]     Requirements for ports between clusters
- [ ]     Rest of the ports are RKE nodes to remote clusters

Could you please review the PR and let me know if the rest of the bullets still apply? If so, we might need to set up some time to understand what needs to be changed.

**Comment by catherineluse** [comment]
This issue is mostly addressed by https://github.com/rancher/docs/pull/1896

**Comment by catherineluse** [comment]
Closing this issue because https://github.com/rancher/docs/pull/1896 was merged
