### ISSUE TITLE
docker-machine instructions mission memory specification

### ISSUE THREAD

**Issue by skoslowski** [rancher/docs#615]
The [instructions for using RancherOS ](https://rancher.com/docs/os/v1.x/en/installation/running-rancheros/workstation/docker-machine/) on VirtualBox with docker-machine don't work the the latest release. The (current) [RancherOS memory requirements](https://rancher.com/docs/os/v1.x/en/overview/#hardware-requirements) exceed the default value of 1024MB. `docker-machine create ...` fails to complete (the VM crashes).

Passing e.g. `--virtualbox-memory 1280 ` fixes this:
```
docker-machine create -d virtualbox \
  --virtualbox-boot2docker-url https://releases.rancher.com/os/latest/rancheros.iso \
  --virtualbox-memory 1280 <MACHINE-NAME> 
```

Amending the command in the docs or adding a note about memory requirements would be helpful.

**Comment by deniseschannon** [comment]
These have been fixed in the following PR: https://github.com/rancher/docs/pull/686
