### ISSUE TITLE
ADFS Auth Provider docs incomplete

### ISSUE THREAD

**Issue by dnauck** [rancher/docs#616]
Currently its not very clear how to setup ADFS auth with Rancher 2.0.7:

* `Rancher API Host` - what should be in this field? Doesn't rancher know about its own URL?
* `Private Key`, `Certificate ` - is this the ADFS Token Auth Cert? Why is then a priv key required?
* `Metadata XML` - why i just can't enter my ADFS domain name (the metadata url is known) and rancher downloads everything itsself?
* what are the rancher urls for sign-in and log-out and what HTTP verb needs to be configured in ADFS?
* why does rancher does not have a metadata url that ADFS can use to configure itsself?
* what is the required hash algo to configure in ADFS? sha1, sha2?
* what is the required nameID and nameID format?
* what are the required mappings?

**Comment by deniseschannon** [comment]
We've updated the ADFS docs. Let us know if you need more information on setting it up. 

https://rancher.com/docs/rancher/v2.x/en/admin-settings/authentication/microsoft-adfs/

**Comment by dnauck** [comment]
@deniseschannon Thank you, but currently all links to the images are broken:

![image](https://user-images.githubusercontent.com/97584/44795038-09ae2d80-abaa-11e8-8ab0-d76fd7c59449.png)

**Comment by deniseschannon** [comment]
@dnauck This was fixed in live last week. Let me know if you are still having issues.
