### ISSUE TITLE
Default Roles with (Custom) in Them Need Specific RBAC Documented

### ISSUE THREAD

**Issue by bradld** [rancher/docs#625]
Default Rancher Roles often have (Custom) as a line in them for what RBAC are granted to that role.  These should be documented how they map to K8s and CRD RBAC specifically.

**Comment by jgreat** [comment]
![image](https://user-images.githubusercontent.com/5324639/45700761-96edfd80-bb2a-11e8-8eb1-9c0382c2a6e9.png)

What does this `nodes,nodepools (Custom)` mean?
