### ISSUE TITLE
Consolidate Redundant Content

### ISSUE THREAD

**Issue by MBishop17** [rancher/docs#675]
These two files duplicate content. Merge them into a single file.

https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/custom-clusters/

https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/

**Comment by deniseschannon** [comment]
We have purposely separated it into 2 sections for navigation purposes so that if you wanted to bring a custom cluster, you wouldn't have to dig 2 levels deep to find it.
