### ISSUE TITLE
RKE AWS cloud provider needs information about setting clusterID

### ISSUE THREAD

**Issue by moelsayed** [rancher/docs#701]
similar to https://github.com/rancher/rancher.github.io/pull/1024

**Comment by MBishop17** [comment]
@deniseschannon and @moelsayed, I'm not sure what needs documentation here.

These two doc pages already seem to document what's requested in rancher/rancher.github.io#1024:

- https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/custom-nodes/#amazon-only-br-tag-resources
- https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/rke-clusters/options/cloud-providers/#amazon

**Comment by moelsayed** [comment]
@MBishop17 It also needs to go into RKE docs. I've had a couple of questions about it on slack.

**Comment by MBishop17** [comment]
ok, that makes more sense. Thanks @moelsayed

**Comment by MBishop17** [comment]
Work completed. Lives at https://rancher.com/docs/rancher/v2.x/en/catalog/
