### ISSUE TITLE
Provide info on using helm charts in UI

### ISSUE THREAD

**Issue by superseb** [rancher/docs#716]
This will mostly involve linking to Helm docs, but there should be some entrypoint to using charts in the UI. Especially the types of answers (single/multiline, string, hash etc). Also a pointer to escape comma's in the values. `key=value\,value2`

**Comment by StrongMonkey** [comment]
@deniseschannon @superseb do we really need to write a doc for how to use those answers or just provide a link to their helm doc in UI?

**Comment by MBishop17** [comment]
related to #803
