### ISSUE TITLE
User Guide of CLI 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/docs#756]

**Comment by divya-mohan0209** [comment]
@deniseschannon : Does this still need to be worked upon? I was just combing through issues and am wondering if there’s anything that could be potentially added to the [existing docs](https://rancher.com/docs/rancher/v2.6/en/cli/)

**Comment by deniseschannon** [comment]
At this point, I'm not sure what else would need to be done given this is from over 3 years ago :)

**Comment by divya-mohan0209** [comment]
Is there anybody I could potentially reach out to for understanding if there's anything else we could document?

**Comment by deniseschannon** [comment]
@divya-mohan0209 Typically support or our field engineering would have feedback from what they hear from customers/prospects. Try posting an open ended question in #discuss-rancher in our slack and see if anyone has any feedback. If there is no response, feel free to close this.

**Comment by divya-mohan0209** [comment]
Thank you @deniseschannon :) Sorry for the multiple pings!
