### ISSUE TITLE
jumping to specific headings seems to have the heading hiding behind the header

### ISSUE THREAD

**Issue by deniseschannon** [rancher/docs#763]
example link:
https://rancher.com/docs/rke/v0.1.x/en/config-options/cloud-providers/aws/#iam-requirements

<img width="1070" alt="screen shot 2018-09-07 at 11 48 54 am" src="https://user-images.githubusercontent.com/11410997/45237606-098dec00-b294-11e8-9572-0578bb092437.png">

it should look like this

<img width="1216" alt="screen shot 2018-09-07 at 11 49 17 am" src="https://user-images.githubusercontent.com/11410997/45237625-13afea80-b294-11e8-8396-8ec086b6098b.png">

**Comment by vincent99** [comment]
Reasons not to have fixed headers, volume 42...  The browser puts the named element at the top of screen, it doesn't know or care if you happen to cover that area with something else.

@lvuch Normal headers have enough padding on top to still be visible but that space is hidden for the first one on the page.  So if you remove `.docs-body > h3:first-of-type, .docs-body > h2:first-of-type` it would show ok for the first one too (but have extra space at the top...)
