### ISSUE TITLE
Remove Draft Flag for 2.1 release

### ISSUE THREAD

**Issue by MBishop17** [rancher/docs#766]
go through content for 2.1 and remove `draft: true` flag and any content that's commented out.

affected files: 

- /rancher/v2.x/en/admin-settings/authentication/keycloak
- /rancher/v2.x/en/admin-settings/removing-rancher/
- /rancher/v2.x/en/admin-settings/removing-rancher/user-cluster-nodes
- /rancher/v2.x/en/admin-settings/authentication/ - make sure to display 
- /rancher/v2.x/en/k8s-in-rancher/projects-and-namespaces/project-quotas/
- /rancher/v2.x/en/k8s-in-rancher/projects-and-namespaces/editing-projects/ (comments)
- /rancher/v2.x/en/k8s-in-rancher/projects-and-namespaces/ (comments)
- /rancher/v2.x/en/admin-settings/authentication/
- /rancher/v2.x/en/installation/air-gap-installation/prepare-private-reg/
- /rancher/v2.x/en/installation/air-gap-installation/config-rancher-for-private-reg/
- /rancher/v2.x/en/installation/air-gap-installation/install-rancher/

**Comment by deniseschannon** [comment]
@MBishop17 I merged https://github.com/rancher/docs/pull/845 but it looks like we have more files to fix up.
