### ISSUE TITLE
Node Cleanup Doc

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/docs#788]
With this change https://github.com/rancher/rancher/pull/15551, Nodes that are created through docker-machine and custom driver will be cleaned up if user deletes them in k8s api. We need to add proper documentation for this behavior.

**Comment by StrongMonkey** [comment]
Move it out of 2.1. The original PR needs more discussions and testing.

**Comment by catherineluse** [comment]
@StrongMonkey Does this still need to be documented?

**Comment by divya-mohan0209** [comment]
@deniseschannon  : Does this still require to be documented? If so, would [this page](https://rancher.com/docs/rancher/v2.5/en/cluster-admin/cleaning-cluster-nodes/) be an appropriate placement area for the content?

**Comment by catherineluse** [comment]
@divya-mohan0209 That would be the correct page. We have gotten feedback that that page is somewhat confusing. It could probably use a review to improve clarity. As for whether the original issue is outdated, we'd have to ask Daishan.
