### ISSUE TITLE
Broken Link in About Page

### ISSUE THREAD

**Issue by sandeepksaini** [rancher/docs#80]
There are few broken links under "About", i.e. are:
Update Our Docs
Contributing to Rancher
FAQs

Link is here: https://rancher.com/docs/rancher/v2.x/en/about/

**Comment by deniseschannon** [comment]
I'm unable to find any broken links. please reopen if you see anything.

**Comment by sandeepksaini** [comment]
@deniseschannon I recently checked and seem like someone already fixed it.
Thanks for addressing it.
