### ISSUE TITLE
Describe how to restore clusters where system namespaces were moved into a project (after upgrading to v2.0.7 or higher)

### ISSUE THREAD

**Issue by superseb** [rancher/docs#802]
Because we introduced the System project, all setups that have had system namespaces moved into a project prior to 2.0.7, network issues will arise. We need steps to fix if an user has upgraded without moving the namespaces out of a project before upgrading.

* Steps for Rancher cluster (HA/single)
* Steps for created clusters

ref https://github.com/rancher/rancher/issues/15146

**Comment by ryanstecker** [comment]
@superseb Thanks so much for the write-up in https://gist.github.com/superseb/d2a4f7b827cff2c2c133ac5510dd51c6; it was instrumental in helping us fix an issue with our HA local cluster after the 2.0.7 upgrade.

Just want to confirm that the official docs will include details for re-creating network policies after deleting them (if this is at all necessary).

We're not sure of the implications of having deleted the network policies on our "local" cluster - like whether or not Rancher will re-create these, if we need to do additional steps, or if these policies aren't even necessary for a management cluster.

Thanks!

**Comment by MBishop17** [comment]
@superseb and @ryanstecker , I captured an issue to get the official docs updated: https://github.com/rancher/docs/issues/833
