### ISSUE TITLE
Update Air Gap Docs to include mirroring rancher server chart repo

### ISSUE THREAD

**Issue by MBishop17** [rancher/docs#822]
Continuation of #808 

https://github.com/rancher/docs/pull/808#issuecomment-422883929 

> We also need to document mirroring the rancher server chart repository, e.g. either by
> 
> 1. Creating a local helm repository to host the rancher server chart from https://github.com/rancher/server-chart,
>    or
> 2. Probably better: How to pull the packaged archive of rancher server chart and then use helm to deploy from that local package.

**Comment by jgreat** [comment]
Removing dependency on tiller and remote charts. Charts can be fetched and rendered on a system with internet access and copied to a system that has access to the cluster. #854

**Comment by catherineluse** [comment]
I think this has been added to the docs already:
- HA air gap docs about preparing a private registry: https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-high-availability/prepare-private-registry/ 
- Single node air gap docs about preparing a private registry: https://rancher.com/docs/rancher/v2.x/en/installation/air-gap-single-node/prepare-private-registry/

@MBishop17, can this issue be closed?
