### ISSUE TITLE
Code Block improvements - scroll and text size

### ISSUE THREAD

**Issue by jgreat** [rancher/docs#857]
* Don't scroll in code blocks
* Make text a little bit larger green on grey is hard to read at that size.

**Comment by lvuch** [comment]
@jgreat can you include an example where you're running into the scrolling issue as well as what os and browser.

**Comment by jgreat** [comment]
One example is https://rancher.com/docs/rke/v0.1.x/en/example-yamls/
The "Full cluster.yml example" scrolls.  
I'm using Chrome 69.0.3497.100 on Ubuntu (Linux) 18.04.  Same behavior in Chrome and Edge on Windows 10. 

This request was originally from @superseb, maybe he can point out some other places.

**Comment by lvuch** [comment]
This example is helpful, thank you. I can make it so the max height is greater or it can show the full height (we have some very long code blocks so it seemed better to scroll some within the block vs the browser window itself). The x axis will have to scroll overflow though as to not create word wrapping that breaks the code within the block

**Comment by lvuch** [comment]
https://github.com/rancherlabs/website-theme/pull/31 fixed in theme

**Comment by superseb** [comment]
Scrolling in code blocks is not convenient, if it has to be scrollable, it should indicate its scrollable (you can't determine if all code is shown)

Second problem is there is no copy paste button so you can't skip going to the code block by just copy pasting using a button.
