### ISSUE TITLE
quote/note blocks blend into the page

### ISSUE THREAD

**Issue by jgreat** [rancher/docs#897]
We use markdown blockquotes for note emphasis in our docs. In the current theme, the blockquotes tend to blend into the page and de-emphasis the content of the quote.  

The header for the note is currently gray on a light blue-gray background. For me this blends in and I loose the emphasis and importance of the note.

Can we do something to make it stand out from the page a bit more? 

An example might be the way O'Reilly books have various icons for their notes (Warning, Info). Kubernetes 1.12 API docs use 2 points of differentiation for their notes. Various color and icons for the purpose of the block.

**Comment by lvuch** [comment]
@jgreat can you send me the O'Reilly example and K8s example. Are there set types of denotations you imagine would be useful?

**Comment by jgreat** [comment]
Here's a link to the kubernetes API docs and some color coded info and notices. https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/#daemonset-v1-apps

The "Kubernetes Up & Running" book uses these symbols. All the O'Reilly books do something like this, but not necessarily these icons. 

![img_20181012_140457](https://user-images.githubusercontent.com/5324639/46889241-a2320180-ce28-11e8-837c-5e019fbb4700.jpg)

In action.  

![img_20181012_140519](https://user-images.githubusercontent.com/5324639/46889314-ddcccb80-ce28-11e8-978e-d228d6102a43.jpg)
