### ISSUE TITLE
Update install and upgrade for the new `rancher-latest/rancher` helm repo

### ISSUE THREAD

**Issue by deniseschannon** [rancher/docs#907]
* Add in a section explaining the `latest` and `stable` helm repos and the differences (similar to the diff between our latest/stable docker tags
* Update install docs to point to the latest helm repo (rancher-latest/rancher)
  * make sure to add reference of how to decide which repo to use in the install steps
* Update upgrade/rollbacks docs to point to the latest helm repo, needs mnotes in the docs to reference selecting the same repo you used

* Create an upgrade section of how to switch between different helm repos if you want to go between the latest/stable repos (we should add a link in to where we explain the repos)

**Comment by MBishop17** [comment]
Assigning over to @deniseschannon  for completion.
