### ISSUE TITLE
<<<<<<< HEAD in docs

### ISSUE THREAD

**Issue by spuder** [rancher/docs#920]
Looks like a git diff snuck into the docs

```
<<<<<<< HEAD
```

<img width="914" alt="screenshot 2018-10-18 14 59 22" src="https://user-images.githubusercontent.com/242382/47183937-8c1fb780-d2e6-11e8-8039-ae293d065af1.png">

**Comment by superseb** [comment]
Thanks for the report!

**Comment by deniseschannon** [comment]
yep, that was me. that was a fast report! haha

thanks @superseb
