### ISSUE TITLE
Helm Repo Updates Proofread Fixes

### ISSUE THREAD

**Issue by MBishop17** [rancher/docs#925]
Noticed the following issues during my review:

- "We align our latest and stable Helm chart repositories with the Docker tags that are used for a single node installation. Therefore, the rancher-latest repository will contain charts for all the Rancher versions that have been tagged as rancher/rancher:latest."

We can phrase this more succinctly.

- "Instructions on when to select these repos are available in High Availability Install."

update this to point at https://rancher.com/docs/rancher/v2.x/en/installation/server-tags/#switching-to-a-different-helm-chart-repository

- "Note:
The introduction of the rancher-latest and rancher-stable Helm Chart repositories was introduced after Rancher v2.1.0, so the rancher-stable repository contains some Rancher versions that were never marked as rancher/rancher:stable. The versions of Rancher that were tagged as rancher/rancher:stable prior to v2.1.0 are v2.0.4, v2.0.6, v2.0.8. Post v2.1.0, all charts in the rancher-stable repository will correspond with any Rancher version tagged as stable."

This note sounds like a good opportunity to make an easy-to-read table.

- Nit Pick: In helm install, titles for steps 1 and 2 use emdashes, 3 and 4 use hypens.

- https://rancher.com/docs/rancher/v2.x/en/installation/ha/. In final note, link to RKE add on install is outside of note.

- Install cert-manager. Correct note casing.

- https://rancher.com/docs/rancher/v2.x/en/upgrades/upgrades/ha-server-upgrade-helm/#upgrade-rancher: fix heading indent.

- upgrade step 2 (both vanilla and air gap). Update the text to clarify that the link explains the repos and that you need to run the command below to get the repo name. Make clarifications in the note too.

**Comment by deniseschannon** [comment]
Released with https://github.com/rancher/docs/pull/1046
