### ISSUE TITLE
Add more documentation for developers of Rancher 2

### ISSUE THREAD

**Issue by loganhz** [rancher/docs#927]
The origin issue is from https://github.com/rancher/rancher/issues/13933

I'd love to contribute to this project but reverse engineering through the code is horrible :-) The Rancher 2 architecture document is a minimal starting point for getting a feeling how the API might work.

The last days I worked on documentation and a few scripts which enable me to remote debug Rancher 2 from a GO IDE. I created a pull request for that:

https://github.com/rancher/rancher/pull/13932

Please please please create more documentation about how Rancher 2 works, how we can contribute to fix bugs and enhance it. Maybe it's also a good idea to create a Slack channel for Rancher Developers.

This project is awesome and we want to get our hands on it. Give us more documentation, please :-) !

Josef

**Comment by vincent99** [comment]
This is the kind of thing that goes in the repo, not the public-facing user documentation.

**Comment by catherineluse** [comment]
@vincent99 I was wondering, since there's already a [contributing](https://rancher.com/docs/rancher/v2.x/en/contributing/) section in the docs, should we just put a link to the [wiki](https://github.com/rancher/rancher/wiki/Setting-Up-Rancher-2.0-Development-Environment) in it?

**Comment by vincent99** [comment]
Sure that works
