### ISSUE TITLE
nginx config example is invalid

### ISSUE THREAD

**Issue by spuder** [rancher/docs#954]
The documentation example to setup a level 4 load balancer does not work because `proxy_pass` must be inside of a `location` directive

https://rancher.com/docs/rancher/v2.x/en/installation/ha/rke-add-on/layer-4-lb/#b-create-nginx-configuration

Attempting to use the example as provided
```
worker_processes 4;
worker_rlimit_nofile 40000;

events {
    worker_connections 8192;
}

http {
    server {
        listen         80;
        return 301 https://$host$request_uri;
    }
}

stream {
    upstream rancher_servers {
        least_conn;
        server IP_NODE_1:443 max_fails=3 fail_timeout=5s;
        server IP_NODE_2:443 max_fails=3 fail_timeout=5s;
        server IP_NODE_3:443 max_fails=3 fail_timeout=5s;
    }
    server {
        listen     443;
        proxy_pass rancher_servers;
    }
}
```

Returns this nginx error

```
nginx -t
2018/10/29 13:47:00 [emerg] 10467#10467: "proxy_pass" directive is not allowed here in /etc/nginx/sites-enabled/rancher.conf:9
```

**Comment by superseb** [comment]
This is being revised in https://github.com/rancher/docs/issues/935, what version of NGINX is this on?

**Comment by spuder** [comment]
nginx version: nginx/1.11.13

**Comment by superseb** [comment]
It is tested on stable, which is 1.14. 1.11.13 is over 2 years old

**Comment by spuder** [comment]
😞 You are right. I misread `1.11.13` as `1.13`. Off to upgrade all our loadbalancers first.
