### ISSUE TITLE
Document that users must edit cluster after upgrade before etcd snapshots are enabled in 2.1.2

### ISSUE THREAD

**Issue by bmdepesa** [rancher/docs#985]
After an upgrade to v2.1.2, editing a cluster and viewing the settings (or viewing in the API) shows the default values of etcd snapshots being enabled. 

The user must save the cluster to force an update to actually enable the snapshots.

https://github.com/rancher/rancher/issues/16556

**Comment by deniseschannon** [comment]
This was actually fixed in the release and no longer needs to be documented.
