### ISSUE TITLE
Fix doc inconsistencies

### ISSUE THREAD

**Issue by MBishop17** [rancher/docs#990]
Noted issues:

1. Term used for YAML entries--prefer `directive` over `field` and `construct`.
2. Numbers in title--use periods instead of colons, hyphens, or emdashes.
3. Outline lists. Use regular bullets, put num in text.
4. menu cascade steps. 
5. Replace elipsis with "Context" menu.
6. Come up with name for navigation menu.

**Comment by catherineluse** [comment]
Closing this issue because we're deferring to the Microsoft Manual of Style
